import {getAuthUserId} from '@convex-dev/auth/server';
import {mutationGeneric as mutation,queryGeneric as query} from 'convex/server';
import {v} from 'convex/values';
async function identity(ctx:any){const id=await getAuthUserId(ctx);if(!id)throw new Error('Sign in to use campaigns.');return id}
async function access(ctx:any,campaignId:any,gm=false){const userId=await identity(ctx),campaign=await ctx.db.get(campaignId);if(!campaign)throw new Error('Campaign not found.');const member=await ctx.db.query('campaignMembers').withIndex('by_campaign_user',(q:any)=>q.eq('campaignId',campaignId).eq('userId',userId)).unique();if(campaign.ownerId!==userId&&(!member||gm&&member.role!=='gm'))throw new Error('Campaign access denied.');return {userId,campaign,isGM:campaign.ownerId===userId||member?.role==='gm'}}
function text(value:string,max:number){if(!value.trim()||value.length>max)throw new Error('Please enter text within the allowed length.');return value.trim()}
export const list=query({args:{},handler:async(ctx)=>{const id=await getAuthUserId(ctx);if(!id)return [];const owned=await ctx.db.query('campaigns').withIndex('by_owner',q=>q.eq('ownerId',id)).collect();const memberships=await ctx.db.query('campaignMembers').withIndex('by_user',q=>q.eq('userId',id)).collect();const joined=await Promise.all(memberships.map(m=>ctx.db.get(m.campaignId)));return [...new Map([...owned,...joined.filter(Boolean)].map((c:any)=>[c._id,c])).values()].map((c:any)=>({_id:c._id,name:c.name,system:c.system,isGM:c.ownerId===id||memberships.some(m=>m.campaignId===c._id&&m.role==='gm')}))}});
export const workspace=query({args:{campaignId:v.id('campaigns')},handler:async(ctx,{campaignId})=>{const {userId,campaign,isGM}=await access(ctx,campaignId);const adventures=await ctx.db.query('adventures').withIndex('by_campaign',q=>q.eq('campaignId',campaignId)).collect();const sceneGroups=isGM?await Promise.all(adventures.map(a=>ctx.db.query('scenes').withIndex('by_adventure',q=>q.eq('adventureId',a._id)).collect())):[];const members=await ctx.db.query('campaignMembers').withIndex('by_campaign_user',q=>q.eq('campaignId',campaignId)).collect();const party=await Promise.all(members.map(async m=>{const c=m.characterId?await ctx.db.get(m.characterId):null;const p=await ctx.db.query('profiles').withIndex('by_owner',q=>q.eq('ownerId',m.userId)).unique();return {userId:m.userId,characterName:c?.name||'Character not attached',profileHandle:p?.reviewStatus==='approved'&&p.publicSnapshot?p.handle:null}}));const journals=(await ctx.db.query('privateJournals').withIndex('by_owner',q=>q.eq('ownerId',userId)).collect()).filter(j=>j.campaignId===campaignId);return {name:campaign.name,system:campaign.system,isGM,adventures,scenes:sceneGroups.flat(),party,journals}}});
export const addAdventure=mutation({args:{campaignId:v.id('campaigns'),title:v.string()},handler:async(ctx,{campaignId,title})=>{await access(ctx,campaignId,true);return ctx.db.insert('adventures',{campaignId,title:text(title,160),updatedAt:Date.now()})}});
export const saveScene=mutation({args:{adventureId:v.id('adventures'),id:v.optional(v.id('scenes')),title:v.string(),notes:v.string()},handler:async(ctx,args)=>{const adventure=await ctx.db.get(args.adventureId);if(!adventure)throw new Error('Adventure not found.');await access(ctx,adventure.campaignId,true);if(args.notes.length>30000)throw new Error('Scene notes too long.');const data={adventureId:args.adventureId,title:text(args.title,160),notes:args.notes,updatedAt:Date.now()};if(args.id){const scene=await ctx.db.get(args.id);if(!scene||scene.adventureId!==args.adventureId)throw new Error('Scene not found.');await ctx.db.patch(args.id,data);return args.id}return ctx.db.insert('scenes',data)}});
export const invite=mutation({args:{campaignId:v.id('campaigns')},handler:async(ctx,{campaignId})=>{await access(ctx,campaignId,true);const token=crypto.randomUUID()+crypto.randomUUID();await ctx.db.insert('campaignInvites',{campaignId,token,expiresAt:Date.now()+86400000});return token}});
export const join=mutation({args:{token:v.string(),characterId:v.id('characters')},handler:async(ctx,{token,characterId})=>{const userId=await identity(ctx);const invite=await ctx.db.query('campaignInvites').withIndex('by_token',q=>q.eq('token',token)).unique();if(!invite||invite.expiresAt<Date.now())throw new Error('Invitation expired or invalid.');const character=await ctx.db.get(characterId);if(!character||character.ownerId!==userId)throw new Error('Choose your own saved character.');const campaign=await ctx.db.get(invite.campaignId);if(!campaign)throw new Error('Campaign not found.');if(campaign.system&&((['dnd5e','pathfinder2e'].includes(character.setting||'')?character.setting:'savageWorlds')!==campaign.system))throw new Error('Choose a character for this campaign’s game system.');const old=await ctx.db.query('campaignMembers').withIndex('by_campaign_user',q=>q.eq('campaignId',invite.campaignId)).filter(q=>q.eq(q.field('userId'),userId)).unique();if(old)await ctx.db.patch(old._id,{characterId});else await ctx.db.insert('campaignMembers',{campaignId:invite.campaignId,userId,characterId,role:'player'});await ctx.db.delete(invite._id);return invite.campaignId}});

export const setSystem=mutation({args:{campaignId:v.id('campaigns'),system:v.union(v.literal('dnd5e'),v.literal('savageWorlds'),v.literal('pathfinder2e'))},handler:async(ctx,{campaignId,system})=>{const {campaign}=await access(ctx,campaignId,true);if(campaign.system&&campaign.system!==system)throw new Error('This campaign already has a game system. Create a separate campaign for another game.');const members=await ctx.db.query('campaignMembers').withIndex('by_campaign_user',q=>q.eq('campaignId',campaignId)).collect();for(const m of members){if(m.characterId){const c=await ctx.db.get(m.characterId);if(c&&((['dnd5e','pathfinder2e'].includes(c.setting||'')?c.setting:'savageWorlds')!==system))throw new Error('A linked character belongs to another game system.');}}await ctx.db.patch(campaignId,{system,updatedAt:Date.now()});}});
