import {getAuthUserId} from '@convex-dev/auth/server';
import {mutation,query} from './_generated/server';
import {v} from 'convex/values';
import { reviewedAuthor } from './chronicleVisibility';
const pair=(a:string,b:string)=>[a,b].sort().join(':');
async function identity(ctx:any){const id=await getAuthUserId(ctx);if(!id)throw new Error('Sign in to connect with players.');if((await ctx.db.get(id))?.communityPausedAt!==undefined)throw new Error('Community access is paused.');return id;}
async function profile(ctx:any,userId:any){return reviewedAuthor(ctx,userId);}
async function target(ctx:any,handle:string){const p=await ctx.db.query('profiles').withIndex('by_handle',(q:any)=>q.eq('handle',handle.trim().toLowerCase())).unique();if(!p||!await profile(ctx,p.ownerId))throw new Error('Profile unavailable.');return p;}
async function blocked(ctx:any,a:any,b:any){return !!(await ctx.db.query('friendBlocks').withIndex('by_owner_blocked',(q:any)=>q.eq('ownerId',a).eq('blockedId',b)).unique());}
export const blockedPlayers=query({args:{},handler:async(ctx)=>{const id=await getAuthUserId(ctx);if(!id)return [];const rows=await ctx.db.query('friendBlocks').withIndex('by_owner',q=>q.eq('ownerId',id)).collect();return Promise.all(rows.map(async r=>{const p=await profile(ctx,r.blockedId);return {_id:r._id,handle:p?.handle||null,displayName:p?.publicSnapshot?.displayName||p?.handle||'Unavailable profile'};}));}});
export const unblock=mutation({args:{id:v.id('friendBlocks')},handler:async(ctx,{id})=>{const owner=await identity(ctx),row=await ctx.db.get(id);if(!row||row.ownerId!==owner)throw new Error('Blocked player not found.');await ctx.db.delete(id);}});
export const connections=query({args:{},handler:async(ctx)=>{const id=await getAuthUserId(ctx);if(!id)return [];const rows=[...await ctx.db.query('friendships').withIndex('by_sender',q=>q.eq('senderId',id)).collect(),...await ctx.db.query('friendships').withIndex('by_recipient',q=>q.eq('recipientId',id)).collect()];const result=[];for(const row of rows){if(row.status==='declined')continue;const other=row.senderId===id?row.recipientId:row.senderId;if(await blocked(ctx,id,other)||await blocked(ctx,other,id))continue;const p=await profile(ctx,other);if(!p)continue;const s=p.publicSnapshot;result.push({_id:row._id,status:row.status,incoming:row.recipientId===id,handle:p.handle,displayName:s.displayName||p.handle,games:s.games||[],avatarUrl:s.avatarId?await ctx.storage.getUrl(s.avatarId):null});}return result;}});
export const relationship=query({args:{handle:v.string()},handler:async(ctx,{handle})=>{const id=await getAuthUserId(ctx);if(!id)return 'signed-out';const p=await ctx.db.query('profiles').withIndex('by_handle',q=>q.eq('handle',handle.trim().toLowerCase())).unique();if(!p||!await profile(ctx,p.ownerId)||(await ctx.db.get(id))?.communityPausedAt!==undefined)return 'unavailable';if(p.ownerId===id)return 'self';if(await blocked(ctx,id,p.ownerId))return 'blocked';if(await blocked(ctx,p.ownerId,id))return 'unavailable';const row=await ctx.db.query('friendships').withIndex('by_pair',q=>q.eq('pair',pair(id,p.ownerId))).unique();return row?.status==='accepted'?'friends':row?.status==='pending'?(row.recipientId===id?'incoming':'outgoing'):'none';}});
export const request=mutation({args:{handle:v.string()},handler:async(ctx,{handle})=>{const id=await identity(ctx),p=await target(ctx,handle);if(p.ownerId===id)throw new Error('This is your own profile.');if(!await profile(ctx,id))throw new Error('Save your profile and complete public-profile review before sending requests.');if(await blocked(ctx,id,p.ownerId)||await blocked(ctx,p.ownerId,id))throw new Error('Unable to send this request.');const key=pair(id,p.ownerId),old=await ctx.db.query('friendships').withIndex('by_pair',q=>q.eq('pair',key)).unique(),now=Date.now();if(old&&old.status!=='declined')throw new Error('You already have a connection or pending request.');if(old&&now-old.updatedAt<7*86400000)throw new Error('Please wait before sending another request.');const sent=await ctx.db.query('friendships').withIndex('by_sender',q=>q.eq('senderId',id)).collect();if(sent.filter(r=>r.status==='pending').length>=20||sent.filter(r=>r.createdAt>now-86400000).length>=20)throw new Error('Request limit reached. Try again later.');const data={pair:key,senderId:id,recipientId:p.ownerId,status:'pending' as const,createdAt:now,updatedAt:now};if(old){await ctx.db.patch(old._id,data);return old._id;}return ctx.db.insert('friendships',data);}});
export const respond=mutation({args:{handle:v.string(),accept:v.boolean()},handler:async(ctx,{handle,accept})=>{const id=await identity(ctx),p=await target(ctx,handle);const row=await ctx.db.query('friendships').withIndex('by_pair',q=>q.eq('pair',pair(id,p.ownerId))).unique();if(!row||row.recipientId!==id||row.status!=='pending')throw new Error('No incoming request.');if(await blocked(ctx,id,p.ownerId)||await blocked(ctx,p.ownerId,id))throw new Error('Connection unavailable.');await ctx.db.patch(row._id,{status:accept?'accepted':'declined',updatedAt:Date.now()});}});
export const remove=mutation({args:{handle:v.string()},handler:async(ctx,{handle})=>{const id=await identity(ctx),p=await target(ctx,handle);const row=await ctx.db.query('friendships').withIndex('by_pair',q=>q.eq('pair',pair(id,p.ownerId))).unique();if(row)await ctx.db.patch(row._id,{status:'declined',updatedAt:Date.now()});}});
export const block=mutation({args:{handle:v.string(),blocked:v.boolean()},handler:async(ctx,{handle,blocked:shouldBlock})=>{const id=await identity(ctx),p=await target(ctx,handle);if(id===p.ownerId)throw new Error('Cannot block your own profile.');const old=await ctx.db.query('friendBlocks').withIndex('by_owner_blocked',q=>q.eq('ownerId',id).eq('blockedId',p.ownerId)).unique();if(shouldBlock&&!old)await ctx.db.insert('friendBlocks',{ownerId:id,blockedId:p.ownerId});if(!shouldBlock&&old)await ctx.db.delete(old._id);if(shouldBlock){const row=await ctx.db.query('friendships').withIndex('by_pair',q=>q.eq('pair',pair(id,p.ownerId))).unique();if(row)await ctx.db.patch(row._id,{status:'declined',updatedAt:Date.now()});}}});
