import {convexTest} from 'convex-test';
import {test,expect} from 'vitest';
import {makeFunctionReference as ref} from 'convex/server';
import schema from './schema';
const modules=import.meta.glob('./**/*.ts');
async function setup(){const t=convexTest(schema,modules);const people=await t.run(async ctx=>{const result=[];for(const [handle,games] of [['alice',['Savage Worlds']],['bob',['Dungeons & Dragons']],['eve',['Other games']]] as [string,string[]][]){const ownerId=await ctx.db.insert('users',{email:handle+'@example.test'});const profileId=await ctx.db.insert('profiles',{ownerId,handle,displayName:handle,bio:'PRIVATE DRAFT',games,memory:'private',roles:['player'],links:[],favorites:[],highlights:[],appearance:{background:'midnight',accent:'gold',font:'classic',layout:'balanced',sections:[]},ageConfirmedAt:Date.now(),updatedAt:Date.now(),reviewStatus:'approved',publicSnapshot:{displayName:handle,games}});result.push({ownerId,profileId});}return result;});const clients=people.map(p=>({...p,client:t.withIdentity({subject:p.ownerId})}));return {t,a:clients[0],b:clients[1],e:clients[2]};}
test('players connect across games only after recipient accepts; strangers cannot see connections',async()=>{const {t,a,b,e}=await setup();await a.client.mutation(ref<'mutation'>('friends:request'),{handle:'bob'});expect(await a.client.query(ref<'query'>('friends:relationship'),{handle:'bob'})).toBe('outgoing');await expect(a.client.mutation(ref<'mutation'>('friends:respond'),{handle:'bob',accept:true})).rejects.toThrow('No incoming');await expect(e.client.mutation(ref<'mutation'>('friends:respond'),{handle:'alice',accept:true})).rejects.toThrow('No incoming');await b.client.mutation(ref<'mutation'>('friends:respond'),{handle:'alice',accept:true});const rows:any=await a.client.query(ref<'query'>('friends:connections'),{});expect(rows[0].status).toBe('accepted');expect(rows[0].games).toEqual(['Dungeons & Dragons']);expect(JSON.stringify(rows)).not.toContain('PRIVATE DRAFT');expect(await e.client.query(ref<'query'>('friends:connections'),{})).toEqual([]);expect(await t.query(ref<'query'>('friends:connections'),{})).toEqual([]);});
test('blocks, duplicate requests, cooldown, and private profiles prevent unwanted connections',async()=>{const {t,a,b}=await setup();await a.client.mutation(ref<'mutation'>('friends:request'),{handle:'bob'});await expect(a.client.mutation(ref<'mutation'>('friends:request'),{handle:'bob'})).rejects.toThrow('already');await b.client.mutation(ref<'mutation'>('friends:block'),{handle:'alice',blocked:true});expect(await a.client.query(ref<'query'>('friends:connections'),{})).toEqual([]);await expect(a.client.mutation(ref<'mutation'>('friends:request'),{handle:'bob'})).rejects.toThrow('Unable');await b.client.mutation(ref<'mutation'>('friends:block'),{handle:'alice',blocked:false});await expect(a.client.mutation(ref<'mutation'>('friends:request'),{handle:'bob'})).rejects.toThrow('wait');await t.run(ctx=>ctx.db.patch(b.profileId,{reviewStatus:'private',publicSnapshot:undefined}));await expect(a.client.mutation(ref<'mutation'>('friends:request'),{handle:'bob'})).rejects.toThrow('unavailable');await expect(t.mutation(ref<'mutation'>('friends:request'),{handle:'bob'})).rejects.toThrow('Sign in');});
test('only block owner can unblock; private profile details remain hidden',async()=>{const {t,a,b,e}=await setup();await a.client.mutation(ref<'mutation'>('friends:block'),{handle:'bob',blocked:true});const blocks:any=await a.client.query(ref<'query'>('friends:blockedPlayers'),{});await expect(e.client.mutation(ref<'mutation'>('friends:unblock'),{id:blocks[0]._id})).rejects.toThrow('not found');await t.run(ctx=>ctx.db.patch(b.profileId,{reviewStatus:'private',publicSnapshot:undefined}));const hidden:any=await a.client.query(ref<'query'>('friends:blockedPlayers'),{});expect(hidden[0].handle).toBeNull();expect(hidden[0].displayName).toBe('Unavailable profile');await a.client.mutation(ref<'mutation'>('friends:unblock'),{id:blocks[0]._id});expect(await a.client.query(ref<'query'>('friends:blockedPlayers'),{})).toEqual([]);});
