export const ruleSets: {id:string;name:string;detail:string}[];
export const worldSections: string[][];
export function newWorld(): any;
export function foundationIssues(world:any): string[];
export function worldIssues(world:any): string[];
export function ruleSetName(world:any): string;
export function validateWorld(world:any,options?:{draft?:boolean}): any;
export function worldBackup(world:any): any;
export function readWorldBackup(snapshot:any): any;
