import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {ConvexReactClient,useConvexAuth,useQuery,useMutation} from 'convex/react';
import {ConvexAuthProvider} from '@convex-dev/auth/react';
import {makeFunctionReference as ref} from 'convex/server';
import {CharacterAccount} from './account.jsx';
import './campaigns.css';
const refs=Object.fromEntries(['list','workspace','addAdventure','saveScene','invite','join'].map(n=>[n,ref('campaigns:'+n)]));
function Workspace(){
 const {isAuthenticated}=useConvexAuth(),[campaign,setCampaign]=useState(''),[adventure,setAdventure]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[link,setLink]=useState('');
 const list=useQuery(refs.list,isAuthenticated?{}:'skip'),data=useQuery(refs.workspace,isAuthenticated&&campaign?{campaignId:campaign}:'skip'),characters=useQuery(ref('characters:list'),isAuthenticated?{}:'skip');
 const create=useMutation(ref('privateWorkspaces:createCampaign')),add=useMutation(refs.addAdventure),save=useMutation(refs.saveScene),journal=useMutation(ref('privateWorkspaces:saveJournal')),invite=useMutation(refs.invite),join=useMutation(refs.join);
 const token=new URLSearchParams(location.search).get('invite');
 useEffect(()=>{if(!isAuthenticated){setCampaign('');setAdventure('');setLink('')}},[isAuthenticated]);
 async function run(action){setBusy(true);setStatus('');try{await action();setStatus('Saved to your account.')}catch(e){setStatus(e.message.replace(/\[CONVEX[^\]]*\]/g,'').replace(/Called by client/g,'').trim())}finally{setBusy(false)}}
 function form(action){return e=>{e.preventDefault();const f=e.currentTarget,values=Object.fromEntries(new FormData(f));run(async()=>{await action(values);f.reset()})}}
 return <main><nav className="workspace-nav" aria-label="Workspace"><a href="/">Characters</a><a href="/campaigns" aria-current="page">Campaigns</a><a href="/profile">My Profile</a></nav><header><h1>Savage Master</h1><p>Your campaigns, adventures, and memories at the table.</p></header><CharacterAccount accountOnly/>{isAuthenticated&&<>
 {token&&<section><h2>Join a campaign</h2><p>Choose a character you have saved in your account.</p><form onSubmit={form(async v=>{setCampaign(await join({token,characterId:v.character}));history.replaceState({},'',location.pathname)})}><select name="character" required><option value="">Choose character</option>{characters?.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select><button disabled={busy}>Join campaign</button></form></section>}
 <section><h2>Campaign Tome</h2><label>Open campaign<select value={campaign} onChange={e=>{setCampaign(e.target.value);setAdventure('');setLink('')}}><option value="">Choose a campaign</option>{list?.map(c=><option key={c._id} value={c._id}>{c.name} · {c.isGM?'GM':'Player'}</option>)}</select></label><form onSubmit={form(async v=>{setCampaign(await create({name:v.name}));setAdventure('')})}><input name="name" placeholder="New campaign name" aria-label="New campaign name" maxLength={160} required/><button disabled={busy}>Create campaign</button></form>{list?.length===0&&<p>Create your first campaign, or open an invitation from your GM.</p>}</section>
 {data&&<><section><h2>{data.name}</h2><p>{data.isGM?'GM workspace · Scenes and preparation stay private.':'Player workspace · Your journal stays private.'}</p><h3>Party</h3>{data.party.length?data.party.map(p=><p key={p.userId}>{p.characterName}</p>):<p>Invite players to build your party.</p>}{data.isGM&&<><button disabled={busy} onClick={()=>run(async()=>setLink(location.origin+'/campaigns.html?invite='+await invite({campaignId:campaign})))}>Create player invitation</button>{link&&<label>One-use link · expires in 24 hours<input readOnly value={link} onFocus={e=>e.target.select()}/></label>}</>}</section>
 <div className="columns"><section><h2>Adventures</h2><label>Current adventure<select value={adventure} onChange={e=>setAdventure(e.target.value)}><option value="">Choose an adventure</option>{data.adventures.map(a=><option key={a._id} value={a._id}>{a.title}</option>)}</select></label>{data.isGM&&<form onSubmit={form(async v=>setAdventure(await add({campaignId:campaign,title:v.title})))}><input name="title" placeholder="Adventure title" aria-label="Adventure title" required maxLength={160}/><button disabled={busy}>Add adventure</button></form>}{data.isGM&&adventure&&<><h3>Scene preparation</h3>{data.scenes.filter(s=>s.adventureId===adventure).map(s=><article key={s._id}><h3>{s.title}</h3><p className="notes">{s.notes}</p><details><summary>Edit scene</summary><form onSubmit={form(v=>save({id:s._id,adventureId:adventure,title:v.title,notes:v.notes}))}><input name="title" defaultValue={s.title} aria-label="Edit scene title" required maxLength={160}/><textarea name="notes" defaultValue={s.notes} aria-label="Edit scene notes" maxLength={30000}/><button disabled={busy}>Update scene</button></form></details></article>)}<form onSubmit={form(v=>save({adventureId:adventure,title:v.title,notes:v.notes}))}><input name="title" placeholder="Scene title" aria-label="Scene title" required maxLength={160}/><textarea name="notes" placeholder="Details, NPCs, clues, and stats" aria-label="Scene notes" maxLength={30000}/><button disabled={busy}>Save scene</button></form></>}</section>
 <section><h2>{data.isGM?'Private GM Journal':'Personal Player Journal'}</h2><p>Only you can read these entries.</p>{data.journals.map(j=><article key={j._id}><small>{new Date(j.updatedAt).toLocaleDateString()}</small><p className="notes">{j.text}</p></article>)}<form onSubmit={form(v=>journal({campaignId:campaign,kind:data.isGM?'gm':'player',text:v.text}))}><textarea name="text" placeholder="Write a memory or private note…" aria-label="Journal entry" required maxLength={30000}/><button disabled={busy}>Save journal entry</button></form></section></div></>}
 </>}<p className="workspace-status" role="status">{busy?'Saving…':status}</p></main>
}
const url=import.meta.env.VITE_CONVEX_URL;
createRoot(document.getElementById('campaignRoot')).render(url?<ConvexAuthProvider client={new ConvexReactClient(url)}><Workspace/></ConvexAuthProvider>:<p>Campaigns need a configured Convex deployment.</p>);
