import React,{useEffect,useState} from 'react';
import {classData,spellAbility,backgrounds} from './dnd-model.mjs';
import {spellSlots} from './dnd-play.mjs';
import {spellLevel,spellSchool,spellUse,spellMatches} from './dnd-spells.mjs';
import {spellGuidance} from './dnd-spell-guidance.mjs';
import {SpellBook} from './dnd-sheet.jsx';
const pdf='https://media.dndbeyond.com/compendium-images/srd/5.2/SRD_CC_v5.2.1.pdf';
export function SpellLibrary({c,update}){
 const [rows,setRows]=useState(null),[error,setError]=useState(false),[retry,setRetry]=useState(0),[search,setSearch]=useState(''),[classFilter,setClassFilter]=useState('All'),[level,setLevel]=useState('all'),[school,setSchool]=useState('All'),[use,setUse]=useState('All'),[ritual,setRitual]=useState(false),[concentration,setConcentration]=useState(false),[other,setOther]=useState(false),[limit,setLimit]=useState(8),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;setError(false);import('./dnd-rules-data/spells.json').then(m=>{if(active)setRows(m.default);}).catch(()=>{if(active)setError(true);});return()=>{active=false;};},[retry]);
 const book=c?.spellbook||[],source=c?(Object.hasOwn(spellAbility,c.className)?c.className:backgrounds[c.background].feat.includes('Wizard')?'Wizard':backgrounds[c.background].feat.includes('Cleric')?'Cleric':null):null,slots=c?(c.slotTotals||spellSlots(c)):[],maxLevel=c?Math.max(1,slots.reduce((max,n,i)=>n>0?i+1:max,0)):9,effectiveClass=c&&!other?(source||'No class spells'):classFilter,effectiveMax=c&&!other?maxLevel:9;
 const guide=c?spellGuidance[c.className]?.levels[c.level-1]:null,cantrips=book.filter(b=>{const r=rows?.find(r=>r.name===b.name);return r&&spellLevel(r)===0;}).length,prepared=book.filter(b=>{const r=rows?.find(r=>r.name===b.name);return b.prepared&&r&&spellLevel(r)>0;}).length;
 const found=(rows||[]).filter(r=>spellMatches(r,{search,className:effectiveClass,level,maxLevel:effectiveMax,school,use,ritual,concentration}));
 useEffect(()=>setLimit(8),[search,classFilter,level,school,use,ritual,concentration,other,c?.className,c?.level]);
 function add(row){update({spellbook:[...book,{name:row.name,prepared:false}]});setNotice(row.name+' added to your spell book.');}
 return <div className="dnd-spell-library"><div className="dnd-library-banner dnd-magic-banner"><span aria-hidden="true">✦</span><div><h2>{c?'Discover your magic':'Spell library'}</h2><p>{c?'Choose the magic you want at your fingertips.':'Explore the open spells by class, level, school, and purpose.'}</p></div></div>{c&&<div className="dnd-spell-summary"><span><strong>{book.length}</strong> {book.length===1?'spell':'spells'} in your book</span><span><strong>{book.filter(b=>b.prepared).length}</strong> marked ready</span><span>{c.className} · level {c.level}</span></div>}
 {guide&&<div className="dnd-spell-guide"><div><small>Class cantrips</small><strong>{cantrips} / {guide.cantrips}</strong></div><div><small>Class prepared spells</small><strong>{prepared} / {guide.prepared}</strong></div>{c.className==='Wizard'&&<div><small>Wizard spell-book guide</small><strong>{book.length-cantrips} / {6+2*(c.level-1)}+</strong></div>}<p>Class-table guidance. Spells granted by other features may be additional; confirm their source with your GM.</p></div>}
 <div className="dnd-spell-search"><label>Find a spell<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try fire, healing, invisibility…"/></label><label>Spell level<select value={level} onChange={e=>setLevel(e.target.value)}><option value="all">{c&&!other?'Available levels':'All levels'}</option><option value="0">Cantrips · no spell slots</option>{Array.from({length:effectiveMax},(_,i)=><option key={i} value={i+1}>Level {i+1}</option>)}</select></label><label>School<select value={school} onChange={e=>setSchool(e.target.value)}>{['All','Abjuration','Conjuration','Divination','Enchantment','Evocation','Illusion','Necromancy','Transmutation'].map(n=><option key={n}>{n}</option>)}</select></label></div>
 {c?<><p className="dnd-note">{source&&!other?`Showing ${source} spells through level ${maxLevel}.`:'Spells from another source must be granted by a feature or your GM.'} Adding to your book does not automatically grant the spell or expend a slot.</p><label className="dnd-check"><input type="checkbox" checked={other} onChange={e=>{setOther(e.target.checked);setLevel('all');}}/>Browse other granted spells (species, feats, subclasses, or GM)</label></>:<p className="dnd-note">Add spells to your character in Create character → Spells.</p>}
 {(!c||other)&&<label>Spell class<select value={classFilter} onChange={e=>setClassFilter(e.target.value)}>{['All',...Object.keys(spellAbility)].map(n=><option key={n}>{n}</option>)}</select></label>}
 <nav className="dnd-category-nav dnd-spell-uses" aria-label="Browse spells by use">{['All','Damage','Healing','Protection','Control','Utility','Summoning'].map(n=><button aria-pressed={use===n} key={n} onClick={()=>setUse(n)}>{n==='All'?'All magic':n}</button>)}</nav><div className="dnd-spell-filters"><label className="dnd-check"><input type="checkbox" checked={ritual} onChange={e=>setRitual(e.target.checked)}/>Ritual spells</label><label className="dnd-check"><input type="checkbox" checked={concentration} onChange={e=>setConcentration(e.target.checked)}/>Concentration spells</label><button onClick={()=>{setSearch('');setLevel('all');setSchool('All');setUse('All');setRitual(false);setConcentration(false);setClassFilter('All');}}>Clear filters</button></div>
 {c&&<details className="dnd-inline-library"><summary>How many spells can I choose?</summary><p>Your class defines how many cantrips and spells you learn or prepare. A Wizard begins with six level-one spells in their book and adds at least two whenever they gain a Wizard level. They can copy more spells through play. Their prepared list is separate from the spells in their book. Granted spells and free casts may use different limits. Mark your ready spells in My spell book, and record special sources in your notes.</p><a href={pdf+'#page='+classData[c.className].page} target="_blank" rel="noopener noreferrer">Read {c.className} spellcasting & preparation rules ↗</a></details>}
 {error?<p role="alert">Spells could not load. <button onClick={()=>setRetry(n=>n+1)}>Try again</button></p>:!rows?<p role="status">Opening the spell library…</p>:<><p role="status">{found.length} {found.length===1?'spell':'spells'} found · showing {Math.min(limit,found.length)}</p>{!found.length&&<p>No spells match. Clear the filters{c?' or browse other granted spells':''}.</p>}<div className="dnd-grid dnd-spell-choice-cards">{found.slice(0,limit).map(r=>{const owned=book.find(b=>b.name===r.name),lvl=spellLevel(r),icon={'Damage':'✹','Healing':'✚','Protection':'◇','Control':'⌁','Utility':'✦','Summoning':'◈'}[spellUse(r)];return <article key={r.name} className={owned?'in-book':''}><div className="dnd-spell-card-title"><span aria-hidden="true">{icon}</span><div><h3>{r.name}</h3><small>{lvl===0?'Cantrip':'Level '+lvl} · {spellSchool(r)} · {spellUse(r)}</small></div></div><dl className="dnd-casting-details">{r.stats.map(stat=>{const i=stat.indexOf(':');return <div key={stat}><dt>{stat.slice(0,i)}</dt><dd>{stat.slice(i+1).trim()}</dd></div>;})}</dl><p>{r.description.length>280?r.description.slice(0,280).replace(/\s+\S*$/,'')+'…':r.description}</p><details className="dnd-spell-effect"><summary>Full effect & higher-level casting</summary><p>{r.fullDescription||r.description}</p><a href={pdf+'#page='+r.page} target="_blank" rel="noopener noreferrer">Official SRD · page {r.page} ↗</a></details>{update&&<div className="dnd-spell-pick-actions">{owned?<><span className="dnd-in-book">✓ In your spell book</span><label className="dnd-check"><input type="checkbox" checked={owned.prepared} onChange={e=>update({spellbook:book.map(b=>b.name===r.name?{...b,prepared:e.target.checked}:b)})}/>Prepared / ready</label></>:<button disabled={book.length>=339} onClick={()=>add(r)}>Add to spell book</button>}</div>}</article>;})}</div>{limit<found.length&&<button onClick={()=>setLimit(n=>n+8)}>Discover 8 more spells</button>}</>}<p role="status">{notice}</p></div>;
}
export function SpellStudio({c,update}){const [area,setArea]=useState('Choose spells');return <><nav className="dnd-category-nav" aria-label="Spell workspace">{['Choose spells','My spell book'].map(n=><button key={n} aria-pressed={area===n} onClick={()=>setArea(n)}>{n}{n==='My spell book'?' ('+(c.spellbook||[]).length+')':''}</button>)}</nav>{area==='Choose spells'?<SpellLibrary c={c} update={update}/>:<SpellBook c={c} update={update} editing/>}</>;}
