import React,{useState} from 'react';
import {classData,abilities} from './dnd-model.mjs';
import {classLevels,classLabel,multiclassIssues,multiclassRequirements} from './dnd-multiclass.mjs';
import {creationNotice} from './creation-notice.mjs';
export function MulticlassChoices({c,update,onAbilities}){
 const [choice,setChoice]=useState(''),rows=classLevels(c);
 function add(){if(!choice)return;const next={...c,multiclass:[...(c.multiclass||[]),{className:choice,level:1,subclass:'',order:''}]};const error=multiclassIssues(next)[0];if(error){creationNotice('Check your multiclass choice',error+' You can change ability scores in Abilities.');return;}update({multiclass:next.multiclass});setChoice('');}
 return <details className="dnd-inline-library" open={rows.length>1||undefined}><summary>Multiclass (optional)</summary><p>Keep your first class, then divide your total level between classes. Check with your GM. Each class needs its primary abilities at 13 or higher.</p><p><strong>{classLabel(c)}</strong> · Total level {c.level}</p><p>First class levels: {rows[0].level}. Remaining levels stay in your first class automatically.</p>{(c.multiclass||[]).map((r,i)=><div className="dnd-toolbar" key={r.className}><label>{r.className} levels<input type="number" min="1" max={c.level-rows.length+1} value={r.level} onChange={e=>update({multiclass:c.multiclass.map((row,j)=>j===i?{...row,level:Number(e.target.value)}:row)})}/></label><button onClick={()=>update({multiclass:c.multiclass.filter((_,j)=>j!==i)})}>Remove {r.className} class</button></div>)}<label>Add another class<select value={choice} onChange={e=>setChoice(e.target.value)}><option value="">Choose a class</option>{Object.keys(classData).filter(n=>!rows.some(r=>r.className===n)).map(n=><option key={n}>{n}</option>)}</select></label>{choice&&<p>Requires {multiclassRequirements[choice].map(group=>group.map(i=>abilities[i]).join(' or ')).join(' and ')} 13 or higher.</p>}<button disabled={!choice} onClick={add}>Add class</button><button onClick={onAbilities}>Adjust abilities</button><p className="dnd-note">Only the first class grants full starting skills, saving throws, and starting equipment. Later classes grant their multiclass traits. Features and subclasses use that class’s level; Extra Attack doesn’t stack.</p></details>;
}
