import React,{useEffect,useState} from 'react';
import {RuleCard} from './dnd-reference.jsx';
import {Backpack} from './dnd-backpack.jsx';
import {CombatEditor} from './dnd-sheet.jsx';
import {weapons,armors} from './dnd-play.mjs';
import {classStarts,backgroundStarts,higherStart,startingResources,costCopper,coinText,equipmentSections,equipmentSection} from './dnd-starting.mjs';
const pdf='https://media.dndbeyond.com/compendium-images/srd/5.2/SRD_CC_v5.2.1.pdf';
function Quantity({label,value,onChange,min=0,max=1000000}){return <label>{label}<input type="number" min={min} max={max} step="1" value={value??''} onChange={e=>onChange(e.target.value===''?null:Math.max(min,Math.min(max,Math.floor(Number(e.target.value)))))}/></label>;}
export function StartingChoice({c,update}){
 const start=c.starting,mode=start?.mode,resources=startingResources(c),cls=classStarts[c.className],bg=backgroundStarts[c.background],higher=higherStart(c.level);
 const change=patch=>update({starting:{...start,...patch}});
 const clearKit=c.loadoutFromKit?{weapons:[],armor:'',shield:false,loadoutFromKit:false}:{};
 const choose=mode=>update({...clearKit,starting:mode==='gear'?{mode,kit:0}:mode==='gm'?{mode,gmGold:null}:{mode,method:'srd'}});
 return <div className="dnd-start-choice"><h3>Choose your starting path</h3><p>One path supplies your starting gear and money. Switching paths replaces its allowance; it does not stack rewards. Switching paths clears any kit-equipped loadout.</p><div className="dnd-start-options" role="radiogroup" aria-label="Starting equipment method">{[['gear','Starting gear','Your class kit + background kit'],['money','Starting money','SRD allowance or physical dice'],['gm','GM-set amount','Use your GM’s agreed budget']].map(([id,title,detail])=><label key={id} className={mode===id?'chosen':''}><input type="radio" name="starting-path" checked={mode===id} onChange={()=>choose(id)}/><span><strong>{title}</strong><small>{detail}</small></span></label>)}</div>
 {mode==='gear'&&<><h4>Your {c.className} + {c.background} kits</h4>{cls.kits.length>1&&<label>Class equipment kit<select value={start.kit||0} onChange={e=>update({...clearKit,starting:{...start,kit:Number(e.target.value)}})}>{cls.kits.map((kit,i)=><option key={i} value={i}>Kit {String.fromCharCode(65+i)} · {kit.items.map(r=>r[0]).join(', ')}</option>)}</select></label>}<div className="dnd-grid"><article><h4>{c.className} kit</h4><ul>{(cls.kits[start.kit||0]||cls.kits[0]).items.map(([name,qty])=><li key={name}>{qty} × {name}</li>)}</ul><strong>{(cls.kits[start.kit||0]||cls.kits[0]).gold} GP</strong></article><article><h4>{c.background} kit</h4><ul>{bg.items.map(([name,qty])=><li key={name}>{qty} × {name}</li>)}</ul><strong>{bg.gold} GP</strong></article></div><p>Choose the indicated instrument, tools, gaming set, or focus with your GM. Pack contents are listed under Adventuring gear.</p><button onClick={()=>{const items=resources.items.map(([name])=>name.includes('(Quarterstaff)')?'Quarterstaff':name);update({weapons:items.filter((n,i)=>weapons.some(w=>w.name===n)&&items.indexOf(n)===i).map(name=>({name,ability:'auto',proficient:true,twoHanded:false,attackBonus:0,damageBonus:0})),armor:items.find(n=>armors.some(a=>a.name===n))||'',shield:items.includes('Shield'),loadoutFromKit:true});}}>Equip this kit (replace combat loadout)</button></>}
 {mode==='money'&&<><label>Starting money rule<select value={start.method||'srd'} onChange={e=>change({method:e.target.value,rolls:[],count:4,sides:6,multiplier:10,flat:0})}><option value="srd">2024 SRD coin allowance</option><option value="higher" disabled={!higher}>SRD higher-level guide · physical d10 (GM-approved)</option><option value="custom">GM-approved physical-dice formula</option></select></label>{start.method==='srd'&&<p>{cls.gold} GP class allowance + 50 GP background allowance. These replace both kits.</p>}{start.method==='higher'&&higher&&<><p>With GM approval: {cls.gold+50} GP level-one coin alternatives + {higher.base.toLocaleString()} GP + 1d10 × {higher.multiplier} GP. This uses the SRD’s higher-level guideline; any magic-item grants are a separate GM decision.</p><Quantity label="Your physical d10 result" min={1} max={10} value={start.rolls?.[0]||null} onChange={n=>change({rolls:[n||0]})}/><a href={pdf+'#page=24'} target="_blank" rel="noopener noreferrer">Higher-level starting guide ↗</a></>}{start.method==='custom'&&<><p>Roll your real dice, then enter each result. This is a GM-approved house rule, not the revised SRD’s level-one starting rule.</p><div className="dnd-grid"><Quantity label="Number of dice" min={1} max={10} value={start.count||4} onChange={n=>change({count:n||1,rolls:[]})}/><Quantity label="Sides per die" min={2} max={20} value={start.sides||6} onChange={n=>change({sides:n||2,rolls:[]})}/><Quantity label="GP per point rolled" min={1} max={1000} value={start.multiplier||10} onChange={n=>change({multiplier:n||1})}/><Quantity label="Extra fixed GP" max={1000000} value={start.flat||0} onChange={n=>change({flat:n||0})}/></div><div className="dnd-dice-entry">{Array.from({length:start.count||4},(_,i)=><Quantity key={i} label={'Die '+(i+1)} min={1} max={start.sides||6} value={start.rolls?.[i]||null} onChange={n=>{const rolls=Array.from({length:start.count||4},(_,j)=>start.rolls?.[j]||0);rolls[i]=n||0;change({rolls});}}/>)}</div></>}</>}
 {mode==='gm'&&<Quantity label="GM-set starting amount (GP)" value={start.gmGold} onChange={gmGold=>change({gmGold})}/>}<div className="dnd-wallet"><div><small>Starting allowance</small><strong>{coinText(resources.copper)}</strong></div><div><small>Purchased equipment</small><strong>{coinText(resources.spent)}</strong></div><div><small>Money remaining</small><strong>{coinText(resources.balance)}</strong></div></div>{resources.issues.map(issue=><p role="alert" key={issue}>{issue}</p>)}<a href={pdf+'#page=20'} target="_blank" rel="noopener noreferrer">Starting equipment rules ↗</a></div>;
}
export function EquipmentLibrary({c,update}){
 const [rows,setRows]=useState(null),[error,setError]=useState(false),[retry,setRetry]=useState(0),[section,setSection]=useState('Weapons'),[search,setSearch]=useState(''),[limit,setLimit]=useState(8),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;setError(false);import('./dnd-rules-data/items.json').then(m=>{if(active)setRows(m.default);}).catch(()=>{if(active)setError(true);});return()=>{active=false;};},[retry]);
 const resources=c?startingResources(c):null,inventory=c?.inventory||[],found=(rows||[]).filter(r=>equipmentSection(r)===section&&[r.name,r.description,r.tag,...r.stats].join(' ').toLowerCase().includes(search.toLowerCase()));
 function add(row,price){const index=inventory.findIndex(r=>r.name===row.name&&r.page===row.page&&r.paidCp===price),next=[...inventory];if(index>=0)next[index]={...next[index],quantity:next[index].quantity+1};else next.push({name:row.name,page:row.page,quantity:1,paidCp:price});update({inventory:next});setNotice(row.name+' added to your backpack.');}
 return <div className="dnd-equipment-library"><div className="dnd-library-banner"><span aria-hidden="true">⚔</span><div><h2>Equipment</h2><p>Outfit your adventurer, one section at a time.</p></div></div><nav className="dnd-category-nav" aria-label="Equipment sections">{equipmentSections.map(n=><button key={n} aria-pressed={section===n} onClick={()=>{setSection(n);setSearch('');setLimit(8);}}>{n}</button>)}</nav><label>Find {section.toLowerCase()}<input type="search" value={search} onChange={e=>{setSearch(e.target.value);setLimit(8);}} placeholder="Name, property, or keyword"/></label>{resources&&<p className="dnd-equipment-budget">Available to spend: <strong>{coinText(resources.balance)}</strong></p>}{error?<p role="alert">Equipment could not load. <button onClick={()=>setRetry(n=>n+1)}>Try again</button></p>:!rows?<p role="status">Loading equipment…</p>:<><p role="status">{found.length} matches · showing {Math.min(limit,found.length)}</p><div className="dnd-grid dnd-equipment-cards">{found.slice(0,limit).map(r=>{const price=costCopper(r),buy=price!==null&&resources?.balance>=price&&c?.starting&&!resources.issues.length&&(inventory.length<200||inventory.some(i=>i.name===r.name&&i.page===r.page&&i.paidCp===price))&&!inventory.some(i=>i.name===r.name&&i.page===r.page&&i.paidCp===price&&i.quantity>=10000);return <div className="dnd-equipment-entry" key={r.name+r.page}><RuleCard {...r} name={r.name.replace(/\s*\([\d,.]+\s*[A-Z]P\)$/,'')}/>{update&&section!=='Properties'&&(price===null?<p className="dnd-note">No listed purchase price. Arrange magic-item rewards or custom grants with your GM and record them in equipment notes.</p>:<button disabled={!buy} onClick={()=>add(r,price)}>Buy for {coinText(price)}</button>)}</div>;})}</div>{!found.length&&<p>No equipment matches. Try another search.</p>}{limit<found.length&&<button onClick={()=>setLimit(n=>n+8)}>Show 8 more</button>}</>}<p role="status">{notice}</p></div>;
}
export function EquipmentBuilder({c,update}){const [area,setArea]=useState('Start');return <><nav className="dnd-category-nav" aria-label="Equipment workspace">{['Start','Browse equipment','Backpack','Combat loadout'].map(n=><button key={n} aria-pressed={area===n} onClick={()=>setArea(n)}>{n}</button>)}</nav>{area==='Start'?<StartingChoice c={c} update={update}/>:area==='Browse equipment'?<EquipmentLibrary c={c} update={update}/>:area==='Backpack'?<Backpack c={c} update={update}/>:<CombatEditor c={c} update={patch=>update({...patch,loadoutFromKit:false})}/>}</>;}
