import React from 'react';
const pdf='https://media.dndbeyond.com/compendium-images/srd/5.2/SRD_CC_v5.2.1.pdf';
export const speciesDetails={
 Dragonborn:{page:84,description:'Dragon-descended adventurers with a powerful breath weapon and elemental protection.',size:'Medium',speed:30,traits:['Darkvision: 60 ft.','Ancestry: choose acid, cold, fire, lightning, or poison resistance.','Breath weapon: 1d10 damage; 2d10 at level 5, 3d10 at 11, 4d10 at 17. Uses equal proficiency bonus per Long Rest; save DC = 8 + Constitution modifier + proficiency bonus.','Level 5: flight at your walking speed for 10 minutes, once per Long Rest.']},
 Dwarf:{page:84,description:'Sturdy adventurers with exceptional endurance, poison resistance, and a deep connection to stone.',size:'Medium',speed:30,traits:['Darkvision: 120 ft.','Toughness: +1 maximum HP per character level.','Poison damage resistance; advantage on saves against the Poisoned condition.','Stonecunning: 60-ft Tremorsense for 10 minutes while touching stone; proficiency-bonus uses per Long Rest.']},
 Elf:{page:84,description:'Keen-sensed adventurers whose elven lineage grants magic and unusual awareness.',size:'Medium',speed:30,traits:['Darkvision: 60 ft.; Drow lineage increases it to 120 ft.','Keen Senses: proficiency in Insight, Perception, or Survival.','Advantage on saves against the Charmed condition; immune to magical sleep. Trance completes a Long Rest in 4 hours.','Choose Drow, High Elf, or Wood Elf lineage for magic. Wood Elf speed: 35 ft. Additional lineage spells at levels 3 and 5.']},
 Gnome:{page:85,description:'Small adventurers with sharp minds and innate magic from their forest or rock lineage.',size:'Small',speed:30,traits:['Darkvision: 60 ft.','Gnomish Cunning: advantage on Intelligence, Wisdom, and Charisma saves.','Forest: Minor Illusion and Speak with Animals; free castings of Speak with Animals equal proficiency bonus per Long Rest.','Rock: Mending and Prestidigitation, plus up to 3 tiny magical clockwork devices lasting 8 hours.']},
 Goliath:{page:85,description:'Towering adventurers with giant ancestry, powerful builds, and a supernatural ancestral gift.',size:'Medium',speed:35,traits:['Powerful Build: count as one size larger for carrying capacity; advantage on checks to end the Grappled condition.','Choose a giant gift: teleport 30 ft., +1d10 fire damage, +1d6 cold damage and −10 ft. target speed, knock a target Prone, reduce damage by 1d12 + Constitution modifier, or retaliate for 1d8 thunder damage. Each has specific triggers; proficiency-bonus uses per Long Rest.','Level 5: become Large for 10 minutes, gaining +10 ft. speed and advantage on Strength checks; once per Long Rest.']},
 Halfling:{page:86,description:'Small, nimble adventurers whose bravery and good fortune help them through dangerous moments.',size:'Small',speed:30,traits:['Luck: reroll a natural 1 on a d20 test; use the new result.','Brave: advantage on saves against the Frightened condition.','Move through larger creatures’ spaces without stopping there.','Naturally Stealthy: Hide when obscured only by a creature at least one size larger.']},
 Human:{page:86,description:'Adaptable adventurers with a talent for learning and finding fresh inspiration.',size:'Small or Medium',speed:30,traits:['Skillful: +1 skill proficiency of your choice.','Versatile: +1 Origin feat of your choice.','Resourceful: gain Heroic Inspiration after every Long Rest.']},
 Orc:{page:86,description:'Resilient adventurers who can surge into action and keep fighting when others would fall.',size:'Medium',speed:30,traits:['Darkvision: 120 ft.','Adrenaline Rush: Bonus Action Dash grants temporary HP equal to proficiency bonus. Proficiency-bonus uses per Short or Long Rest.','Relentless Endurance: drop to 1 HP instead of 0 when not killed outright; once per Long Rest.']},
 Tiefling:{page:86,description:'Adventurers with a fiendish legacy that grants protective resistance and innate spellcasting.',size:'Small or Medium',speed:30,traits:['Darkvision: 60 ft.','Know Thaumaturgy plus a legacy cantrip.','Abyssal: poison resistance + Poison Spray. Chthonic: necrotic resistance + Chill Touch. Infernal: fire resistance + Fire Bolt.','Legacy spells at levels 3 and 5: each can be cast once without a slot per Long Rest. Choose Intelligence, Wisdom, or Charisma for species spellcasting.']}
};
export function SpeciesCard({name}){const s=speciesDetails[name];return <article className="dnd-species-card"><h3>{name}</h3><p>{s.description}</p><div className="dnd-species-stats"><span><strong>Size:</strong> {s.size}</span><span><strong>Speed:</strong> {s.speed} ft.</span></div><h4>Traits & bonuses</h4><ul>{s.traits.map(t=><li key={t}>{t}</li>)}</ul><p className="dnd-note">Ability-score bonuses come from your background in these 2024 rules, rather than your species.</p><a href={pdf+'#page='+s.page} target="_blank" rel="noopener noreferrer">Read more about {name} in the SRD ↗</a></article>;}
