import {classLevel} from './dnd-multiclass.mjs';
import {startingResources} from './dnd-starting.mjs';
import {combatStats} from './dnd-play.mjs';
export const abilities=['Strength','Dexterity','Constitution','Intelligence','Wisdom','Charisma'];
export const skillAbilities={Acrobatics:1,'Animal Handling':4,Arcana:3,Athletics:0,Deception:5,History:3,Insight:4,Intimidation:5,Investigation:3,Medicine:4,Nature:3,Perception:4,Performance:5,Persuasion:5,Religion:3,'Sleight of Hand':1,Stealth:1,Survival:4};
export const classData={
 Barbarian:{die:12,saves:[0,2],array:[15,13,14,10,12,8],page:28},Bard:{die:8,saves:[1,5],array:[8,14,12,13,10,15],page:31},Cleric:{die:8,saves:[4,5],array:[14,8,13,10,15,12],page:36},Druid:{die:8,saves:[3,4],array:[8,12,14,13,15,10],page:41},Fighter:{die:10,saves:[0,2],array:[15,14,13,8,10,12],page:47},Monk:{die:8,saves:[0,1],array:[12,15,13,10,14,8],page:49},Paladin:{die:10,saves:[4,5],array:[15,10,13,8,12,14],page:53},Ranger:{die:10,saves:[0,1],array:[12,15,13,8,14,10],page:57},Rogue:{die:8,saves:[1,3],array:[12,15,13,14,10,8],page:61},Sorcerer:{die:6,saves:[2,5],array:[10,13,14,8,12,15],page:64},Warlock:{die:8,saves:[4,5],array:[8,14,13,12,10,15],page:70},Wizard:{die:6,saves:[3,4],array:[8,12,13,15,14,10],page:77}
};
export const backgrounds={Acolyte:{abilities:[3,4,5],skills:['Insight','Religion'],feat:'Magic Initiate (Cleric)',tool:"Calligrapher’s Supplies"},Criminal:{abilities:[1,2,3],skills:['Sleight of Hand','Stealth'],feat:'Alert',tool:"Thieves’ Tools"},Sage:{abilities:[2,3,4],skills:['Arcana','History'],feat:'Magic Initiate (Wizard)',tool:"Calligrapher’s Supplies"},Soldier:{abilities:[0,1,2],skills:['Athletics','Intimidation'],feat:'Savage Attacker',tool:'Gaming Set (choose one)'}};
export const speciesNames=['Dragonborn','Dwarf','Elf','Gnome','Goliath','Halfling','Human','Orc','Tiefling'];
export const classTraining={Barbarian:'Choose 2: Animal Handling, Athletics, Intimidation, Nature, Perception, Survival.',Bard:'Choose any 3 skills. Choose 3 musical instruments.',Cleric:'Choose 2: History, Insight, Medicine, Persuasion, Religion.',Druid:'Choose 2: Animal Handling, Arcana, Insight, Medicine, Nature, Perception, Religion, Survival. Herbalism Kit.',Fighter:'Choose 2: Acrobatics, Animal Handling, Athletics, History, Insight, Intimidation, Persuasion, Perception, Survival.',Monk:'Choose 2: Acrobatics, Athletics, History, Insight, Religion, Stealth. Choose Artisan’s Tools or a Musical Instrument.',Paladin:'Choose 2: Athletics, Insight, Intimidation, Medicine, Persuasion, Religion.',Ranger:'Choose 3: Animal Handling, Athletics, Insight, Investigation, Nature, Perception, Stealth, Survival.',Rogue:'Choose 4: Acrobatics, Athletics, Deception, Insight, Intimidation, Investigation, Perception, Persuasion, Sleight of Hand, Stealth. Thieves’ Tools.',Sorcerer:'Choose 2: Arcana, Deception, Insight, Intimidation, Persuasion, Religion.',Warlock:'Choose 2: Arcana, Deception, History, Intimidation, Investigation, Nature, Religion.',Wizard:'Choose 2: Arcana, History, Insight, Investigation, Medicine, Nature, Religion.'};
export const spellAbility={Bard:5,Cleric:4,Druid:4,Paladin:5,Ranger:4,Sorcerer:5,Warlock:5,Wizard:3};
export const modifier=n=>Math.floor((n-10)/2);
export const signed=n=>n>=0?'+'+n:String(n);
export function newDndCharacter(){return {name:'',setting:'dnd5e',rules:'srd-5.2.1',className:'Fighter',species:'Human',background:'Soldier',level:1,concept:'',notes:'',scores:[15,14,13,8,10,12],method:'standard',boosts:[2,1,0,0,0,0],skills:[],expertise:[],equipment:'',spells:'',features:'',languages:'Common',ac:null,hp:null,currentHp:null,tempHp:0,speed:30,alignment:'',subclass:'',armor:'',shield:false,defense:'normal',acBonus:0,weapons:[],spellbook:[],slotsUsed:Array(9).fill(0),starting:{mode:'gear',kit:0},inventory:[]};}
export function dndStats(c){const scores=c.scores.map((v,i)=>Math.min(20,v+c.boosts[i])),mods=scores.map(modifier),pb=2+Math.floor((c.level-1)/4),cls=classData[c.className],bg=backgrounds[c.background],proficiencies=new Set([...bg.skills,...c.skills]);const result={scores,mods,pb,saves:mods.map((m,i)=>m+(cls.saves.includes(i)?pb:0)),skills:Object.fromEntries(Object.entries(skillAbilities).map(([s,a])=>[s,mods[a]+(proficiencies.has(s)?pb:classLevel(c,'Bard')>=2?Math.floor(pb/2):0)+(proficiencies.has(s)&&c.expertise.includes(s)?pb:0)])),ac:c.ac??(10+mods[1]),hp:c.hp??Math.max(1,cls.die+mods[2]+(c.species==='Dwarf'?1:0)),initiative:mods[1]+(c.background==='Criminal'?pb:0)};result.ac=combatStats(c,result).ac;return result;}
export function creationIssues(c){const issues=[];if(!c.name.trim())issues.push('Give your character a name.');if(c.method==='standard'&&[...c.scores].sort((a,b)=>a-b).join(',')!=='8,10,12,13,14,15')issues.push('Assign each standard-array score once.');if(c.method==='points'){const costs={8:0,9:1,10:2,11:3,12:4,13:5,14:7,15:9};const total=c.scores.reduce((s,v)=>s+(costs[v]??100),0);if(total!==27)issues.push('Point buy must use exactly 27 points, with scores from 8 to 15.');}const allowed=backgrounds[c.background].abilities;const boosts=c.boosts.filter(Boolean).sort().join(',');if(!['1,2','1,1,1'].includes(boosts)||c.boosts.some((n,i)=>n&&!allowed.includes(i)))issues.push('Use +2 and +1 on different background abilities, or +1 on all three.');if(c.level>1&&c.hp===null)issues.push('Enter your maximum HP for this level.');return [...issues,...startingResources(c).issues];}
