import {LanguageStudio} from './dnd-languages.jsx';
import {syncDndLanguages,chosenLanguages,knownLanguages,dndLanguageRules,dndLanguageIssues,speciesLanguages} from './dnd-languages.mjs';
import {readySpellbook} from './dnd-granted-spells.mjs';
import {spellSlotPools} from './dnd-play.mjs';
import {classLevels,classLabel} from './dnd-multiclass.mjs';
import {MulticlassChoices} from './dnd-multiclass.jsx';
import {dndChoiceError,reducesSpellChoices,dndTrainingLimit,dndSpellLimits,hasDndMagic,spellsForGrant} from './dnd-choice-limits.mjs';
import {creationNotice} from './creation-notice.mjs';
import {dndStepIssues} from './dnd-creation-flow.mjs';
import React,{useEffect,useState} from 'react';
import {useConvexAuth,useConvex,useQuery,useMutation} from 'convex/react';
import {makeFunctionReference as ref} from 'convex/server';
import {CharacterAccount} from './account.jsx';
import {CharacterSheet} from './dnd-sheet.jsx';
import {EquipmentBuilder} from './dnd-equipment.jsx';
import {TrainingStudio} from './dnd-training.jsx';
import {SpellStudio} from './dnd-spell-studio.jsx';
import {SpeciesCard,speciesDetails} from './dnd-species.jsx';
import {ClassCard,BackgroundCard,CatalogueBrowser,classDescriptions} from './dnd-reference.jsx';
import {abilities,classData,backgrounds,speciesNames,newDndCharacter,dndStats,signed,spellAbility} from './dnd-model.mjs';
import {validateDndCharacter} from './dnd-validation.mjs';
import {CreationWorkshop} from './creation-workshop.jsx';
import {CreationCharacter} from './creation-character.jsx';
import {journeyChapters,restoredJourneyStep} from './character-journey.mjs';
import {ChoiceCards} from './character-cards.jsx';
import {CharacterStory} from './character-story.jsx';
import spellIndex from './dnd-rules-data/spell-index.json';
import {startingResources,coinText} from './dnd-starting.mjs';
const pdf='https://media.dndbeyond.com/compendium-images/srd/5.2/SRD_CC_v5.2.1.pdf';
const draftKey='savage-master-dnd-draft-v1';
const chosenDefaults={species:true,class:true,background:true};
function freshDraft(){return {character:syncDndLanguages({...newDndCharacter(),boosts:Array(6).fill(0)}),id:null,selections:{},completed:[]};}
function initial(){try{const d=JSON.parse(localStorage.getItem(draftKey));validateDndCharacter(d?.character,{draft:true});return {...d,character:syncDndLanguages(d.character),id:null,selections:d.selections||chosenDefaults,completed:d.stepVersion===4&&Array.isArray(d.completed)?d.completed:[]};}catch{}return freshDraft();}
export function DndBuilder({focus}){const [draft,setDraft]=useState(initial),[step,setStep]=useState(()=>{if(new URLSearchParams(location.search).has('create'))return 0;try{const d=JSON.parse(localStorage.getItem(draftKey));return restoredJourneyStep('dnd5e',d?.step,d?.stepVersion);}catch{return 0;}}),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);const {isAuthenticated}=useConvexAuth(),convex=useConvex(),rows=useQuery(ref('characters:list'),isAuthenticated?{}:'skip'),save=useMutation(ref('characters:save'));const c=syncDndLanguages(draft.character),s=dndStats(c),bookChapters=journeyChapters('dnd5e',dndStepIssues(c),draft.selections).map(ch=>ch.id==='spells'?{...ch,skipped:!hasDndMagic(c)}:ch),issues=bookChapters.flatMap(ch=>ch.missing);
 const update=patch=>{
  const reducing=patch.skills&&patch.skills.length<c.skills.length||patch.expertise&&patch.expertise.length<c.expertise.length||patch.spellbook&&reducesSpellChoices(c.spellbook||[],patch.spellbook)||patch.boosts&&patch.boosts.reduce((a,b)=>a+b,0)<c.boosts.reduce((a,b)=>a+b,0);
  const error=reducing?null:dndChoiceError(c,patch);if(error){creationNotice('Choice limit reached',error);return false;}
  const before=spellSlotPools(c),after=spellSlotPools({...c,...patch});if(c.className==='Warlock'&&!before.regular.some(Boolean)&&after.regular.some(Boolean)&&c.pactSlotsUsed===undefined)patch={...patch,pactSlotsUsed:c.slotsUsed?.[before.pact.findIndex(Boolean)]||0,slotsUsed:Array(9).fill(0)};
  setDraft(d=>({...d,character:syncDndLanguages(d.character,patch)}));
  if(patch.languageChoices&&chosenLanguages({...c,...patch}).length>chosenLanguages(c).length&&!dndLanguageIssues({...c,...patch},{complete:true}).length)creationNotice('Language choices complete',`All ${dndLanguageRules(c).total} language choices are filled. Common, your species language, and automatic class languages are included. Edit these choices or continue.`);
  const l=dndTrainingLimit(c);
  if(patch.skills&&patch.skills.length>=l.total&&patch.skills.length>c.skills.length)creationNotice('Skill choices complete',`You have chosen all ${l.total} additional skills granted by your class, species, and selected feats. You can edit these choices or continue.`);
  if(patch.expertise&&patch.expertise.length===l.expertise&&patch.expertise.length>c.expertise.length)creationNotice('Expertise choices complete',`You have used your ${l.expertise} Expertise choices at this level.`);
  if(patch.boosts&&patch.boosts.reduce((a,b)=>a+b,0)===3&&c.boosts.reduce((a,b)=>a+b,0)<3)creationNotice('Background bonuses complete','All three background bonus points are assigned. Edit your choices or continue.');
  if(patch.spellbook){const limits=dndSpellLimits(c);for(const source of Object.keys(limits)){const cap=limits[source];for(const [label,count,match] of [['cantrips',cap.cantrips,b=>b.level===0],['prepared spells',cap.ready,b=>b.level>0&&b.prepared]]){const entries=rows=>spellsForGrant(rows,source).map(b=>({...b,level:spellIndex[b.name]?.level})).filter(match).length;if(count&&entries(patch.spellbook)===count&&entries(c.spellbook||[])<count)creationNotice('Spell choices complete',`You have filled your ${cap.label} allowance of ${count} ${label}. Other spell grants have their own limits.`,step===8&&dndStepIssues({...c,...patch})[3].length?{continueLabel:'Keep choosing spells',onContinue:()=>window.scrollTo({top:0,left:0,behavior:'instant'})}:{});}}}
  return true;
 };
 useEffect(()=>{if(focus==='equipment')setStep(9);if(focus==='spells')setStep(8);},[focus]);
 useEffect(()=>{try{localStorage.setItem(draftKey,JSON.stringify({...draft,character:c,step,stepVersion:4}));}catch{setStatus('Browser storage is full. Save to your account or download a backup.')}},[draft,step]);
 useEffect(()=>{if(!isAuthenticated)setDraft(d=>({...d,id:null}));},[isAuthenticated]);
 async function run(fn){setBusy(true);setStatus('');try{await fn();}catch{setStatus('Unable to save or load this character. Check your connection and try again.')}finally{setBusy(false)}}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,system:'dnd5e',character:c},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='5e-character.json';a.click();URL.revokeObjectURL(url);}
 const text=(key,label,max=10000)=><label>{label}<textarea maxLength={max} value={c[key]} onChange={e=>update({[key]:e.target.value})}/></label>;
 const select=(key,label,options,onChange)=><label>{label}<select value={c[key]} onChange={e=>onChange?onChange(e.target.value):update({[key]:e.target.value})}>{options.map(v=><option key={v} value={v}>{({standard:"Standard array",points:"27-point buy",physical:"Physical dice / GM scores"})[v]||v}</option>)}</select></label>;
 const number=(key,label,min,max)=><label>{label}<input type="number" min={min} max={max} value={c[key]??''} placeholder="Automatic" onChange={e=>update({[key]:e.target.value===''?null:Math.max(min,Math.min(max,Number(e.target.value)))})}/></label>;
 const cardChoice=(field,row,index,patch)=>{setDraft(d=>({...d,character:syncDndLanguages(d.character,(d.selections[field]&&row.name===d.character[({species:'species',class:'className',background:'background'})[field]]?{}:patch)),selections:{...d.selections,[field]:true},completed:[...new Set([...(d.completed||[]),index])]}));creationNotice(`${row.name} selected`,'You have made this choice. Continue to the next selection or stay here to change it.',{onContinue:()=>setStep(index+1)});};
 const tools=<><details className="dnd-account"><summary>My account & saved characters</summary><CharacterAccount accountOnly/>{isAuthenticated&&<div className="dnd-grid">{rows?.filter(r=>r.setting==='dnd5e').map(r=><button key={r._id} disabled={busy} onClick={()=>{if(confirm('Load this character and replace the current draft?'))run(async()=>{const snap=await convex.query(ref('characters:load'),{id:r._id});validateDndCharacter(snap.character,{draft:true});setDraft({character:syncDndLanguages(snap.character),id:r._id,selections:chosenDefaults,completed:[]});setStep(11);setStatus('Character loaded.');})}}>{r.name}{r._id===draft.id?' (open)':''}</button>)}{rows?.filter(r=>r.setting==='dnd5e').length===0&&<p>No saved 5e characters yet.</p>}</div>}</details>
 <div className="dnd-toolbar"><button disabled={busy||!isAuthenticated} onClick={()=>run(async()=>{if(issues.length){setStatus(issues.join(' '));return;}const id=await save({id:draft.id||undefined,snapshot:{version:1,system:'dnd5e',character:c}});setDraft(d=>({...d,id}));setStatus('5e character saved to your account.');})}>Save character</button><button onClick={()=>{if(confirm('Start a new character? Download or save your current draft first.')){setDraft(freshDraft());setStep(0);}}}>New character</button><button onClick={download}>Download backup</button><label className="dnd-import">Import backup<input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>200000)throw Error();const snap=JSON.parse(await f.text());if(snap.system!=='dnd5e'||snap.version!==1)throw Error();validateDndCharacter(snap.character,{draft:true});if(confirm('Replace the current draft with this backup?')){setDraft({character:syncDndLanguages(snap.character),id:null,selections:chosenDefaults,completed:[]});setStep(11);}}catch{setStatus('Choose a valid 5e character backup under 200 KB.');}}}/></label></div>
 <p className="dnd-note">Your draft stays in this browser. Sign in to save across devices. Revised 2024 rules · class-level character sheet. Choose your features from the SRD. Equip weapons and armor for combat totals, and add spells to your personal spell book.</p></>;
 return <div className="dnd-builder"><CreationWorkshop system="dnd5e" step={step} setStep={setStep} chapters={bookChapters} tools={tools} choiceStep={step<3&&!draft.selections[['species','class','background'][step]]} completed={draft.completed||[]} setCompleted={completed=>setDraft(d=>({...d,completed}))} summary={<CreationCharacter languages={draft.selections.species?knownLanguages(c):[]} name={c.name} concept={c.concept} identity={[draft.selections.species?c.species:'Choose a species',draft.selections.class?classLabel(c):'Choose a class',draft.selections.class?`Level ${c.level}`:''].filter(Boolean).join(' · ')} stats={draft.selections.class?[["Armor Class",s.ac],["Maximum HP",s.hp],["Speed",`${c.speed} ft`],["Initiative",signed(s.initiative)],["Proficiency",signed(s.pb)],["Shop balance",coinText(startingResources(c).balance)]]:[]} abilities={draft.selections.class?abilities.map((a,i)=>[a,`${s.scores[i]} (${signed(s.mods[i])})`]):[]} skills={draft.selections.background?[...new Set([...backgrounds[c.background].skills,...c.skills])].map(n=>[n,signed(s.skills[n])]):[]} choices={[...(draft.selections.background?[c.background,backgrounds[c.background].feat]:[]),...(c.subclass?[c.subclass]:[]),...(c.features?[c.features]:[])]} equipment={[...(c.armor?[`Equipped: ${c.armor}`]:[]),...startingResources(c).items.map(([name,n])=>`${name} ×${n}`),...(c.inventory||[]).map(r=>`${r.name} ×${r.quantity}`)]} spells={readySpellbook(c).map(r=>r.name+(r.prepared?' (prepared)':''))}/>}>

 {step===0&&<ChoiceCards system="dnd5e" type="species" rows={speciesNames.map(name=>({name}))} value={draft.selections.species?c.species:''} more onChoose={r=>cardChoice('species',r,0,{species:r.name,speed:speciesDetails[r.name].speed,speciesLineage:'',originFeat:''})} details={r=><><p>{speciesDetails[r.name].description}</p><p>Included language: {speciesLanguages[r.name]}</p><p>{speciesDetails[r.name].size} · Speed {speciesDetails[r.name].speed} ft.</p><ul>{speciesDetails[r.name].traits.slice(0,2).map(t=><li key={t}>{t}</li>)}</ul></>} greaterDetail={r=><SpeciesCard name={r.name}/>}/>}
 {step===1&&<ChoiceCards system="dnd5e" type="class" rows={Object.keys(classData).map(name=>({name}))} value={draft.selections.class?c.className:''} more onChoose={r=>cardChoice('class',r,1,{...(c.loadoutFromKit?{weapons:[],armor:'',shield:false,loadoutFromKit:false}:{}),className:r.name,multiclass:[],scores:[...classData[r.name].array],method:'standard',skills:[],expertise:[],subclass:'',order:'',defense:r.name==='Monk'?'monk':r.name==='Barbarian'?'barbarian':'normal',castingAbility:spellAbility[r.name]??4,starting:{...c.starting,kit:0}})} details={r=><><p>{classDescriptions[r.name][0]}</p><p>Primary ability: {classDescriptions[r.name][1]}</p><p>Hit Point Die: d{classData[r.name].die}</p></>} greaterDetail={r=><ClassCard name={r.name} expanded/>}/>}
 {step===2&&<ChoiceCards system="dnd5e" type="background" rows={Object.keys(backgrounds).map(name=>({name}))} value={draft.selections.background?c.background:''} onChoose={r=>{const boosts=Array(6).fill(0),a=backgrounds[r.name].abilities;boosts[a[0]]=2;boosts[a[1]]=1;cardChoice('background',r,2,{...(c.loadoutFromKit?{weapons:[],armor:'',shield:false,loadoutFromKit:false}:{}),background:r.name,boosts,expertise:[]});}} details={r=><><p>Training: {backgrounds[r.name].skills.join(' and ')}.</p><p>Origin feat: {backgrounds[r.name].feat}.</p><p>Ability bonuses: choose from {backgrounds[r.name].abilities.map(i=>abilities[i]).join(', ')}.</p></>} greaterDetail={r=><BackgroundCard name={r.name} expanded/>}/>}
 {step===3&&<><label>Starting level<input type="number" min="1" max="20" value={c.level} onChange={e=>update({level:Math.max(1,Math.min(20,Math.floor(Number(e.target.value))))})} onBlur={()=>creationNotice('Starting level selected',`Total level ${c.level}. Each class’s levels set its feature and spell choices.`)}/></label><MulticlassChoices c={c} update={update} onAbilities={()=>setStep(4)}/>{c.level>1&&number('hp','Maximum HP for this level',1,10000)}</>}

 {step===4&&<>{select('method','Ability score method',['standard','points','physical'])}<p>{c.method==='standard'?'Assign 15, 14, 13, 12, 10, and 8 once each.':c.method==='points'?'Spend 27 points. Scores 8–15 cost 0, 1, 2, 3, 4, 5, 7, and 9 points.':'Enter your real dice results or GM-approved scores. No digital dice.'}</p><div className="dnd-grid">{abilities.map((a,i)=><article key={a}><label>{a} base<input type="number" min={c.method==='physical'?3:8} max={c.method==='physical'?18:15} value={c.scores[i]} onChange={e=>{const scores=[...c.scores];const value=Math.max(c.method==='physical'?3:8,Math.min(c.method==='physical'?18:15,Math.floor(Number(e.target.value))));if(c.method==='standard'){const other=scores.findIndex((n,j)=>j!==i&&n===value);if(other<0&&value!==scores[i]){creationNotice('Use the standard array','Choose one of 15, 14, 13, 12, 10, or 8. Existing scores swap places so each is used once.');return;}if(other>=0)scores[other]=scores[i];}scores[i]=value;update({scores});}}/></label><label>{a} background increase<select disabled={!backgrounds[c.background].abilities.includes(i)} value={c.boosts[i]} onChange={e=>{const boosts=[...c.boosts];boosts[i]=Number(e.target.value);update({boosts});}}>{[0,1,2].map(n=><option key={n} value={n}>+{n}</option>)}</select></label><strong>{s.scores[i]} ({signed(s.mods[i])})</strong></article>)}</div><p>Background: {c.background}. Use +2 / +1 on two listed abilities, or +1 on all three. Scores cap at 20.</p></>}
 {step===5&&<TrainingStudio c={c} update={update}/>}
 {step===6&&<LanguageStudio c={c} update={update}/>}
 {step===7&&<>{['Elf','Gnome','Tiefling'].includes(c.species)&&<label>Species lineage<select value={c.speciesLineage||''} onChange={e=>update({speciesLineage:e.target.value})}><option value="">Choose lineage</option>{({Elf:['Drow','High Elf','Wood Elf'],Gnome:['Forest Gnome','Rock Gnome'],Tiefling:['Abyssal','Chthonic','Infernal']})[c.species].map(n=><option key={n}>{n}</option>)}</select></label>}{['Cleric','Druid'].includes(c.className)&&<label>{c.className==='Cleric'?'Divine':'Primal'} Order<select value={c.order||''} onChange={e=>update({order:e.target.value})}><option value="">Choose order</option>{(c.className==='Cleric'?['Protector','Thaumaturge']:['Warden','Magician']).map(n=><option key={n}>{n}</option>)}</select></label>}<label>{c.className} subclass / choices<input maxLength={200} value={c.subclass} onChange={e=>update({subclass:e.target.value})}/><small>Choose a subclass at {c.className} level 3.</small></label>{c.className==='Druid'&&classLevels(c)[0].level>=3&&/^(land|circle of the land)$/i.test(c.subclass.trim())&&<label>Circle of the Land terrain<select value={c.land||''} onChange={e=>update({land:e.target.value})}><option value="">Choose land</option>{['Arid','Polar','Temperate','Tropical'].map(n=><option key={n}>{n}</option>)}</select></label>}{(c.multiclass||[]).map((r,i)=><article key={r.className}><h3>{r.className} · level {r.level}</h3>{r.level>=3&&<label>{r.className} subclass / choices<input maxLength={200} value={r.subclass} onChange={e=>update({multiclass:c.multiclass.map((row,j)=>j===i?{...row,subclass:e.target.value}:row)})}/></label>}{r.className==='Druid'&&r.level>=3&&/^(land|circle of the land)$/i.test(r.subclass.trim())&&<label>Circle of the Land terrain<select value={r.land||''} onChange={e=>update({multiclass:c.multiclass.map((row,j)=>j===i?{...row,land:e.target.value}:row)})}><option value="">Choose land</option>{['Arid','Polar','Temperate','Tropical'].map(n=><option key={n}>{n}</option>)}</select></label>}{['Cleric','Druid'].includes(r.className)&&<label>{r.className} Order<select value={r.order} onChange={e=>update({multiclass:c.multiclass.map((row,j)=>j===i?{...row,order:e.target.value}:row)})}><option value="">Choose order</option>{(r.className==='Cleric'?['Protector','Thaumaturge']:['Warden','Magician']).map(n=><option key={n}>{n}</option>)}</select></label>}<details><summary>Greater Detail: {r.className} features</summary><ClassCard name={r.className} expanded/></details></article>)}{text('features','Features, feats, species traits & chosen options')}<details className="dnd-inline-library"><summary>Greater Detail: class features</summary><CatalogueBrowser category="Class features" initialSearch={c.className}/></details><details className="dnd-inline-library"><summary>Greater Detail: feats & bonuses</summary><CatalogueBrowser category="Feats" initialSearch={backgrounds[c.background].feat.split(' (')[0]}/></details></>}

 {step===9&&<><EquipmentBuilder c={c} update={update}/>{text('equipment','Equipment notes, custom grants & currency changes')}<details className="dnd-inline-library"><summary>Health, movement & defense overrides</summary><div className="dnd-grid">{number('ac','Armor Class override',1,50)}{number('hp','Maximum HP override',1,10000)}{number('currentHp','Current HP',0,10000)}{number('tempHp','Temporary HP',0,10000)}{number('speed','Speed (feet)',0,300)}</div><p className="dnd-note">Your loadout calculates AC unless overridden. Record later-level maximum HP and special defenses here.</p></details></>}
 {step===8&&<SpellStudio c={c} update={update}/>}

 {step===11&&<CharacterSheet c={c} update={update}/>}
 {step===10&&<CharacterStory system="dnd5e" c={c} update={update}/>}
 <p role="status">{busy?'Working.':status}</p></CreationWorkshop>
 </div>;
}
