import {knownLanguages} from './dnd-languages.mjs';
import {readySpellbook,alwaysPreparedGrants} from './dnd-granted-spells.mjs';
import {classLevels,classLevel,classLabel} from './dnd-multiclass.mjs';
import spellIndex from './dnd-rules-data/spell-index.json';
import {prepareSpell,spellGrants,dndSpellLimits,spellEligible,hasDndMagic} from './dnd-choice-limits.mjs';
import React,{useEffect,useState} from 'react';
import {abilities,classData,backgrounds,skillAbilities,dndStats,signed,spellAbility} from './dnd-model.mjs';
import {Backpack} from './dnd-backpack.jsx';
import {startingResources,coinText} from './dnd-starting.mjs';
import {weapons,armors,combatStats,spellSlots,spellSlotPools} from './dnd-play.mjs';
const pdf='https://media.dndbeyond.com/compendium-images/srd/5.2/SRD_CC_v5.2.1.pdf';
function Numeric({label,value,onChange,min=0,max=20}){return <label>{label}<input type="number" min={min} max={max} value={value} onChange={e=>onChange(Math.max(min,Math.min(max,Number(e.target.value))))}/></label>;}
function Metrics({rows}){return <div className="dnd-grid dnd-stat-grid">{rows.map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div>;}
export function CombatEditor({c,update}){
 const equipped=c.weapons||[];
 function edit(i,patch){update({weapons:equipped.map((w,j)=>j===i?{...w,...patch}:w)});}
 return <section className="dnd-loadout"><h3>Combat loadout</h3><p>Select what you wear and carry. Totals update when abilities, level, or equipment change.</p><div className="dnd-grid"><label>Equipped armor<select value={c.armor||''} onChange={e=>update({armor:e.target.value})}><option value="">Unarmored</option>{armors.map(a=><option key={a.name}>{a.name}</option>)}</select></label><label>Unarmored defense<select value={c.defense||'normal'} onChange={e=>update({defense:e.target.value})}><option value="normal">10 + Dexterity</option>{classLevel(c,'Monk')>0&&<option value="monk">Monk: add Wisdom (no shield)</option>}{classLevel(c,'Barbarian')>0&&<option value="barbarian">Barbarian: add Constitution</option>}</select></label><Numeric label="Other AC bonus (magic / features)" value={c.acBonus||0} min={-20} onChange={acBonus=>update({acBonus})}/></div><label className="dnd-check"><input type="checkbox" checked={!!c.shield} onChange={e=>update({shield:e.target.checked})}/>Equipped shield (+2 AC)</label><p className="dnd-note">An AC override replaces the calculated total. Confirm armor training and feature eligibility with your GM.</p>
 {equipped.map((w,i)=><article className="dnd-weapon-editor" key={i}><div className="dnd-grid"><label>Weapon {i+1}<select value={w.name} onChange={e=>edit(i,{name:e.target.value})}>{weapons.map(a=><option key={a.name}>{a.name}</option>)}</select></label><label>Attack ability<select value={w.ability} onChange={e=>edit(i,{ability:e.target.value})}><option value="auto">Automatic (Strength / Dexterity / Finesse)</option><option value="str">Strength</option><option value="dex">Dexterity</option><option value="con">Constitution (if granted)</option><option value="int">Intelligence (if granted)</option><option value="wis">Wisdom (if granted)</option><option value="cha">Charisma (if granted)</option></select></label><Numeric label="Extra attack bonus" value={w.attackBonus} min={-20} onChange={attackBonus=>edit(i,{attackBonus})}/><Numeric label="Extra damage bonus" value={w.damageBonus} min={-20} onChange={damageBonus=>edit(i,{damageBonus})}/></div><div className="dnd-toolbar"><label className="dnd-check"><input type="checkbox" checked={w.proficient} onChange={e=>edit(i,{proficient:e.target.checked})}/>Proficient</label><label className="dnd-check"><input type="checkbox" checked={w.twoHanded} onChange={e=>edit(i,{twoHanded:e.target.checked})}/>Use two hands (Versatile damage)</label><button onClick={()=>update({weapons:equipped.filter((_,j)=>j!==i)})}>Remove weapon {i+1}</button></div></article>)}<button disabled={equipped.length>=20} onClick={()=>update({weapons:[...equipped,{name:'Longsword',ability:'auto',proficient:false,twoHanded:false,attackBonus:0,damageBonus:0}]})}>Add weapon</button></section>;
}
export function SpellBook({c,update,editing=false}){
 const [catalogue,setCatalogue]=useState(null),[loadError,setLoadError]=useState(false),[retry,setRetry]=useState(0),[readyOnly,setReadyOnly]=useState(false),[query,setQuery]=useState('');
 useEffect(()=>{let active=true;setLoadError(false);import('./dnd-rules-data/spells.json').then(m=>{if(active)setCatalogue(m.default);}).catch(()=>{if(active)setLoadError(true);});return()=>{active=false;};},[retry]);
 const s=dndStats(c),limits=dndSpellLimits(c),book=readySpellbook(c),pools=spellSlotPools(c),onlyPact=!pools.regular.some(Boolean)&&pools.pact.some(Boolean),totals=c.slotTotals||spellSlots(c),used=c.slotsUsed||Array(9).fill(0),pact=onlyPact,hasCasting=Object.values(limits).some(l=>l.cantrips||l.ready);
 const pactRank=pools.pact.findIndex(Boolean),pactTotal=pools.pact[pactRank]||0,pactUsed=c.pactSlotsUsed??(onlyPact?used[pactRank]||0:0),classCasters=Object.entries(limits).filter(([,l])=>l.cantrips||l.ready).map(([source,l])=>({...l,source}));
 const known=book.map(entry=>({...entry,rule:catalogue?.find(r=>r.name===entry.name)})).filter(r=>(!readyOnly||r.prepared||spellIndex[r.name]?.level===0)&&[r.name,r.rule?.description].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>((spellIndex[a.name]?.level===0?0:spellIndex[a.name]?.level||0)-(spellIndex[b.name]?.level===0?0:spellIndex[b.name]?.level||0))||a.name.localeCompare(b.name));

 function setUsed(i,n){const next=[...used];next[i]=n;update(pact?{slotsUsed:next,pactSlotsUsed:n}:{slotsUsed:next});}
 return <section className="dnd-spellbook"><h3>{editing?'Build your spell book':'Spell Book'}</h3>{classCasters.map(l=><div key={l.source}><h4>{l.label} · {abilities[l.ability]}</h4><Metrics rows={[["Spell attack",signed(s.pb+s.mods[l.ability])],["Spell save DC",8+s.pb+s.mods[l.ability]]]}/></div>)}{!classCasters.length&&hasCasting&&<p className="dnd-note">Species and Magic Initiate spells use Intelligence, Wisdom, or Charisma, chosen for that grant. Record your choice and free casts in Spell notes.</p>}


 {(hasCasting||totals.some(Boolean))&&<><h4>{pact?'Pact Magic slots · recover on Short or Long Rest':'Spell slots · recover on Long Rest'}</h4><div className="dnd-slot-grid">{totals.map((total,i)=>total>0&&<article key={i}><h4>Level {i+1}</h4><strong>{Math.max(0,total-(pact?pactUsed:used[i]))} / {total} available</strong>{used[i]>total&&<p role="alert">Recorded uses exceed this level’s slots.</p>}<div className="dnd-toolbar"><button disabled={(pact?pactUsed:used[i])>=total} onClick={()=>setUsed(i,(pact?pactUsed:used[i])+1)}>Use level {i+1} slot</button><button disabled={!(pact?pactUsed:used[i])} onClick={()=>setUsed(i,(pact?pactUsed:used[i])-1)}>Undo level {i+1} use</button></div></article>)}</div>{totals.some(Boolean)&&<button onClick={()=>update(pact?{slotsUsed:Array(9).fill(0),pactSlotsUsed:0}:{slotsUsed:Array(9).fill(0)})}>{pact?'Restore Pact Magic slots':'Restore spell slots'}</button>}<p className="dnd-note">Track real casts with Use slot, including higher-level casting. Cantrips use no slots. Rest recovery and free casts follow your class and spell rules; high-level Warlock Mystic Arcanum is tracked separately in notes.</p></>}
 {pactTotal>0&&!onlyPact&&<div><h4>Pact Magic · recover on Short or Long Rest</h4><p>Level {pactRank+1}: {Math.max(0,pactTotal-pactUsed)} / {pactTotal} available</p><div className="dnd-toolbar"><button disabled={pactUsed>=pactTotal} onClick={()=>update({pactSlotsUsed:pactUsed+1})}>Use Pact Magic slot</button><button disabled={!pactUsed} onClick={()=>update({pactSlotsUsed:pactUsed-1})}>Undo Pact Magic use</button><button onClick={()=>update({pactSlotsUsed:0})}>Restore Pact Magic slots</button></div><p className="dnd-note">Either slot pool can cast a ready spell of an eligible level from either class. Use that spell’s class ability. Restoring one pool leaves the other unchanged.</p></div>}
 {editing&&<details className="dnd-inline-library"><summary>Adjust slot totals for special features</summary><p>Leave automatic for your class-level SRD progression. Override only for GM-approved changes.</p><div className="dnd-grid">{totals.map((n,i)=><Numeric key={i} label={'Level '+(i+1)+' total slots'} value={n} onChange={n=>{const next=[...totals];next[i]=n;update({slotTotals:next});}}/>)}</div><button onClick={()=>update({slotTotals:null,slotsUsed:Array(9).fill(0)})}>Use automatic slot totals</button></details>}
 <div className="dnd-spell-controls"><label>Search your spells<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or effect"/></label><label className="dnd-check"><input type="checkbox" checked={readyOnly} onChange={e=>setReadyOnly(e.target.checked)}/>Prepared / ready only</label></div>
 {!book.length&&<p>No spells added yet. Add spells in the Spells creation step. Existing spell notes are kept below.</p>}{book.length>0&&!known.length&&<p>No spells match this filter.</p>}{loadError&&!editing&&<p role="alert">Spell details could not load. <button onClick={()=>setRetry(n=>n+1)}>Try again</button></p>}
 <div className="dnd-grid dnd-book-cards">{known.map(entry=><article key={entry.name}><h4>{entry.name}</h4><small>{entry.rule?.tag||'Spell reference unavailable'}</small><span className="dnd-print-only">{entry.prepared?'Prepared / ready':spellIndex[entry.name]?.level===0?'Cantrip':'Not marked prepared'}</span>{Object.entries(spellGrants(entry)).map(([source,g])=><label key={source} className="dnd-check">{!source.startsWith('always:')&&(!limits[source]||!spellEligible(limits[source],entry.name))?<span>Unavailable for your current build</span>:<><input type="checkbox" checked={spellIndex[entry.name]?.level===0||g.prepared} disabled={spellIndex[entry.name]?.level===0||!limits[source]?.className&&!source.startsWith('arcanum:')} onChange={e=>update({spellbook:prepareSpell(c,entry.name,e.target.checked,source)})}/>{limits[source]?.label||alwaysPreparedGrants(c).find(g=>g.source===source)?.label||source}: {spellIndex[entry.name]?.level===0?'always ready cantrip':'prepared / ready'}</>}{editing&&!source.startsWith('always:')&&<button onClick={()=>{const spellbook=(c.spellbook||[]).flatMap(b=>{if(b.name!==entry.name)return [b];const grants={...spellGrants(b)};delete grants[source];return Object.keys(grants).length?[{...b,grants,prepared:Object.values(grants).some(g=>g.prepared)}]:[];});update({spellbook});}}>Remove this grant</button>}</label>)}{entry.rule?<details><summary>Greater Detail</summary><ul>{entry.rule.stats.map(stat=><li key={stat}>{stat}</li>)}</ul><p>{entry.rule.fullDescription||entry.rule.description}</p><a href={pdf+'#page='+entry.rule.page} target="_blank" rel="noopener noreferrer">Full SRD spell reference · page {entry.rule.page} ↗</a></details>:<p>{catalogue?'This spell needs a custom description in your notes.':'Loading spell details…'}</p>}{editing&&(c.spellbook||[]).some(b=>b.name===entry.name)&&<button onClick={()=>update({spellbook:(c.spellbook||[]).filter(b=>b.name!==entry.name)})}>Remove {entry.name}</button>}</article>)}</div>
 <h4>Concentration</h4><p className="dnd-print-only">{c.concentration||'None recorded.'}</p><label>Currently concentrating on<input maxLength={120} value={c.concentration||''} onChange={e=>update({concentration:e.target.value})} placeholder="Spell name, or none"/></label><p className="dnd-note">One concentration spell at a time. When damaged, make a Constitution save against DC 10 or half the damage (round down), whichever is higher, up to DC 30.</p><h4>Spell notes & other magic</h4><>{editing?<label>Free casts, special spell sources & other magic<textarea maxLength={10000} value={c.spells} onChange={e=>update({spells:e.target.value})}/></label>:<p className="notes">{c.spells||'No additional spell notes recorded.'}</p>}</></section>;
}
export function CharacterSheet({c,update}){
 const [playing,setPlaying]=useState(false);
 const s=dndStats(c),combat=combatStats(c,s),armor=combat.armor,required=Number(armor?.details.Strength.match(/\d+/)?.[0]||0),speed=Math.max(0,c.speed-(required>s.scores[0]?10:0));
 return <div className={'dnd-sheet'+(playing?' dnd-play-mode':'')}><div className="dnd-sheet-heading"><div><h2>{c.name||'Unnamed adventurer'}</h2><p>Level {c.level} {c.species} · {classLabel(c)} · {c.background}{c.subclass?' · '+c.subclass:''}</p></div><div className="dnd-sheet-actions"><button aria-pressed={playing} onClick={()=>setPlaying(!playing)}>{playing?'Exit Play View':'Play View'}</button><button onClick={()=>window.print()}>Print / Save PDF</button></div></div><div className="dnd-play-summary"><Metrics rows={[["Armor Class",combat.ac],["HP",`${c.currentHp??s.hp} / ${s.hp}`],["Initiative",signed(s.initiative)],["Speed",speed+' ft.'],["Passive Perception",10+s.skills.Perception]]}/><p>Roll your real dice or your VTT dice, then use the totals on this sheet. Changes stay in your browser draft; exit Play View and use Save character to keep them across devices.</p></div><nav className="dnd-sheet-nav" aria-label="Character sheet sections">{['Stats','Bio','Combat',...(hasDndMagic(c)?['Spell Book']:[])].map(n=><a key={n} href={'#sheet-'+n.replace(' ','-').toLowerCase()}>{n}</a>)}</nav>
 <section id="sheet-stats"><h3>Stats</h3><Metrics rows={[["Proficiency",signed(s.pb)],['Passive Perception',10+s.skills.Perception],['Hit Dice',classLevels(c).map(r=>r.level+'d'+classData[r.className].die).join(' + ')]]}/><div className="dnd-grid dnd-abilities">{abilities.map((a,i)=><article key={a}><h4>{a}</h4><strong>{s.scores[i]} <small>({signed(s.mods[i])})</small></strong><span>Saving throw <b>{signed(s.saves[i])}</b>{classData[c.className].saves.includes(i)?' · proficient':''}</span></article>)}</div><h4>Skills</h4><div className="dnd-skill-list">{Object.keys(skillAbilities).map(n=><span key={n}>{n}<strong>{signed(s.skills[n])}</strong></span>)}</div></section>
 <section id="sheet-bio"><h3>Bio</h3>{[['Concept & personality',c.concept],['Features & feats',backgrounds[c.background].feat+'\n'+c.features],['Languages & tools',knownLanguages(c).join(', ')+'\n'+backgrounds[c.background].tool],['Journal & memories',c.notes]].map(([n,v])=><article key={n}><h4>{n}</h4><p className="notes">{v||'None recorded yet.'}</p></article>)}</section>
 <section id="sheet-combat"><h3>Combat</h3><Metrics rows={[["Armor Class",combat.ac],['HP',`${c.currentHp??s.hp} / ${s.hp}`],['Temporary HP',c.tempHp],['Initiative',signed(s.initiative)],['Speed',speed+' ft.']]}/><div className="dnd-grid dnd-live-hp"><Numeric label="Current HP" max={10000} value={c.currentHp??s.hp} onChange={currentHp=>update({currentHp})}/><Numeric label="Temporary HP" max={10000} value={c.tempHp} onChange={tempHp=>update({tempHp})}/></div><article><h4>Armor & defenses</h4><p><strong>AC {combat.ac}</strong> · {combat.label}{c.shield?' + Shield':''}</p><p className="dnd-note">{combat.overridden?'Using your recorded AC override.':`Armor / defense ${combat.base} · Shield ${signed(combat.shield)} · Other bonuses ${signed(combat.bonus)}. Total shown above.`}</p>{armor&&<p>Stealth: {armor.details.Stealth==='Disadvantage'?'Disadvantage':'No armor penalty'} · Strength requirement: {required||'None'}</p>}{required>s.scores[0]&&<p>Armor Strength requirement unmet: speed reduced by 10 ft. above.</p>}{c.shield&&combat.attacks.some(a=>a.twoHanded||a.item.details.Properties.includes('Two-Handed'))&&<p role="alert">A two-handed attack needs both hands. Unequip your shield before using it.</p>}</article><h4>Weapons & attacks</h4>{!combat.attacks.length&&<p>No equipped weapons. Add weapons in Equipment → Combat loadout to calculate attack totals.</p>}<div className="dnd-grid">{combat.attacks.map((a,i)=><article className="dnd-attack-card" key={i}><h4>{a.name}</h4><Metrics rows={[["To hit",signed(a.attack)],['Damage',a.damage.replace(/^(\S+)/,(_,dice)=>dice+(a.damageBonus?' '+signed(a.damageBonus):''))]]}/><p>{abilities[a.ability]} · {a.proficient?'Proficient':'Not proficient'}</p><p>Properties: {a.item.details.Properties}<br/>Mastery: {a.item.details.Mastery} (only if granted)</p><a href={pdf+'#page=91'} target="_blank" rel="noopener noreferrer">Weapon rules ↗</a></article>)}</div><details className="dnd-inline-library"><summary>Backpack & remaining money · {coinText(startingResources(c).balance)}</summary><Backpack c={c} update={update}/></details><h4>Gear, currency & combat notes</h4><p className="notes">{c.equipment||'No other equipment notes recorded.'}</p><p className="dnd-note">Attack totals include the selected ability, proficiency, and recorded bonuses. Damage shows the complete dice expression; roll your physical dice. Situational effects and limited-use features remain GM/player choices.</p></section>
 {hasDndMagic(c)&&<section id="sheet-spell-book"><SpellBook c={c} update={update}/></section>}</div>;
}
