import React,{useEffect,useState} from 'react';
import {useConvexAuth,useConvex,useQuery,useMutation} from 'convex/react';
import {makeFunctionReference as ref} from 'convex/server';
import {CharacterAccount} from './account.jsx';
import {SpeciesCard} from './dnd-species.jsx';
import {ClassCard,BackgroundCard,CatalogueBrowser} from './dnd-reference.jsx';
import {abilities,skillAbilities,classData,backgrounds,speciesNames,newDndCharacter,dndStats,signed,creationIssues,classTraining,spellAbility} from './dnd-model.mjs';
import {validateDndCharacter} from './dnd-validation.mjs';
const pdf='https://media.dndbeyond.com/compendium-images/srd/5.2/SRD_CC_v5.2.1.pdf';
const draftKey='savage-master-dnd-draft-v1';
function initial(){try{const d=JSON.parse(localStorage.getItem(draftKey));validateDndCharacter(d?.character,{draft:true});return {character:d.character,id:null};}catch{}return {character:newDndCharacter(),id:null};}
export function DndBuilder(){const [draft,setDraft]=useState(initial),[step,setStep]=useState(0),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);const {isAuthenticated}=useConvexAuth(),convex=useConvex(),rows=useQuery(ref('characters:list'),isAuthenticated?{}:'skip'),save=useMutation(ref('characters:save'));const c=draft.character,s=dndStats(c),issues=creationIssues(c),steps=['Identity','Abilities','Training','Equipment & magic','Character sheet'];
 const update=patch=>setDraft(d=>({...d,character:{...d.character,...patch}}));
 useEffect(()=>{try{localStorage.setItem(draftKey,JSON.stringify(draft));}catch{setStatus('Browser storage is full. Save to your account or download a backup.')}},[draft]);
 useEffect(()=>{if(!isAuthenticated)setDraft(d=>({...d,id:null}));},[isAuthenticated]);
 async function run(fn){setBusy(true);setStatus('');try{await fn();}catch{setStatus('Unable to save or load this character. Check your connection and try again.')}finally{setBusy(false)}}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,system:'dnd5e',character:c},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='5e-character.json';a.click();URL.revokeObjectURL(url);}
 const text=(key,label,max=10000)=><label>{label}<textarea maxLength={max} value={c[key]} onChange={e=>update({[key]:e.target.value})}/></label>;
 const select=(key,label,options,onChange)=><label>{label}<select value={c[key]} onChange={e=>onChange?onChange(e.target.value):update({[key]:e.target.value})}>{options.map(v=><option key={v} value={v}>{({standard:"Standard array",points:"27-point buy",physical:"Physical dice / GM scores"})[v]||v}</option>)}</select></label>;
 const number=(key,label,min,max)=><label>{label}<input type="number" min={min} max={max} value={c[key]??''} placeholder="Automatic" onChange={e=>update({[key]:e.target.value===''?null:Math.max(min,Math.min(max,Number(e.target.value)))})}/></label>;
 return <div className="dnd-builder"><details className="dnd-account"><summary>My account & saved characters</summary><CharacterAccount accountOnly/>{isAuthenticated&&<div className="dnd-grid">{rows?.filter(r=>r.setting==='dnd5e').map(r=><button key={r._id} disabled={busy} onClick={()=>{if(confirm('Load this character and replace the current draft?'))run(async()=>{const snap=await convex.query(ref('characters:load'),{id:r._id});setDraft({character:snap.character,id:r._id});setStep(4);setStatus('Character loaded.');})}}>{r.name}{r._id===draft.id?' (open)':''}</button>)}{rows?.filter(r=>r.setting==='dnd5e').length===0&&<p>No saved 5e characters yet.</p>}</div>}</details>
 <div className="dnd-toolbar"><button disabled={busy||!isAuthenticated} onClick={()=>run(async()=>{if(issues.length){setStatus(issues.join(' '));return;}const id=await save({id:draft.id||undefined,snapshot:{version:1,system:'dnd5e',character:c}});setDraft(d=>({...d,id}));setStatus('5e character saved to your account.');})}>Save character</button><button onClick={()=>{if(confirm('Start a new character? Download or save your current draft first.')){setDraft({character:newDndCharacter(),id:null});setStep(0);}}}>New character</button><button onClick={download}>Download backup</button><label className="dnd-import">Import backup<input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>200000)throw Error();const snap=JSON.parse(await f.text());if(snap.system!=='dnd5e'||snap.version!==1)throw Error();validateDndCharacter(snap.character);if(confirm('Replace the current draft with this backup?')){setDraft({character:snap.character,id:null});setStep(4);}}catch{setStatus('Choose a valid 5e character backup under 200 KB.');}}}/></label></div>
 <p className="dnd-note">Your draft stays in this browser. Sign in to save across devices. Revised 2024 rules · single-class character sheet. Record class, species, feat, equipment, and spell choices from the SRD; these choices are not fully automated.</p>
 <nav className="dnd-tabs" aria-label="Character creation steps">{steps.map((label,i)=><button key={label} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}>{i+1}. {label}</button>)}</nav>
 <h2>{steps[step]}</h2>
 {step===0&&<><div className="dnd-grid"><label>Character name<input maxLength={120} value={c.name} onChange={e=>update({name:e.target.value})}/></label>{select('className','Class',Object.keys(classData),v=>update({className:v,scores:[...classData[v].array],method:'standard',skills:[],expertise:[]}))}{select('species','Species',speciesNames,v=>update({species:v,speed:v==='Goliath'?35:30}))}{select('background','Background',Object.keys(backgrounds),v=>{const a=backgrounds[v].abilities,boosts=[0,0,0,0,0,0];boosts[a[0]]=2;boosts[a[1]]=1;update({background:v,boosts,expertise:[]});})}<label>Level<input type="number" min="1" max="20" value={c.level} onChange={e=>update({level:Math.max(1,Math.min(20,Number(e.target.value)))})}/></label><label>Subclass / choices<input maxLength={200} value={c.subclass} onChange={e=>update({subclass:e.target.value})}/></label></div><div className="dnd-grid dnd-choice-cards"><ClassCard name={c.className}/><SpeciesCard name={c.species}/><BackgroundCard name={c.background}/></div>{text('concept','Concept & personality')}<p><a href={pdf+'#page='+classData[c.className].page} target="_blank" rel="noopener noreferrer">Read your class and level features</a> · <a href={pdf+'#page=84'} target="_blank" rel="noopener noreferrer">Species traits and choices</a></p></>}
 {step===1&&<>{select('method','Ability score method',['standard','points','physical'])}<p>{c.method==='standard'?'Assign 15, 14, 13, 12, 10, and 8 once each.':c.method==='points'?'Spend 27 points. Scores 8–15 cost 0, 1, 2, 3, 4, 5, 7, and 9 points.':'Enter your real dice results or GM-approved scores. No digital dice.'}</p><div className="dnd-grid">{abilities.map((a,i)=><article key={a}><label>{a} base<input type="number" min={c.method==='physical'?3:8} max={c.method==='physical'?18:15} value={c.scores[i]} onChange={e=>{const scores=[...c.scores];scores[i]=Math.max(c.method==='physical'?3:8,Math.min(c.method==='physical'?18:15,Number(e.target.value)));update({scores});}}/></label><label>{a} background increase<select disabled={!backgrounds[c.background].abilities.includes(i)} value={c.boosts[i]} onChange={e=>{const boosts=[...c.boosts];boosts[i]=Number(e.target.value);update({boosts});}}>{[0,1,2].map(n=><option key={n} value={n}>+{n}</option>)}</select></label><strong>{s.scores[i]} ({signed(s.mods[i])})</strong></article>)}</div><p>Background: {c.background}. Use +2 / +1 on two listed abilities, or +1 on all three. Scores cap at 20.</p></>}
 {step===2&&<><p>{c.background} gives {backgrounds[c.background].skills.join(' and ')}, {backgrounds[c.background].tool}, and {backgrounds[c.background].feat}.</p><p><strong>{c.className} training:</strong> {classTraining[c.className]}</p><p>Choose additional skills and expertise permitted by your class, species, and feats. Check your <a href={pdf+'#page='+classData[c.className].page} target="_blank" rel="noopener noreferrer">class rules</a> for allowed choices and counts.</p><div className="dnd-grid">{Object.keys(skillAbilities).map(name=>{const fromBg=backgrounds[c.background].skills.includes(name),trained=fromBg||c.skills.includes(name);return <article key={name}><label className="dnd-check"><input type="checkbox" checked={trained} disabled={fromBg} onChange={e=>update({skills:e.target.checked?[...c.skills,name]:c.skills.filter(v=>v!==name),expertise:c.expertise.filter(v=>v!==name)})}/>{name} {signed(s.skills[name])}{fromBg?' · background':''}</label><label className="dnd-check"><input type="checkbox" disabled={!trained} checked={trained&&c.expertise.includes(name)} onChange={e=>update({expertise:e.target.checked?[...c.expertise,name]:c.expertise.filter(v=>v!==name)})}/>Expertise (if granted)</label></article>;})}</div><label>Languages<input maxLength={1000} value={c.languages} onChange={e=>update({languages:e.target.value})}/></label>{text('features','Features, feats, species traits & chosen options')}<details className="dnd-inline-library"><summary>Read class features</summary><CatalogueBrowser category="Class features" initialSearch={c.className}/></details><details className="dnd-inline-library"><summary>Read feats & bonuses</summary><CatalogueBrowser category="Feats" initialSearch={backgrounds[c.background].feat.split(' (')[0]}/></details></>}
 {step===3&&<><p><a href={pdf+'#page=89'} target="_blank" rel="noopener noreferrer">Equipment rules</a> · <a href={pdf+'#page=104'} target="_blank" rel="noopener noreferrer">Spell rules</a>. Add your starting equipment or spending, attacks, prepared spells, slots, and limited-use abilities.</p>{text('equipment','Equipment, weapons, attacks & currency')}{text('spells','Cantrips, spells & spell slots')}<details className="dnd-inline-library"><summary>Browse spell descriptions</summary><CatalogueBrowser category="Spells"/></details><details className="dnd-inline-library"><summary>Browse items & gear</summary><CatalogueBrowser category="Items"/></details><div className="dnd-grid">{number('ac','Armor Class override',1,50)}{number('hp','Maximum HP override',1,10000)}{number('currentHp','Current HP',0,10000)}{number('tempHp','Temporary HP',0,10000)}{number('speed','Speed (feet)',0,300)}</div><p className="dnd-note">Automatic AC is 10 + Dexterity for an unarmored character. Automatic HP is level-one class HP plus Constitution and Dwarf bonus. Enter overrides for armor, class defenses, feats, and later levels.</p></>}
 {step===4&&<div className="dnd-sheet"><h2>{c.name||'Unnamed adventurer'}</h2><p>Level {c.level} {c.species} {c.className} · {c.background}{c.subclass?' · '+c.subclass:''}</p><div className="dnd-grid dnd-stat-grid">{[['AC',s.ac],['HP',`${c.currentHp??s.hp} / ${s.hp}`],['Temporary HP',c.tempHp],['Initiative',signed(s.initiative)],['Speed',c.speed+' ft'],['Proficiency',signed(s.pb)],['Passive Perception',10+s.skills.Perception],...(Object.hasOwn(spellAbility,c.className)?[['Class spell DC',8+s.pb+s.mods[spellAbility[c.className]]],['Class spell attack',signed(s.pb+s.mods[spellAbility[c.className]])]]:[])].map(([n,v])=><article key={n}><small>{n}</small><strong>{v}</strong></article>)}</div><div className="dnd-grid">{abilities.map((a,i)=><article key={a}><h3>{a}</h3><strong>{s.scores[i]} ({signed(s.mods[i])})</strong><span>Save {signed(s.saves[i])}{classData[c.className].saves.includes(i)?' · proficient':''}</span></article>)}</div><h3>Skills</h3><div className="dnd-skill-list">{Object.keys(skillAbilities).map(n=><span key={n}>{n} <strong>{signed(s.skills[n])}</strong></span>)}</div>{[['Concept',c.concept],['Features & feats',backgrounds[c.background].feat+'\n'+c.features],['Languages & tools',c.languages+'\n'+backgrounds[c.background].tool],['Equipment & attacks',c.equipment],['Magic',c.spells],['Journal & notes',c.notes]].map(([n,v])=><article key={n}><h3>{n}</h3><p className="notes">{v||'None recorded yet.'}</p></article>)}<button onClick={()=>window.print()}>Print character sheet</button></div>}
 {step!==4&&text('notes','Character journal & notes',30000)}
 {issues.length>0&&<aside className="dnd-issues"><strong>Before saving</strong><ul>{issues.map(i=><li key={i}>{i}</li>)}</ul></aside>}
 <div className="dnd-toolbar"><button disabled={step===0} onClick={()=>setStep(step-1)}>Back</button><button disabled={step===4} onClick={()=>setStep(step+1)}>Next: {steps[Math.min(4,step+1)]}</button></div><p role="status">{busy?'Working…':status}</p>
 </div>;
}
