import React,{useEffect,useState} from 'react';
import {useConvexAuth,useConvex,useQuery,useMutation} from 'convex/react';
import {makeFunctionReference as ref} from 'convex/server';
import {CharacterAccount} from './account.jsx';
import {CharacterSheet} from './dnd-sheet.jsx';
import {EquipmentBuilder} from './dnd-equipment.jsx';
import {SpellStudio} from './dnd-spell-studio.jsx';
import {SpeciesCard} from './dnd-species.jsx';
import {ClassCard,BackgroundCard,CatalogueBrowser} from './dnd-reference.jsx';
import {abilities,skillAbilities,classData,backgrounds,speciesNames,newDndCharacter,dndStats,signed,creationIssues,classTraining,spellAbility} from './dnd-model.mjs';
import {validateDndCharacter} from './dnd-validation.mjs';
const pdf='https://media.dndbeyond.com/compendium-images/srd/5.2/SRD_CC_v5.2.1.pdf';
const draftKey='savage-master-dnd-draft-v1';
function initial(){try{const d=JSON.parse(localStorage.getItem(draftKey));validateDndCharacter(d?.character,{draft:true});return {character:d.character,id:null};}catch{}return {character:newDndCharacter(),id:null};}
export function DndBuilder({focus}){const [draft,setDraft]=useState(initial),[step,setStep]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem(draftKey)),n=saved?.step;return Number.isInteger(n)&&n>=0&&n<=5?(saved?.stepVersion!==2&&n===4?5:n):0;}catch{return 0;}}),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);const {isAuthenticated}=useConvexAuth(),convex=useConvex(),rows=useQuery(ref('characters:list'),isAuthenticated?{}:'skip'),save=useMutation(ref('characters:save'));const c=draft.character,s=dndStats(c),issues=creationIssues(c),steps=['Identity','Abilities','Training','Equipment','Spells','Character sheet'];
 const update=patch=>setDraft(d=>({...d,character:{...d.character,...patch}}));
 useEffect(()=>{if(focus==='equipment')setStep(3);if(focus==='spells')setStep(4);},[focus]);
 useEffect(()=>{try{localStorage.setItem(draftKey,JSON.stringify({...draft,step,stepVersion:2}));}catch{setStatus('Browser storage is full. Save to your account or download a backup.')}},[draft,step]);
 useEffect(()=>{if(!isAuthenticated)setDraft(d=>({...d,id:null}));},[isAuthenticated]);
 async function run(fn){setBusy(true);setStatus('');try{await fn();}catch{setStatus('Unable to save or load this character. Check your connection and try again.')}finally{setBusy(false)}}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,system:'dnd5e',character:c},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='5e-character.json';a.click();URL.revokeObjectURL(url);}
 const text=(key,label,max=10000)=><label>{label}<textarea maxLength={max} value={c[key]} onChange={e=>update({[key]:e.target.value})}/></label>;
 const select=(key,label,options,onChange)=><label>{label}<select value={c[key]} onChange={e=>onChange?onChange(e.target.value):update({[key]:e.target.value})}>{options.map(v=><option key={v} value={v}>{({standard:"Standard array",points:"27-point buy",physical:"Physical dice / GM scores"})[v]||v}</option>)}</select></label>;
 const number=(key,label,min,max)=><label>{label}<input type="number" min={min} max={max} value={c[key]??''} placeholder="Automatic" onChange={e=>update({[key]:e.target.value===''?null:Math.max(min,Math.min(max,Number(e.target.value)))})}/></label>;
 return <div className="dnd-builder"><details className="dnd-account"><summary>My account & saved characters</summary><CharacterAccount accountOnly/>{isAuthenticated&&<div className="dnd-grid">{rows?.filter(r=>r.setting==='dnd5e').map(r=><button key={r._id} disabled={busy} onClick={()=>{if(confirm('Load this character and replace the current draft?'))run(async()=>{const snap=await convex.query(ref('characters:load'),{id:r._id});setDraft({character:snap.character,id:r._id});setStep(5);setStatus('Character loaded.');})}}>{r.name}{r._id===draft.id?' (open)':''}</button>)}{rows?.filter(r=>r.setting==='dnd5e').length===0&&<p>No saved 5e characters yet.</p>}</div>}</details>
 <div className="dnd-toolbar"><button disabled={busy||!isAuthenticated} onClick={()=>run(async()=>{if(issues.length){setStatus(issues.join(' '));return;}const id=await save({id:draft.id||undefined,snapshot:{version:1,system:'dnd5e',character:c}});setDraft(d=>({...d,id}));setStatus('5e character saved to your account.');})}>Save character</button><button onClick={()=>{if(confirm('Start a new character? Download or save your current draft first.')){setDraft({character:newDndCharacter(),id:null});setStep(0);}}}>New character</button><button onClick={download}>Download backup</button><label className="dnd-import">Import backup<input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>200000)throw Error();const snap=JSON.parse(await f.text());if(snap.system!=='dnd5e'||snap.version!==1)throw Error();validateDndCharacter(snap.character);if(confirm('Replace the current draft with this backup?')){setDraft({character:snap.character,id:null});setStep(5);}}catch{setStatus('Choose a valid 5e character backup under 200 KB.');}}}/></label></div>
 <p className="dnd-note">Your draft stays in this browser. Sign in to save across devices. Revised 2024 rules · single-class character sheet. Choose your features from the SRD. Equip weapons and armor for combat totals, and add spells to your personal spell book.</p>
 <nav className="dnd-tabs" aria-label="Character creation steps">{steps.map((label,i)=><button key={label} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}>{i+1}. {label}</button>)}</nav>
 <h2>{steps[step]}</h2>
 {step===0&&<><div className="dnd-grid"><label>Character name<input maxLength={120} value={c.name} onChange={e=>update({name:e.target.value})}/></label>{select('className','Class',Object.keys(classData),v=>update({...(c.loadoutFromKit?{weapons:[],armor:'',shield:false,loadoutFromKit:false}:{}),className:v,scores:[...classData[v].array],method:'standard',skills:[],expertise:[],defense:v==='Monk'?'monk':v==='Barbarian'?'barbarian':'normal',castingAbility:spellAbility[v]??4,...(c.starting?{starting:{...c.starting,kit:0}}:{})}))}{select('species','Species',speciesNames,v=>update({species:v,speed:v==='Goliath'?35:30}))}{select('background','Background',Object.keys(backgrounds),v=>{const a=backgrounds[v].abilities,boosts=[0,0,0,0,0,0];boosts[a[0]]=2;boosts[a[1]]=1;update({...(c.loadoutFromKit?{weapons:[],armor:'',shield:false,loadoutFromKit:false}:{}),background:v,boosts,expertise:[]});})}<label>Level<input type="number" min="1" max="20" value={c.level} onChange={e=>update({level:Math.max(1,Math.min(20,Number(e.target.value)))})}/></label><label>Subclass / choices<input maxLength={200} value={c.subclass} onChange={e=>update({subclass:e.target.value})}/></label></div><div className="dnd-grid dnd-choice-cards"><ClassCard name={c.className}/><SpeciesCard name={c.species}/><BackgroundCard name={c.background}/></div>{text('concept','Concept & personality')}<p><a href={pdf+'#page='+classData[c.className].page} target="_blank" rel="noopener noreferrer">Read your class and level features</a> · <a href={pdf+'#page=84'} target="_blank" rel="noopener noreferrer">Species traits and choices</a></p></>}
 {step===1&&<>{select('method','Ability score method',['standard','points','physical'])}<p>{c.method==='standard'?'Assign 15, 14, 13, 12, 10, and 8 once each.':c.method==='points'?'Spend 27 points. Scores 8–15 cost 0, 1, 2, 3, 4, 5, 7, and 9 points.':'Enter your real dice results or GM-approved scores. No digital dice.'}</p><div className="dnd-grid">{abilities.map((a,i)=><article key={a}><label>{a} base<input type="number" min={c.method==='physical'?3:8} max={c.method==='physical'?18:15} value={c.scores[i]} onChange={e=>{const scores=[...c.scores];scores[i]=Math.max(c.method==='physical'?3:8,Math.min(c.method==='physical'?18:15,Number(e.target.value)));update({scores});}}/></label><label>{a} background increase<select disabled={!backgrounds[c.background].abilities.includes(i)} value={c.boosts[i]} onChange={e=>{const boosts=[...c.boosts];boosts[i]=Number(e.target.value);update({boosts});}}>{[0,1,2].map(n=><option key={n} value={n}>+{n}</option>)}</select></label><strong>{s.scores[i]} ({signed(s.mods[i])})</strong></article>)}</div><p>Background: {c.background}. Use +2 / +1 on two listed abilities, or +1 on all three. Scores cap at 20.</p></>}
 {step===2&&<><p>{c.background} gives {backgrounds[c.background].skills.join(' and ')}, {backgrounds[c.background].tool}, and {backgrounds[c.background].feat}.</p><p><strong>{c.className} training:</strong> {classTraining[c.className]}</p><p>Choose additional skills and expertise permitted by your class, species, and feats. Check your <a href={pdf+'#page='+classData[c.className].page} target="_blank" rel="noopener noreferrer">class rules</a> for allowed choices and counts.</p><div className="dnd-grid">{Object.keys(skillAbilities).map(name=>{const fromBg=backgrounds[c.background].skills.includes(name),trained=fromBg||c.skills.includes(name);return <article key={name}><label className="dnd-check"><input type="checkbox" checked={trained} disabled={fromBg} onChange={e=>update({skills:e.target.checked?[...c.skills,name]:c.skills.filter(v=>v!==name),expertise:c.expertise.filter(v=>v!==name)})}/>{name} {signed(s.skills[name])}{fromBg?' · background':''}</label><label className="dnd-check"><input type="checkbox" disabled={!trained} checked={trained&&c.expertise.includes(name)} onChange={e=>update({expertise:e.target.checked?[...c.expertise,name]:c.expertise.filter(v=>v!==name)})}/>Expertise (if granted)</label></article>;})}</div><label>Languages<input maxLength={1000} value={c.languages} onChange={e=>update({languages:e.target.value})}/></label>{text('features','Features, feats, species traits & chosen options')}<details className="dnd-inline-library"><summary>Read class features</summary><CatalogueBrowser category="Class features" initialSearch={c.className}/></details><details className="dnd-inline-library"><summary>Read feats & bonuses</summary><CatalogueBrowser category="Feats" initialSearch={backgrounds[c.background].feat.split(' (')[0]}/></details></>}
 {step===3&&<><EquipmentBuilder c={c} update={update}/>{text('equipment','Equipment notes, custom grants & currency changes')}<details className="dnd-inline-library"><summary>Health, movement & defense overrides</summary><div className="dnd-grid">{number('ac','Armor Class override',1,50)}{number('hp','Maximum HP override',1,10000)}{number('currentHp','Current HP',0,10000)}{number('tempHp','Temporary HP',0,10000)}{number('speed','Speed (feet)',0,300)}</div><p className="dnd-note">Your loadout calculates AC unless overridden. Record later-level maximum HP and special defenses here.</p></details></>}
 {step===4&&<SpellStudio c={c} update={update}/>}

 {step===5&&<CharacterSheet c={c} update={update}/>}
 {step!==5&&text('notes','Character journal & notes',30000)}
 {issues.length>0&&<aside className="dnd-issues"><strong>Before saving</strong><ul>{issues.map(i=><li key={i}>{i}</li>)}</ul></aside>}
 <div className="dnd-toolbar"><button disabled={step===0} onClick={()=>setStep(step-1)}>Back</button><button disabled={step===5} onClick={()=>setStep(step+1)}>Next: {steps[Math.min(5,step+1)]}</button></div><p role="status">{busy?'Working…':status}</p>
 </div>;
}
