import {alwaysPreparedGrants} from './dnd-granted-spells.mjs';
import {dndSpellLimits,spellEligible,spellsForGrant,spellGrants,grantSpell,prepareSpell} from './dnd-choice-limits.mjs';
import React,{useEffect,useState} from 'react';
import {classData,spellAbility,abilities} from './dnd-model.mjs';
import {spellLevel,spellSchool,spellUse,spellMatches} from './dnd-spells.mjs';
import {SpellBook} from './dnd-sheet.jsx';
const pdf='https://media.dndbeyond.com/compendium-images/srd/5.2/SRD_CC_v5.2.1.pdf';
export function SpellLibrary({c,update}){
 const [rows,setRows]=useState(null),[error,setError]=useState(false),[retry,setRetry]=useState(0),[search,setSearch]=useState(''),[classFilter,setClassFilter]=useState('All'),[level,setLevel]=useState('all'),[school,setSchool]=useState('All'),[use,setUse]=useState('All'),[ritual,setRitual]=useState(false),[concentration,setConcentration]=useState(false),[other,setOther]=useState(false),[limit,setLimit]=useState(8),[notice,setNotice]=useState(''),[grantChoice,setGrant]=useState('class');
 useEffect(()=>{let active=true;setError(false);import('./dnd-rules-data/spells.json').then(m=>{if(active)setRows(m.default);}).catch(()=>{if(active)setError(true);});return()=>{active=false;};},[retry]);
 const limits=c?dndSpellLimits(c):null,grants=Object.entries(limits||{}).filter(([,l])=>l.cantrips||l.ready),grant=grants.some(([key])=>key===grantChoice)?grantChoice:grants[0]?.[0]||'class',active=limits?.[grant],book=c?.spellbook||[],source=active?.list,maxLevel=c?active?.maxLevel||0:9,effectiveClass=c?source:classFilter,effectiveMax=maxLevel;
 const cantrips=spellsForGrant(book,grant).filter(b=>rows?.some(r=>r.name===b.name&&spellLevel(r)===0)).length,prepared=spellsForGrant(book,grant).filter(b=>b.prepared&&rows?.some(r=>r.name===b.name&&spellLevel(r)>0)).length;
 const selectableLevels=c?[...(active?.cantrips?[0]:[]),...(active?.ready?Array.from({length:Math.max(0,effectiveMax-(active.minLevel||1)+1)},(_,i)=>i+(active.minLevel||1)):[])]:Array.from({length:10},(_,i)=>i);
 const fixed=c?alwaysPreparedGrants(c).find(g=>g.className===active?.className)?.names||[]:[];
 const found=(rows||[]).filter(r=>spellMatches(r,{search,className:c?active?.names||active?.lists?'All':active?.list||'No spells':effectiveClass,level,maxLevel:c?active?.maxLevel:effectiveMax,school,use,ritual,concentration})&&(!c||spellEligible(active,r.name))&&!fixed.includes(r.name));
 useEffect(()=>setLimit(8),[search,classFilter,level,school,use,ritual,concentration,other,grant,c?.className,c?.level]);
 function add(row){if(update({spellbook:grantSpell(c,row.name,grant)})===false)return;setNotice(row.name+' selected for '+active.label+'.');}
 return <div className="dnd-spell-library"><div className="dnd-library-banner dnd-magic-banner"><span aria-hidden="true">✦</span><div><h2>{c?'Discover your magic':'Spell library'}</h2><p>{c?'Choose the magic you want at your fingertips.':'Explore the open spells by class, level, school, and purpose.'}</p></div></div>{c&&<><label>Choose spells for<select value={grant} onChange={e=>{setGrant(e.target.value);setLevel('all');setSearch('');}}>{grants.map(([key,l])=><option key={key} value={key}>{l.label}</option>)}</select></label>{active.abilityChoice&&<label>Spellcasting ability for this grant<select value={active.ability} onChange={e=>update({grantAbilities:{...c.grantAbilities,[grant]:Number(e.target.value)}})}>{[3,4,5].map(i=><option key={i} value={i}>{abilities[i]}</option>)}</select><small>Choose the ability you use when casting these granted spells.</small></label>}<div className="dnd-spell-guide"><div><small>Cantrips</small><strong>{cantrips} / {active.cantrips}</strong></div><div><small>Ready spells</small><strong>{prepared} / {active.ready}</strong></div>{active.bookMinimum>0&&<div><small>Wizard book (at least)</small><strong>{spellsForGrant(book,grant).filter(b=>rows?.some(r=>r.name===b.name&&spellLevel(r)>0)).length} / {active.bookMinimum}</strong></div>}</div>{grant.startsWith('arcanum:')&&<p className="dnd-note">Choose one spell of this exact level. Cast it once per Long Rest without using a spell slot; record its use in Spell notes.</p>}<p>Choose from {active.names?'your granted species spells':`${(active.lists||[active.list]).join(', ')} spells through level ${active.maxLevel}`}. {active.bookMinimum?'Add spells to your book, then mark the ones you want ready.':'Add a spell, then mark it ready to cast.'} Cantrips are always ready.</p>{fixed.length>0&&<details className="dnd-inline-library"><summary>Already ready from class features ({fixed.length})</summary><p>{fixed.join(', ')}.</p><p>Included automatically in My spell book. These don’t use your choice allowance.</p></details>}{grants.filter(([,l])=>l.className&&l.ready).length>1&&<p className="dnd-note">Choose each class’s spells separately. Shared slots can cast your ready spells at higher levels; they don’t unlock higher-level spell choices.</p>}</>}<div className="dnd-spell-search"><label>Find a spell<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try fire, healing, invisibility…"/></label><label>Spell level<select value={level} onChange={e=>setLevel(e.target.value)}><option value="all">{c&&!other?'Available levels':'All levels'}</option>{selectableLevels.map(n=><option key={n} value={n}>{n===0?'Cantrips · no spell slots':'Level '+n}</option>)}</select></label></div>
 <details className="dnd-inline-library"><summary>More spell filters & granted magic</summary><label>School<select value={school} onChange={e=>setSchool(e.target.value)}>{['All','Abjuration','Conjuration','Divination','Enchantment','Evocation','Illusion','Necromancy','Transmutation'].map(n=><option key={n}>{n}</option>)}</select></label>
 {c?<><p className="dnd-note">{source&&!other?`Showing ${source} spells through level ${maxLevel}.`:'Spells from another source must be granted by a feature or your GM.'} Adding to your book does not automatically grant the spell or expend a slot.</p><p>Each spell grant has a separate allowance. Choose your lineage and Origin feat before selecting their spells.</p></>:<p className="dnd-note">Add spells to your character in Create character → Spells.</p>}
 {(!c||other)&&<label>Spell class<select value={classFilter} onChange={e=>setClassFilter(e.target.value)}>{['All',...Object.keys(spellAbility)].map(n=><option key={n}>{n}</option>)}</select></label>}
 <nav className="dnd-category-nav dnd-spell-uses" aria-label="Browse spells by use">{['All','Damage','Healing','Protection','Control','Utility','Summoning'].map(n=><button aria-pressed={use===n} key={n} onClick={()=>setUse(n)}>{n==='All'?'All magic':n}</button>)}</nav><div className="dnd-spell-filters"><label className="dnd-check"><input type="checkbox" checked={ritual} onChange={e=>setRitual(e.target.checked)}/>Ritual spells</label><label className="dnd-check"><input type="checkbox" checked={concentration} onChange={e=>setConcentration(e.target.checked)}/>Concentration spells</label><button onClick={()=>{setSearch('');setLevel('all');setSchool('All');setUse('All');setRitual(false);setConcentration(false);setClassFilter('All');}}>Clear filters</button></div>
</details>
 {c&&<details className="dnd-inline-library"><summary>How many spells can I choose?</summary><p>Your class defines how many cantrips and spells you learn or prepare. A Wizard begins with six level-one spells in their book and adds at least two whenever they gain a Wizard level. They can copy more spells through play. Their prepared list is separate from the spells in their book. Granted spells and free casts may use different limits. Mark your ready spells in My spell book, and record special sources in your notes.</p><a href={pdf+'#page='+(classData[active?.className||active?.list||c.className]?.page||8)} target="_blank" rel="noopener noreferrer">Read {active?.className||active?.list||c.className} spellcasting & preparation rules ↗</a><p><a href="https://www.dndbeyond.com/sources/dnd/br-2024/creating-a-character#Multiclassing" target="_blank" rel="noopener noreferrer">Greater Detail: multiclass spell rules</a></p></details>}
 {error?<p role="alert">Spells could not load. <button onClick={()=>setRetry(n=>n+1)}>Try again</button></p>:!rows?<p role="status">Opening the spell library…</p>:<><p role="status">{found.length} {found.length===1?'spell':'spells'} found · showing {Math.min(limit,found.length)}</p>{!found.length&&<p>No spells match. Clear the filters{c?' or browse other granted spells':''}.</p>}<div className="dnd-grid dnd-spell-choice-cards">{found.slice(0,limit).map(r=>{const owned=book.find(b=>b.name===r.name),lvl=spellLevel(r),icon={'Damage':'✹','Healing':'✚','Protection':'◇','Control':'⌁','Utility':'✦','Summoning':'◈'}[spellUse(r)];return <article key={r.name} className={owned?'in-book':''}><div className="dnd-spell-card-title"><span aria-hidden="true">{icon}</span><div><h3>{r.name}</h3><small>{lvl===0?'Cantrip':'Level '+lvl} · {spellSchool(r)} · {spellUse(r)}</small></div></div><dl className="dnd-casting-details">{r.stats.map(stat=>{const i=stat.indexOf(':');return <div key={stat}><dt>{stat.slice(0,i)}</dt><dd>{stat.slice(i+1).trim()}</dd></div>;})}</dl><p>{r.description.length>280?r.description.slice(0,280).replace(/\s+\S*$/,'')+'…':r.description}</p><details className="dnd-spell-effect"><summary>Greater Detail</summary><p>{r.fullDescription||r.description}</p><a href={pdf+'#page='+r.page} target="_blank" rel="noopener noreferrer">Official SRD · page {r.page} ↗</a></details>{update&&<div className="dnd-spell-pick-actions">{owned&&Object.hasOwn(spellGrants(owned),grant)?<><span className="dnd-in-book">✓ In your spell book</span><label className="dnd-check"><input type="checkbox" disabled={lvl===0} checked={lvl===0||spellGrants(owned)[grant]?.prepared||false} onChange={e=>update({spellbook:prepareSpell(c,r.name,e.target.checked,grant)})}/>Prepared / ready</label></>:<button disabled={book.length>=339} onClick={()=>add(r)}>Add to spell book</button>}</div>}</article>;})}</div>{limit<found.length&&<button onClick={()=>setLimit(n=>n+8)}>Discover 8 more spells</button>}</>}<p role="status">{notice}</p></div>;
}
export function SpellStudio({c,update}){const [area,setArea]=useState('Choose spells');if(!Object.values(dndSpellLimits(c)).some(l=>l.cantrips||l.ready)&&(c.spellbook||[]).length)return <><p role="alert">Your current build doesn’t grant these saved spells. Remove the old choices below, or return to Starting level and Features to add the class or spell grant that allows them.</p><button onClick={()=>update({spellbook:[]})}>Remove old spell choices</button><SpellBook c={c} update={update} editing/></>;if(!Object.values(dndSpellLimits(c)).some(l=>l.cantrips||l.ready)&&!(c.spellbook||[]).length)return <div><h3>No spells required</h3><p>Your {c.className} can continue without spellcasting. Use the guide below if a species, feat, or feature grants magic.</p><details className="dnd-inline-library"><summary>Add magic granted by a feature</summary><SpellLibrary c={c} update={update}/></details></div>;return <><nav className="dnd-category-nav" aria-label="Spell workspace">{['Choose spells','My spell book'].map(n=><button key={n} aria-pressed={area===n} onClick={()=>setArea(n)}>{n}{n==='My spell book'?' ('+(c.spellbook||[]).length+')':''}</button>)}</nav>{area==='Choose spells'?<SpellLibrary c={c} update={update}/>:<SpellBook c={c} update={update} editing/>}</>;}
