import React from 'react';
import {dndLanguages,dndLanguageRules,chosenLanguages,dndLanguageIssues} from './dnd-languages.mjs';

export function LanguageStudio({c,update}){
 const rules=dndLanguageRules(c),choices=chosenLanguages(c),unknown=choices.filter(n=>!dndLanguages.some(r=>r.name===n));
 const cards=kind=><div className="dnd-training-cards">{dndLanguages.filter(r=>r.kind===kind&&!rules.included.some(a=>a.name===r.name)).map(r=>{
  const selected=choices.includes(r.name),next=selected?choices.filter(n=>n!==r.name):[...choices,r.name];
  return <article key={r.name} className={selected?'trained':''}><h3>{r.name}</h3><label className="dnd-check"><input type="checkbox" aria-label={`${r.name} language`} checked={selected} disabled={!selected&&dndLanguageIssues({...c,languageChoices:next}).length>0} onChange={()=>update({languageChoices:next})}/>{selected?'My choice':'Choose language'}</label><details><summary>Greater Detail</summary><p>{r.description}</p><p>Knowing a language lets you communicate, read, and write in it. Ask your GM how it fits your setting.</p></details></article>;
 })}</div>;
 return <div className="dnd-training dnd-languages"><h3>Already included</h3><ul>{rules.included.map(r=><li key={r.name}><strong>{r.name}</strong> — {r.reason}</li>)}</ul><p>Your species language is included in this workshop's three starting languages. Choose {rules.starting} more standard language{rules.starting===1?'':'s'}.</p>{rules.bonus>0&&<p>{rules.bonuses.map(r=>`${r.label}: ${r.count} extra`).join(' · ')}. These extra choices may be standard or rare languages.</p>}<p role="status"><strong>{choices.length} / {rules.total} language choices</strong> · Included languages do not use extra class choices.</p>{unknown.length>0&&<aside className="dnd-note"><p>These imported languages need review. Remove them here and record GM-approved custom languages in Features & choices.</p>{unknown.map(n=><button key={n} onClick={()=>update({languageChoices:choices.filter(v=>v!==n)})}>Remove {n}</button>)}</aside>}<h3>Standard languages</h3>{cards('standard')}<details className="dnd-inline-library"><summary>Greater Detail: rare languages{rules.bonus?' & class choices':''}</summary><p>{rules.bonus?'Your class grants let you choose from this list.':'A class or other feature must grant a rare language. Custom grants can be recorded with your GM in Features & choices.'}</p>{cards('rare')}</details><details className="dnd-inline-library"><summary>Greater Detail: language rules</summary><p>Revised 2024 rules normally let you choose both languages alongside Common. This workshop assigns the species language to one of those choices, as your table's creation rule. Check with your GM when joining another table.</p><a href="https://www.dndbeyond.com/sources/dnd/br-2024/creating-a-character#ChooseLanguages" target="_blank" rel="noopener noreferrer">Read the D&D language tables</a></details></div>;
}
