import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './campaigns.css';
import './dnd.css';
const pdf='https://media.dndbeyond.com/compendium-images/srd/5.2/SRD_CC_v5.2.1.pdf';
const classes=[['Barbarian','Path of the Berserker',28],['Bard','College of Lore',31],['Cleric','Life Domain',36],['Druid','Circle of the Land',41],['Fighter','Champion',47],['Monk','Warrior of the Open Hand',49],['Paladin','Oath of Devotion',53],['Ranger','Hunter',57],['Rogue','Thief',61],['Sorcerer','Draconic Sorcery',64],['Warlock','Fiend Patron',70],['Wizard','Evoker',77]];
const species=[['Dragonborn',84],['Dwarf',84],['Elf',84],['Gnome',85],['Goliath',85],['Halfling',86],['Human',86],['Orc',86],['Tiefling',86]];
const rules=[['Create a character',19,'Follow the SRD character-creation sequence.'],['Abilities & d20 tests',5,'Read how ability scores, checks, and saving throws work.'],['Combat',13,'Find turns, movement, attacks, and damage.'],['Equipment',89,'Look up weapons, armor, tools, and adventuring gear.'],['Spells',104,'Check spellcasting rules and SRD spell descriptions.'],['Feats',87,'Review the feats included in the open rules.'],['Rules glossary',176,'Find definitions during play.'],['Monsters',254,'Open stat-block guidance and SRD creatures.']];
function Reference({name,page,children}){return <article><h3>{name}</h3>{children}<a href={pdf+'#page='+page} target="_blank" rel="noopener noreferrer">Open SRD · page {page} ↗</a></article>}
function App(){const [tab,setTab]=useState('start'),[search,setSearch]=useState('');const tabs=[['start','Start here'],['classes','Classes'],['species','Species'],['backgrounds','Backgrounds'],['rules','Rules library']];const matches=n=>n.toLowerCase().includes(search.toLowerCase());return <main>
 <nav className="game-switch" aria-label="Game system"><a href="/">Savage Worlds</a><a href="/dnd" aria-current="page">Dungeons &amp; Dragons 5e</a></nav>
 <nav className="workspace-nav" aria-label="Workspace"><a href="/dnd" aria-current="page">5e Rules</a><a href="/campaigns">Campaigns</a><a href="/profile">My Profile</a></nav>
 <header className="workspace-hero"><div><span className="art-eyebrow">Fifth-edition adventures</span><h1>Dungeons &amp; Dragons 5e</h1><p>Explore the open rules. Bring your adventure to the same table.</p><small>SRD 5.2.1 · Revised fifth edition (2024 rules)</small></div><img className="workspace-art" src="/images/art/hero-kit.webp" alt="" width="720" height="480"/></header>
 <section><div className="dnd-tabs" role="tablist" aria-label="5e rules sections">{tabs.map(([id,label])=><button role="tab" id={'tab-'+id} aria-selected={tab===id} aria-controls={'panel-'+id} key={id} onClick={()=>{setTab(id);setSearch('')}}>{label}</button>)}</div>
 <div role="tabpanel" id={'panel-'+tab} aria-labelledby={'tab-'+tab}>
 {tab==='start'?<><h2>Your 5e table starts here</h2><p>This section is a rules reference. Use the SRD to build your character, then use Campaigns and My Profile for your stories. The Savage Worlds character builder remains under its own game tab.</p><div className="dnd-grid"><Reference name="Build your first character" page={19}><p>Start with the official open character-creation guide.</p></Reference><article><h3>Keep the adventure together</h3><p>Prepare scenes and keep private notes in your campaign workspace.</p><a href="/campaigns">Open Campaigns →</a></article><article><h3>Make a gaming home</h3><p>Add the games you play, your favorite memories, and your own artwork.</p><a href="/profile">Open My Profile →</a></article></div><p className="dnd-note">A dedicated 5e character builder and 5e account sheets are not available yet. This page does not change your existing characters.</p></>:<>
 <label>Find {tabs.find(t=>t[0]===tab)[1].toLowerCase()}<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Type a name…"/></label>
 <div className="dnd-grid">{tab==='classes'&&classes.filter(c=>matches(c[0])||matches(c[1])).map(([name,sub,page])=><Reference key={name} name={name} page={page}><p>Included SRD subclass: {sub}</p></Reference>)}{tab==='species'&&species.filter(s=>matches(s[0])).map(([name,page])=><Reference key={name} name={name} page={page}/>)}{tab==='backgrounds'&&['Acolyte','Criminal','Sage','Soldier'].filter(matches).map(name=><Reference key={name} name={name} page={83}/>)}{tab==='rules'&&rules.filter(r=>matches(r[0])).map(([name,page,summary])=><Reference key={name} name={name} page={page}><p>{summary}</p></Reference>)}</div>
 {((tab==='classes'?classes.filter(c=>matches(c[0])||matches(c[1])):tab==='species'?species.filter(s=>matches(s[0])):tab==='backgrounds'?['Acolyte','Criminal','Sage','Soldier'].filter(matches):rules.filter(r=>matches(r[0]))).length===0)&&<p>No matches. Try another name.</p>}
 </>}
 </div></section>
 <section className="dnd-license"><h2>Open rules & attribution</h2><p>This work includes material from the System Reference Document 5.2.1 (“SRD 5.2.1”) by Wizards of the Coast LLC, available at <a href="https://www.dndbeyond.com/srd" target="_blank" rel="noopener noreferrer">https://www.dndbeyond.com/srd</a>. The SRD 5.2.1 is licensed under the Creative Commons Attribution 4.0 International License, available at <a href="https://creativecommons.org/licenses/by/4.0/legalcode" target="_blank" rel="noopener noreferrer">https://creativecommons.org/licenses/by/4.0/legalcode</a>.</p><p>Catalogue organization and interface text are adapted for this site. Independent tool compatible with fifth edition; not an official D&amp;D product. Artwork is original Savage Master artwork.</p><p><a href={pdf} target="_blank" rel="noopener noreferrer">Download the official SRD 5.2.1</a> · <a href="https://www.dndbeyond.com/creator-faq" target="_blank" rel="noopener noreferrer">Creator FAQ</a> · <a href="https://media.dndbeyond.com/compendium-images/srd/5.1/SRD_CC_v5.1.pdf" target="_blank" rel="noopener noreferrer">Older 2014 SRD 5.1</a></p></section>
 </main>}
createRoot(document.getElementById('dndRoot')).render(<App/>);
