import React,{useState,useRef,useEffect} from 'react';
import {useConvexAuth,useQuery,useMutation} from 'convex/react';
import {makeFunctionReference as ref} from 'convex/server';
import {friendlyError,useDraftWarning} from './community-ui.jsx';
export function Guilds(){
  const {isAuthenticated}=useConvexAuth(),eligible=useQuery(ref('chronicles:eligibility')),rows=useQuery(ref('guilds:list'));
  const [selected,setSelected]=useState(null),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
  const create=useMutation(ref('guilds:create'));
  useEffect(()=>{if(!isAuthenticated){setSelected(null);setCreating(false);}},[isAuthenticated]);
  return <section className="chron-panel guilds"><span className="chron-eyebrow">Your people, your adventures</span><h2>Guilds</h2><p>Gather at least four reviewed profiles with verified emails. Your Guild opens once four people accept. Public Guilds share their directory page and events; all chat stays with members.</p>{eligible?<button type="button" onClick={()=>setCreating(!creating)}>Found a Guild</button>:<p><a href={isAuthenticated?'/settings#review':'/profile?entry=signIn'}>Sign in with a reviewed profile</a> to found or join a Guild.</p>}
    {creating&&<form onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);try{const id=await create({name:String(form.get('name')),description:String(form.get('description')),visibility:String(form.get('visibility')),founders:String(form.get('founders')).split(/[\s,]+/).map(s=>s.replace(/^@/,'').toLowerCase()).filter(Boolean)});setSelected(id);setCreating(false);setStatus('Invitations sent. Your Guild opens after four people accept.');}catch(error){setStatus(friendlyError(error));}finally{setBusy(false);}}}><label>Guild name<input name="name" required maxLength={70}/></label><label>What brings you together?<textarea name="description" maxLength={400}/></label><label>Directory visibility<select name="visibility"><option value="public">Public — discoverable with public events</option><option value="private">Private — invitation only</option></select></label><label>Invite at least three other profile handles<textarea name="founders" required placeholder="ember, iron-oracle, table-hero" maxLength={300}/></label><button disabled={busy}>Send founding invitations</button><button type="button" className="quiet" onClick={()=>setCreating(false)}>Cancel</button></form>}
    {status&&<p role="status">{status}</p>}{rows===undefined?<p>Opening Guilds…</p>:!rows.length?<p>No Guilds are open yet. Bring your table together.</p>:<div className="community-list-grid">{rows.map(g=><article key={g._id}><span className="chron-eyebrow">{g.visibility} · {g.active?'Open':`Forming · ${g.memberCount}/4 accepted`}</span><h3>{g.name}</h3><p>{g.description}</p><button type="button" className="quiet" onClick={()=>setSelected(g._id)}>{g.invited?'Your invitation':g.joined?'Open my Guild':'Visit Guild'}</button></article>)}</div>}
    {selected&&<GuildDetail key={selected} id={selected} onClose={()=>setSelected(null)}/>}
  </section>;
}
function GuildDetail({id,onClose}){
  const {isAuthenticated}=useConvexAuth(),guild=useQuery(ref('guilds:detail'),{id}),chat=useQuery(ref('guilds:chat'),{id}),events=useQuery(ref('guilds:events'),{id});
  const respond=useMutation(ref('guilds:respond')),invite=useMutation(ref('guilds:invite')),configure=useMutation(ref('guilds:configure')),send=useMutation(ref('guilds:send')),share=useMutation(ref('guilds:share')),schedule=useMutation(ref('guilds:schedule')),rsvp=useMutation(ref('guilds:rsvp')),cancelEvent=useMutation(ref('guilds:cancelEvent'));
  const [body,setBody]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[sharing,setSharing]=useState(null),[closing,setClosing]=useState(false),[settings,setSettings]=useState(false),[eventForm,setEventForm]=useState(false);
  const request=useRef(crypto.randomUUID()),bottom=useRef(null),lastMessage=useRef(null);
  useDraftWarning(!!body);
  useEffect(()=>{if(!chat?.length)return;const newest=chat[chat.length-1]._id;if(newest!==lastMessage.current){lastMessage.current=newest;const scroller=bottom.current?.parentElement;if(scroller)scroller.scrollTop=scroller.scrollHeight;}},[chat]);
  async function run(fn,message){setBusy(true);setStatus('');try{await fn();setStatus(message);}catch(e){setStatus(friendlyError(e));}finally{setBusy(false);}}
  if(guild===undefined)return <p>Opening your Guild…</p>;
  if(!guild)return <p>This Guild is private, closed, or unavailable. <button type="button" className="quiet" onClick={onClose}>Back to Guilds</button></p>;
  return <section className="guild-detail"><button type="button" className="quiet" onClick={onClose}>Back to Guilds</button><h2>{guild.name}</h2><p>{guild.description}</p><p>{guild.visibility==='private'?'Private Guild':'Public directory and events'} · {guild.memberCount} accepted profiles · {guild.active?'Open':'Waiting for four founding members'}</p>
    {!guild.mine&&isAuthenticated&&<div className="chron-actions"><button disabled={busy} onClick={()=>run(()=>respond({id,accept:!guild.joined}),guild.joined?'You left the Guild.':'You joined the Guild.')}>{guild.joined?'Leave Guild':guild.invited?'Accept invitation':'Join Guild'}</button>{guild.invited&&<button className="quiet" disabled={busy} onClick={()=>run(()=>respond({id,accept:false}),'Invitation declined.')}>Decline invitation</button>}</div>}
    {guild.mine&&<button type="button" className="quiet" onClick={()=>setSettings(!settings)}>Guild settings & invitations</button>}
    {settings&&guild.mine&&<div><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);run(()=>invite({id,handle:String(form.get('handle')).replace(/^@/,'')}),'Invitation sent.');e.currentTarget.reset();}}><label>Invite profile handle<input name="handle" required maxLength={30}/></label><button disabled={busy}>Invite member</button></form><label>Directory visibility<select value={guild.visibility} disabled={busy} onChange={e=>run(()=>configure({id,visibility:e.target.value,close:false}),'Guild visibility updated. Chat remains members-only.')}><option value="public">Public</option><option value="private">Private</option></select></label><button type="button" className="quiet" onClick={()=>setClosing(!closing)}>Close Guild</button>{closing&&<div><p>Close this Guild and hide its directory, chat, and events?</p><button disabled={busy} onClick={()=>run(async()=>{await configure({id,visibility:guild.visibility,close:true});onClose();},'Guild closed.')}>Confirm close</button><button type="button" className="quiet" onClick={()=>setClosing(false)}>Cancel</button></div>}</div>}
    {guild.joined&&<><h3>Members</h3><ul className="guild-members">{guild.members.map(m=><li key={m.handle}><a href={'/profile?user='+encodeURIComponent(m.handle)}>{m.name}</a>{m.invited?' · Invited':''}</li>)}</ul><h3>Members' fire</h3><p>Chat stays inside the Guild. Share only your own chosen messages to Around the Fire.</p><div className="guild-chat" aria-label="Guild messages">{!chat?.length?<p>No messages yet.</p>:chat.map(m=><article key={m._id}><a href={'/profile?user='+encodeURIComponent(m.author.handle)}>{m.author.name}</a> <time>{new Date(m.createdAt).toLocaleString()}</time><p>{m.body}</p>{m.mine&&guild.active&&<button type="button" className="quiet" onClick={()=>setSharing(m)}>Share to Around the Fire</button>}</article>)}<div ref={bottom}/></div>{guild.active?<form onSubmit={e=>{e.preventDefault();run(async()=>{await send({id,body,requestId:request.current});setBody('');request.current=crypto.randomUUID();},'Message sent.');}}><label>Message your Guild<textarea required maxLength={2000} value={body} onChange={e=>{setBody(e.target.value);request.current=crypto.randomUUID();}}/></label><button disabled={busy||!body.trim()}>Send to Guild</button></form>:<p>Chat and scheduling unlock after four reviewed profiles accept.</p>}</>}
    {sharing&&<form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);run(async()=>{await share({id:sharing._id,title:String(form.get('title')),consent:form.has('consent')});setSharing(null);},'Your selected message is now public around the fire.');}}><h3>Share this message publicly</h3><blockquote>{sharing.body}</blockquote><label>Public story title<input name="title" required maxLength={100}/></label><label className="check"><input type="checkbox" name="consent" required/>Publish this message where everyone can see and share it.</label><button disabled={busy}>Publish around the fire</button><button type="button" className="quiet" onClick={()=>setSharing(null)}>Cancel</button></form>}
    <h3>Upcoming gatherings</h3>{guild.joined&&guild.active&&<button type="button" className="quiet" onClick={()=>setEventForm(!eventForm)}>Schedule an event</button>}
    {eventForm&&<form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);run(async()=>{await schedule({id,title:String(form.get('title')),description:String(form.get('description')),startsAt:new Date(String(form.get('start'))).getTime(),endsAt:new Date(String(form.get('end'))).getTime(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});setEventForm(false);},'Your event is on the Guild calendar.');}}><label>Event title<input name="title" required maxLength={100}/></label><label>Details<textarea name="description" maxLength={1000}/></label><label>Starts (your local time)<input name="start" type="datetime-local" required/></label><label>Ends (your local time)<input name="end" type="datetime-local" required/></label><button disabled={busy}>Schedule gathering</button></form>}
    {!events?.length?<p>No upcoming events.</p>:events.map(event=><article className="guild-event" key={event._id}><h4>{event.title}</h4><p>{new Date(event.startsAt).toLocaleString()} – {new Date(event.endsAt).toLocaleTimeString()} ({Intl.DateTimeFormat().resolvedOptions().timeZone})</p><p>{event.description}</p><small>{event.going} going · {event.maybe} maybe</small>{guild.joined&&guild.active&&<div className="chron-actions">{['going','maybe','clear'].map(choice=><button key={choice} className="quiet" type="button" disabled={busy} aria-pressed={event.response===choice} onClick={()=>run(()=>rsvp({id:event._id,choice}),'Event response saved.')}>{choice==='clear'?'Clear response':choice==='going'?'Going':'Maybe'}</button>)}{(event.mine||guild.mine)&&<button className="quiet" disabled={busy} onClick={()=>run(()=>cancelEvent({id:event._id}),'Event cancelled.')}>Cancel event</button>}</div>}</article>)}
    {status&&<p role="status">{status}</p>}
  </section>;
}
