import React,{useEffect,useRef,useState} from 'react';
import {atlasFor,mapBadgePoint,validateAtlas,validateMapParents,routeSummary,printLayout,printPapers} from './map-atlas.mjs';
import {downloadMap,downloadBlob,downloadMapKey,printMap} from './map-export.mjs';
import {worldSections} from './builder-model.mjs';
import './map-atlas.css';

const types=['Town','City','Landmark','Building','NPC','Faction','Creature','God','Lore','Other'];
const clone=x=>JSON.parse(JSON.stringify(x));
function Text({label,value,onChange,max=10000,area=false}){return <label>{label}{area?<textarea maxLength={max} value={value} onChange={e=>onChange(e.target.value)}/>:<input maxLength={max} value={value} onChange={e=>onChange(e.target.value)}/>}</label>;}
export function MapAtlasEditor({map,maps,world,onSave,onClose,onBusy,readOnly=false}){
  const [atlas,setAtlas]=useState(()=>clone(atlasFor(map))),[baseline,setBaseline]=useState(()=>JSON.stringify(atlasFor(map))),[selected,setSelected]=useState(''),[mode,setMode]=useState('inspect'),[points,setPoints]=useState([]),[calibration,setCalibration]=useState([]),[scaleDistance,setScaleDistance]=useState(''),[scaleUnit,setScaleUnit]=useState('miles'),[pathName,setPathName]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('gm'),[zoom,setZoom]=useState(1),[size,setSize]=useState({width:1000,height:1000}),[print,setPrint]=useState({paper:'letter',orientation:'landscape',mode:'fit',width:20}),[printAudience,setPrintAudience]=useState('player');
  const dialog=useRef(null),dirty=JSON.stringify(atlas)!==baseline,aspect=size.width/size.height,h=1000/aspect,marker=atlas.markers.find(m=>m.id===selected),route=atlas.routes.find(r=>r.id===selected);
  const layer=id=>atlas.layers.find(l=>l.id===id),visible=item=>layer(item.layerId)?.visible&&(view==='gm'||item.public&&layer(item.layerId)?.public),shownMarkers=atlas.markers.filter(visible),shownRoutes=atlas.routes.filter(visible),otherMaps=maps.filter(m=>atlasFor(m).id!==atlas.id);
  useEffect(()=>{dialog.current.showModal();return ()=>dialog.current?.close();},[]);
  function change(patch){setAtlas(a=>({...a,...patch}));setStatus('');}
  function selectItem(id){if(points.length||calibration.length){setStatus('Finish or cancel the current path or measurement first.');return;}setSelected(id);setMode('inspect');}
  function patchMarker(patch){change({markers:atlas.markers.map(m=>m.id===selected?{...m,...patch}:m)});}
  function patchRoute(patch){change({routes:atlas.routes.map(r=>r.id===selected?{...r,...patch}:r)});}
  function close(){if(busy)return;if((dirty||points.length||calibration.length)&&!confirm('Close this map and discard unsaved annotation changes? Use Save annotations to keep them.'))return;onClose();}
  async function run(fn){setBusy(true);onBusy?.(true);setStatus('');try{const message=await fn();if(message)setStatus(message);}catch(e){setStatus(e.message?.includes('[CONVEX')?'Could not save map annotations. Check your connection and try again.':e.message||'Could not complete this map action.');}finally{setBusy(false);onBusy?.(false);}}
  function addMarker(point={x:.5,y:.5}){if(atlas.markers.length>=200){setStatus('This map has reached its 200-location limit.');return;}const m={id:crypto.randomUUID(),...point,name:`Location ${atlas.markers.length+1}`,type:'Landmark',layerId:atlas.layers[0].id,public:false,notes:'',gmNotes:'',targetMapId:'',worldField:''};change({markers:[...atlas.markers,m]});setSelected(m.id);setView('gm');}
  function mapClick(e){if(readOnly||busy)return;const box=e.currentTarget.getBoundingClientRect(),point={x:Math.max(0,Math.min(1,(e.clientX-box.left)/box.width)),y:Math.max(0,Math.min(1,(e.clientY-box.top)/box.height))};if(mode==='marker')addMarker(point);if(['route','border'].includes(mode)){if(points.length>=100){setStatus('A path can have up to 100 points.');return;}setPoints(p=>[...p,point]);}if(mode==='scale')setCalibration(p=>p.length===2?[point]:[...p,point]);}
  function finishPath(){const min=mode==='border'?3:2;if(points.length<min){setStatus(`Place at least ${min} points on the map first.`);return;}if(atlas.routes.length>=100){setStatus('This map has reached its 100-path limit.');return;}const r={id:crypto.randomUUID(),name:pathName.trim()||`${mode==='border'?'Border':'Route'} ${atlas.routes.length+1}`,kind:mode==='border'?'border':'travel',layerId:atlas.layers.find(l=>l.id===(mode==='border'?'politics':'travel'))?.id||atlas.layers[0].id,public:false,points,factor:1,override:''};change({routes:[...atlas.routes,r]});setSelected(r.id);setPoints([]);setPathName('');setMode('inspect');setView('gm');}
  function applyScale(){if(calibration.length!==2||!Number.isFinite(Number(scaleDistance))||Number(scaleDistance)<=0||!scaleUnit.trim()){setStatus('Choose two distinct points, a positive distance, and a unit.');return;}const next={...atlas,scale:{a:calibration[0],b:calibration[1],distance:Number(scaleDistance),unit:scaleUnit}};try{validateAtlas(next);change({scale:next.scale});setCalibration([]);setMode('inspect');}catch(e){setStatus(e.message);}}
  function openMap(target){if(dirty||points.length||calibration.length){setStatus('Save annotations before opening another map.');return;}const linked=maps.find(m=>atlasFor(m).id===target);if(linked)onClose(linked);else setStatus('That connected map is not available in this library.');}
  const fieldOptions=[...worldSections.map(([key,label])=>({value:'section:'+key,label,valueText:world?.[key]||''})),...(world?.customFields||[]).map(f=>({value:'custom:'+f.id,label:f.label||'Custom field',valueText:f.value}))],worldRecord=fieldOptions.find(f=>f.value===marker?.worldField);
  let layout;try{layout=printLayout({...print,aspect});}catch{}
  const save=()=>run(async()=>{if(points.length||calibration.length)throw new Error('Finish or cancel your path or scale measurement before saving.');validateAtlas(atlas);validateMapParents(atlas.id,atlas,maps);await onSave(atlas);setBaseline(JSON.stringify(atlas));return 'Map annotations saved.';});
  return <dialog ref={dialog} className="map-dialog atlas-dialog" onCancel={e=>{e.preventDefault();close();}}><div className="atlas-header"><div><small>World atlas</small><h2>{map.name}</h2></div><div className="atlas-header-actions">{!readOnly&&<button type="button" disabled={busy||!dirty} onClick={save}>Save annotations</button>}<button type="button" className="secondary" disabled={busy} onClick={close}>Close map</button></div></div>
    <p className="atlas-status" role="status" aria-live="polite">{status||(!readOnly&&dirty?'You have unsaved annotation changes.':'')}</p>
    <fieldset className="atlas-controls" disabled={busy}><legend className="sr-only">Map tools</legend><div className="atlas-toolbar"><label>Map view<select value={view} onChange={e=>setView(e.target.value)}><option value="gm">GM reference</option><option value="player">Player preview</option></select></label><label>Zoom<select value={zoom} onChange={e=>setZoom(Number(e.target.value))}>{[1,1.5,2,3].map(z=><option key={z} value={z}>{Math.round(z*100)}%</option>)}</select></label>{!readOnly&&<label>Editing tool<select value={mode} onChange={e=>{if(points.length||calibration.length){setStatus('Finish or cancel the current path or measurement first.');return;}setMode(e.target.value);setSelected('');}}><option value="inspect">Inspect locations</option><option value="marker">Place locations</option><option value="route">Draw travel route</option><option value="border">Draw border / region</option><option value="scale">Calibrate distance</option></select></label>}{atlas.parentMapId&&<button type="button" className="secondary" onClick={()=>openMap(atlas.parentMapId)}>Open parent map</button>}</div>
      <div className="atlas-layout"><div className="atlas-main"><p className="builder-caption">{mode==='inspect'?'Select a numbered location or a path to read its details.':mode==='marker'?'Click the map to place a location, or add one at the center and edit its coordinates.':mode==='scale'?'Click two points whose real-world distance you know.':'Click to add points. Finish the path when you are done.'}</p>{view==='player'&&<p className="atlas-notice">This preview hides private annotations. It cannot erase secrets in the original artwork.</p>}
        <div className="atlas-scroll"><img className="atlas-source" src={map.url} alt="" onLoad={e=>setSize({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight})}/><svg className={'atlas-canvas tool-'+mode} style={{width:`${zoom*100}%`}} viewBox={`0 0 1000 ${h}`} role="img" aria-label={'Map canvas for '+map.name} onClick={mapClick}><image href={map.url} width="1000" height={h}/>{shownRoutes.map(r=>{const props={points:r.points.map(p=>`${p.x*1000},${p.y*h}`).join(' '),fill:r.kind==='border'?(layer(r.layerId)?.color+'22'):'none',stroke:layer(r.layerId)?.color,strokeWidth:selected===r.id?5:3,strokeDasharray:r.kind==='border'?'10 7':undefined,onClick:e=>{e.stopPropagation();selectItem(r.id);},className:'atlas-path'};return r.kind==='border'?<polygon key={r.id} {...props}><title>{r.name}</title></polygon>:<polyline key={r.id} {...props}><title>{r.name}</title></polyline>;})}{shownMarkers.map((m,i)=>{const radius=Math.max(selected===m.id?15:12,String(i+1).length*4.5),position=mapBadgePoint(m,1000,h,radius+1);return <g key={m.id} transform={`translate(${position.x},${position.y})`} onClick={e=>{e.stopPropagation();selectItem(m.id);}} className="atlas-pin"><title>{m.name}{m.public?'':' (GM only)'}</title><circle r={radius} fill={layer(m.layerId)?.color} stroke="white" strokeWidth="2"/><text textAnchor="middle" dominantBaseline="central" fontSize="13" fill="#141c20" fontWeight="bold">{i+1}</text></g>;})}{points.length>0&&<polyline points={points.map(p=>`${p.x*1000},${p.y*h}`).join(' ')} fill="none" stroke="#fff" strokeWidth="3" strokeDasharray="7 5"/>}{calibration.map((p,i)=><g key={i}><circle cx={p.x*1000} cy={p.y*h} r="8" fill="#fff" stroke="#111" strokeWidth="2"/><text x={p.x*1000+12} y={p.y*h} fill="#fff" stroke="#111" paintOrder="stroke">{i===0?'A':'B'}</text></g>)}</svg></div>
        {!readOnly&&mode==='marker'&&<button type="button" className="secondary" onClick={()=>addMarker()}>Add location at center</button>}
        {!readOnly&&['route','border'].includes(mode)&&<div className="atlas-action-panel"><Text label="Path name" value={pathName} onChange={setPathName} max={160}/><p>{points.length} points placed</p><button type="button" onClick={finishPath}>Finish {mode==='border'?'border':'route'}</button><button type="button" className="secondary" onClick={()=>setPoints(p=>p.slice(0,-1))} disabled={!points.length}>Undo last point</button><button type="button" className="secondary" onClick={()=>{setPoints([]);setMode('inspect');}}>Cancel path</button></div>}
        {!readOnly&&mode==='scale'&&<div className="atlas-action-panel"><p>{calibration.length}/2 scale points selected.</p><div className="builder-grid"><label>Distance between A and B<input type="number" min="0.001" max="1000000000000" step="any" value={scaleDistance} onChange={e=>setScaleDistance(e.target.value)}/></label><Text label="Distance unit" value={scaleUnit} max={40} onChange={setScaleUnit}/></div><button type="button" onClick={applyScale}>Apply map scale</button><button type="button" className="secondary" onClick={()=>{setCalibration([{x:0,y:.5},{x:1,y:.5}]);setStatus('A and B are now at the left and right map edges. Enter the distance across the full map.');}}>Use full map width</button><button type="button" className="secondary" onClick={()=>{setCalibration([]);setMode('inspect');}}>Cancel measurement</button></div>}
        <details className="atlas-key" open><summary>Locations &amp; paths</summary>{shownMarkers.map((m,i)=><button type="button" key={m.id} className={'atlas-list-item'+(selected===m.id?' selected':'')} onClick={()=>{selectItem(m.id);}}><strong>{i+1}. {m.name}</strong><small>{m.type} · {m.public&&layer(m.layerId)?.public?'Player-visible':'GM only'}</small></button>)}{shownRoutes.map(r=><button type="button" className={'atlas-list-item'+(selected===r.id?' selected':'')} key={r.id} onClick={()=>{selectItem(r.id);}}><strong>{r.name}</strong><small>{r.kind==='border'?'Border / region':view==='player'?'Travel route':routeSummary(r,atlas,aspect)}</small></button>)}{!shownMarkers.length&&!shownRoutes.length&&<p>No annotations in this view yet.</p>}</details>
      </div><aside className="atlas-inspector">
        {marker&&visible(marker)&&<fieldset disabled={readOnly}><legend>Location details</legend><Text label="Location name" value={marker.name} onChange={name=>patchMarker({name})} max={160}/><div className="builder-grid"><label>Location type<select value={types.includes(marker.type)?marker.type:'Other'} onChange={e=>patchMarker({type:e.target.value})}>{types.map(t=><option key={t}>{t}</option>)}</select></label><label>Layer<select value={marker.layerId} onChange={e=>patchMarker({layerId:e.target.value})}>{atlas.layers.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div><div className="builder-grid">{['x','y'].map(axis=><label key={axis}>{axis.toUpperCase()} position (%)<input type="number" min="0" max="100" step="0.1" value={Number((marker[axis]*100).toFixed(2))} onChange={e=>patchMarker({[axis]:Math.max(0,Math.min(100,Number(e.target.value)))/100})}/></label>)}</div><label className="atlas-check"><input type="checkbox" checked={marker.public} onChange={e=>patchMarker({public:e.target.checked})}/>Include this location in player exports</label><Text label="Player-visible location notes" area value={marker.notes} onChange={notes=>patchMarker({notes})}/>{view==='gm'&&<><Text label="Private GM location notes" area value={marker.gmNotes} onChange={gmNotes=>patchMarker({gmNotes})}/><label>Connect to world lore<select value={marker.worldField} onChange={e=>patchMarker({worldField:e.target.value})}><option value="">No world record</option>{fieldOptions.map(f=><option key={f.value} value={f.value}>{f.label}</option>)}</select></label>{worldRecord&&<details><summary>{worldRecord.label}</summary><p className="notes">{worldRecord.valueText||'This world field is still empty.'}</p><small>This linked world text is GM reference only. Copy approved text into player-visible notes to include it in a handout.</small></details>}<label>Connect to another map<select value={marker.targetMapId} onChange={e=>patchMarker({targetMapId:e.target.value})}><option value="">No map connection</option>{otherMaps.map(m=><option key={m.key} value={atlasFor(m).id}>{m.name}</option>)}</select></label></>}{!readOnly&&<button type="button" className="secondary" onClick={()=>{change({markers:atlas.markers.filter(m=>m.id!==selected)});setSelected('');}}>Remove location</button>}</fieldset>}
        {marker?.targetMapId&&view==='gm'&&<button type="button" className="secondary" onClick={()=>openMap(marker.targetMapId)}>Open connected map</button>}
        {route&&visible(route)&&<fieldset disabled={readOnly}><legend>{route.kind==='border'?'Border details':'Travel route details'}</legend><Text label="Path name" value={route.name} onChange={name=>patchRoute({name})} max={160}/><label>Path layer<select value={route.layerId} onChange={e=>patchRoute({layerId:e.target.value})}>{atlas.layers.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="atlas-check"><input type="checkbox" checked={route.public} onChange={e=>patchRoute({public:e.target.checked})}/>Include this path in player exports</label>{view==='gm'&&route.kind!=='border'&&<><label>Travel difficulty multiplier<input type="number" min="0.01" max="100" step="0.1" value={route.factor} onChange={e=>patchRoute({factor:Number(e.target.value)})}/></label><Text label="GM travel time override" value={route.override} onChange={override=>patchRoute({override})} max={200}/><p>{routeSummary(route,atlas,aspect)}</p></>}{!readOnly&&<button type="button" className="secondary" onClick={()=>{change({routes:atlas.routes.filter(r=>r.id!==selected)});setSelected('');}}>Remove path</button>}</fieldset>}
        {!selected&&<p className="builder-caption">Select a location or path from the map or list to read its notes.</p>}
        <details className="atlas-settings" open><summary>Annotation layers</summary>{atlas.layers.filter(l=>view==='gm'||l.public).map(l=><div className="atlas-layer" key={l.id}><label className="atlas-check"><input type="checkbox" disabled={readOnly} checked={l.visible} onChange={e=>change({layers:atlas.layers.map(row=>row.id===l.id?{...row,visible:e.target.checked}:row)})}/>{l.name}</label>{!readOnly&&view==='gm'&&<details><summary>Edit layer</summary><Text label="Layer name" max={80} value={l.name} onChange={name=>change({layers:atlas.layers.map(row=>row.id===l.id?{...row,name}:row)})}/><label>Layer color<input type="color" value={l.color} onChange={e=>change({layers:atlas.layers.map(row=>row.id===l.id?{...row,color:e.target.value}:row)})}/></label><label className="atlas-check"><input type="checkbox" checked={l.public} onChange={e=>change({layers:atlas.layers.map(row=>row.id===l.id?{...row,public:e.target.checked}:row)})}/>Allow player-visible annotations on this layer</label></details>}</div>)}{!readOnly&&view==='gm'&&<button type="button" className="secondary" disabled={atlas.layers.length>=20} onClick={()=>change({layers:[...atlas.layers,{id:crypto.randomUUID(),name:'Custom layer',color:'#769c80',public:false,visible:true}]})}>Add custom layer</button>}</details>
        {view==='gm'&&<details className="atlas-settings"><summary>Map connections &amp; travel rules</summary><fieldset disabled={readOnly}><label>Parent map<select value={atlas.parentMapId} onChange={e=>change({parentMapId:e.target.value})}><option value="">Top-level map</option>{otherMaps.map(m=><option key={m.key} value={atlasFor(m).id}>{m.name}</option>)}</select></label><p className="builder-caption">Maps can link world → region → town → building, or sky → surface → underground. Missing maps can be reconnected later.</p><p>{atlas.scale?`Map scale: ${atlas.scale.distance} ${atlas.scale.unit} between your reference points.`:'No distance scale set yet.'}</p><label>Distance traveled per time unit<input type="number" min="0" max="1000000000000" step="any" value={atlas.travel.rate} onChange={e=>change({travel:{...atlas.travel,rate:Number(e.target.value)}})}/></label><Text label="Travel time unit (day, hour, watch…)" max={40} value={atlas.travel.period} onChange={period=>change({travel:{...atlas.travel,period}})}/><p className="builder-caption">Travel estimates use your chosen rule set’s rates. Enter your own rate; zero leaves time estimates off.</p></fieldset></details>}
      </aside></div>
      <details className="atlas-export" open><summary>Player &amp; GM exports</summary><fieldset disabled={readOnly}><Text label="Player handout title" max={160} value={atlas.publicTitle} onChange={publicTitle=>change({publicTitle})}/><label className="atlas-check"><input type="checkbox" checked={atlas.playerSafeBase} onChange={e=>change({playerSafeBase:e.target.checked})}/>The uploaded base image contains no secrets and is safe for players</label></fieldset><p className="builder-caption">Player files exclude private locations, GM notes, world-record links, map connections, and hidden layers. Only visible, approved annotations are included. Export uses the current edits; save annotations to keep them in your library.</p><div className="atlas-export-buttons"><button type="button" disabled={!atlas.playerSafeBase} onClick={()=>run(()=>downloadMap(map,atlas,'player'))}>Download player map</button><button type="button" className="secondary" onClick={()=>run(()=>downloadMap(map,atlas,'gm'))}>Download GM map</button><button type="button" className="secondary" disabled={!atlas.playerSafeBase} onClick={()=>run(()=>downloadMapKey(map,atlas,'player'))}>Download player location key</button><button type="button" className="secondary" onClick={()=>run(()=>downloadMapKey(map,atlas,'gm'))}>Download GM location key</button><button type="button" className="secondary" onClick={()=>run(async()=>{validateAtlas(atlas);downloadBlob(new Blob([JSON.stringify({version:1,kind:'savage-master-map-annotations',atlas},null,2)],{type:'application/json'}),'map-annotations-GM.json');return 'Annotation backup downloaded, including private GM notes. Download the original image separately.';})}>Download annotation backup (GM)</button></div>
        {!readOnly&&<label>Restore annotation backup<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;await run(async()=>{if(file.size>1200000)throw new Error('Choose an annotation JSON backup under 1.2 MB.');const snap=JSON.parse(await file.text());if(snap.version!==1||snap.kind!=='savage-master-map-annotations')throw new Error('Choose a Savage Master map annotation backup.');const next={...snap.atlas,id:atlas.id};validateAtlas(next);if(confirm('Replace the annotations on this map? Save or download a backup of your current annotations first.')){setAtlas(next);setSelected('');setMode('inspect');setPoints([]);setCalibration([]);}return 'Backup read. Save annotations to keep restored changes.';});}}/></label>}
        <div className="atlas-print-options"><label>Print copy<select value={printAudience} onChange={e=>setPrintAudience(e.target.value)}><option value="player">Player copy</option><option value="gm">GM reference</option></select></label><label>Paper<select value={print.paper} onChange={e=>setPrint({...print,paper:e.target.value})}>{Object.entries(printPapers).map(([id,p])=><option key={id} value={id}>{p.name}</option>)}</select></label><label>Orientation<select value={print.orientation} onChange={e=>setPrint({...print,orientation:e.target.value})}><option value="landscape">Landscape</option><option value="portrait">Portrait</option></select></label><label>Print size<select value={print.mode} onChange={e=>setPrint({...print,mode:e.target.value})}><option value="fit">Fit on one sheet</option><option value="poster">Tiled poster</option></select></label>{print.mode==='poster'&&<label>Printed map width (inches)<input type="number" min="1" max="200" step=".25" value={print.width} onChange={e=>setPrint({...print,width:Number(e.target.value)})}/></label>}</div><p className="builder-caption">{layout?`${layout.pages} map sheet(s), ${layout.columns} column(s) × ${layout.rows} row(s), plus a location key. ${print.mode==='poster'?'Overlapping edges help you assemble the poster.':''}`:'Reduce the map width or choose valid print dimensions.'}</p><button type="button" disabled={!layout||printAudience==='player'&&!atlas.playerSafeBase} onClick={()=>run(()=>printMap(map,atlas,printAudience,print))}>Print / save map PDF</button>
      </details>
    </fieldset>
  </dialog>;
}
