import progression from './pathfinder-data/progression.json' with {type:'json'};
import feats from './pathfinder-data/feats.json' with {type:'json'};
import spells from './pathfinder-data/spells.json' with {type:'json'};
import backgrounds from './pathfinder-data/backgrounds.json' with {type:'json'};
import equipment from './pathfinder-data/equipment.json' with {type:'json'};
import ancestries from './pathfinder-data/ancestries.json' with {type:'json'};
import classes from './pathfinder-data/classes.json' with {type:'json'};
export const attributes=['str','dex','con','int','wis','cha'];
export const skills={Acrobatics:'dex',Arcana:'int',Athletics:'str',Crafting:'int',Deception:'cha',Diplomacy:'cha',Intimidation:'cha',Medicine:'wis',Nature:'wis',Occultism:'int',Performance:'cha',Religion:'wis',Society:'int',Stealth:'dex',Survival:'wis',Thievery:'dex'};
export const rankNames=['Untrained','Trained','Expert','Master','Legendary'];
export const proficiency=(rank,level=1)=>rank?level+rank*2:0;
export function attributeModifier(c,attribute){let result=Object.values(c.boosts||{}).filter(b=>b.includes(attribute)).length,partial=false;for(const level of [5,10,15,20])if(level<=c.level&&c.advancement?.[level]?.includes(attribute)){if(result<4)result++;else if(partial){result++;partial=false;}else partial=true;}return result;}
export function classFeatures(c){return (progression[c.className]||[]).filter(r=>r.level<=c.level).sort((a,b)=>a.level-b.level);}
export function classRanks(c){const cl=classes.find(x=>x.name===c.className)?.data;const ranks={...cl?.attacks,...cl?.defenses,...cl?.savingThrows,perception:cl?.perception||0,spellcasting:cl?.spellcasting||0};for(const feature of classFeatures(c))for(const [key,value] of Object.entries(feature.proficiencies))if(typeof value.rank==='number')ranks[key]=Math.max(ranks[key]||0,value.rank);return ranks;}
export function skillRank(c,name){const cl=classes.find(x=>x.name===c.className)?.data,bg=backgrounds.find(x=>x.name===c.background)?.data;let rank=Math.max(c.ranks[name]||0,cl?.trainedSkills.value.includes(name.toLowerCase())?1:0,bg?.trainedSkills.value.includes(name.toLowerCase())?1:0);for(const advance of c.skillAdvances||[])if(advance.level<=c.level&&advance.skill===name)rank++;return rank;}
export function skillIncreaseLevels(c){return classes.find(x=>x.name===c.className)?.data.skillIncreaseLevels.value.filter(n=>n<=c.level)||[];}
export function validateProgress(c){if(!c||typeof c!=='object')throw Error('Invalid character.');const stages=c.advancement||{};if(typeof stages!=='object'||Array.isArray(stages))throw Error('Invalid advancement.');for(const [level,boosts] of Object.entries(stages))if(!['5','10','15','20'].includes(level)||Number(level)>c.level||!Array.isArray(boosts)||boosts.length>4||new Set(boosts).size!==boosts.length||boosts.some(a=>!attributes.includes(a)))throw Error('Invalid advancement boosts.');if(c.skillAdvances!==undefined){if(!Array.isArray(c.skillAdvances)||c.skillAdvances.length>19)throw Error('Invalid skill increases.');const levels=skillIncreaseLevels(c),seen=new Set();for(const a of [...c.skillAdvances].sort((x,y)=>x.level-y.level)){if(!levels.includes(a.level)||seen.has(a.level)||!Object.hasOwn(skills,a.skill))throw Error('Invalid skill increase.');seen.add(a.level);const prior={...c,level:a.level,skillAdvances:c.skillAdvances.filter(x=>x.level<a.level)};const rank=skillRank(prior,a.skill)+1;if(rank>4||(rank>=3&&a.level<7)||(rank>=4&&a.level<15))throw Error('Skill rank is not available at that level.');}}
 if(c.allowanceCp!==undefined&&(!Number.isInteger(c.allowanceCp)||c.allowanceCp<0||c.allowanceCp>100000000))throw Error('Invalid allowance.');if(c.quantities!==undefined){if(!c.quantities||typeof c.quantities!=='object'||Array.isArray(c.quantities)||Object.keys(c.quantities).length>100)throw Error('Invalid quantities.');for(const [id,n] of Object.entries(c.quantities))if(!c.inventory?.some(r=>r.id===id)||!Number.isInteger(n)||n<1||n>999)throw Error('Invalid quantity.');}if(c.totals!==undefined){if(!c.totals||typeof c.totals!=='object'||Array.isArray(c.totals))throw Error('Invalid totals.');for(const [key,n] of Object.entries(c.totals))if(!['ac','hp','attack','speed','spellAttack','spellDC'].includes(key)||!Number.isInteger(n)||n<0||n>10000)throw Error('Invalid final total.');}const state=c.castingState;if(state!==undefined){if(!state||!['arcane','divine','occult','primal'].includes(state.tradition)||!['prepared','spontaneous'].includes(state.mode)||!Number.isInteger(state.focusMax)||state.focusMax<0||state.focusMax>3||!Number.isInteger(state.focusUsed)||state.focusUsed<0||state.focusUsed>state.focusMax||!state.slots||typeof state.slots!=='object'||Array.isArray(state.slots)||Object.keys(state.slots).length>10||!Array.isArray(state.preparations)||state.preparations.length>100)throw Error('Invalid spellcasting state.');for(const [rank,slot] of Object.entries(state.slots))if(!/^(?:[1-9]|10)$/.test(rank)||Number(rank)>Math.ceil(c.level/2)||!Number.isInteger(slot.max)||slot.max<0||slot.max>20||!Number.isInteger(slot.used)||slot.used<0||slot.used>slot.max)throw Error('Invalid spell slots.');for(const rank of new Set(state.preparations.map(p=>p.rank)))if(state.preparations.filter(p=>p.rank===rank).length>(state.slots[rank]?.max||0))throw Error('Too many prepared spells for that rank.');for(const p of state.preparations){const spell=c.spellbook?.find(x=>x.id===p.spellId);if(!spell||!Number.isInteger(p.rank)||p.rank<spell.data.level.value||p.rank>Math.ceil(c.level/2)||typeof p.used!=='boolean'||spell.data.traits.value.some(t=>['cantrip','focus'].includes(t)))throw Error('Invalid prepared spell.');}}
}
export function fresh(){return {setting:'pathfinder2e',name:'',ancestry:'Human',heritage:'',background:'',className:'Fighter',level:1,advancement:{},skillAdvances:[],castingState:{tradition:'arcane',mode:'prepared',focusMax:0,focusUsed:0,slots:{},preparations:[]},conditions:{},totals:{},quantities:{},allowanceCp:1500,boosts:{ancestry:[],background:[],class:[],free:[]},ranks:{},feats:[],inventory:[],spellbook:[],slots:[0,0],casting:'int',spellRank:1,armor:null,weapon:null,shield:false,currentHp:null,tempHp:0,notes:'',equipment:'',spells:'',concept:''};}
export function stats(c){const a=ancestries.find(x=>x.name===c.ancestry)?.data,cl=classes.find(x=>x.name===c.className)?.data;const mods=Object.fromEntries(attributes.map(x=>[x,attributeModifier(c,x)]));const ranks=classRanks(c),prof=r=>proficiency(r,c.level),hp=(a?.hp||0)+((cl?.hp||0)+mods.con)*c.level+(c.feats.some(r=>r.name==='Toughness')?c.level:0);const armor=c.armor,weapon=c.weapon;const ar=ranks[armor?.data.category||'unarmored']||0;const dex=Math.min(mods.dex,armor?.data.dexCap??mods.dex),ac=10+dex+prof(ar)+(armor?.data.acBonus||0)+(armor?.data.runes?.potency||0)+(c.shield?Math.max(0,...c.inventory.filter(r=>r.type==='shield').map(r=>r.data.acBonus||0)):0);const ability=weapon?.data.range?mods.dex:weapon?.data.traits.value.includes('finesse')?Math.max(mods.str,mods.dex):mods.str;const weaponRank=weapon?ranks[weapon.data.category]||0:0;const attack=weapon?ability+prof(weaponRank)+(weapon.data.runes?.potency||0):0;const result={mods,hp,ac,speed:Math.max(5,(a?.speed||25)+(c.feats.some(r=>r.name==='Fleet')?5:0)+(armor?Math.min(0,(armor.data.speedPenalty||0)+(mods.str>=(armor.data.strength||0)?5:0)):0)),perception:mods.wis+prof(ranks.perception||0),saves:Object.fromEntries(Object.entries(cl?.savingThrows||{}).map(([k,r])=>[k,mods[{fortitude:'con',reflex:'dex',will:'wis'}[k]]+prof(ranks[k]||r)+(armor?.data.runes?.resilient||0)])),skills:Object.fromEntries(Object.entries(skills).map(([k,v])=>[k,mods[v]+prof(skillRank(c,k))])),attack,damage:weapon?`${Math.max(weapon.data.damage.dice,1+(weapon.data.runes?.striking||0))}${weapon.data.damage.die} ${weapon.data.range?(weapon.data.traits.value.some(t=>t.startsWith('thrown'))?' + '+mods.str:weapon.data.traits.value.includes('propulsive')?' + '+(mods.str<0?mods.str:Math.floor(mods.str/2)):''):(mods.str?' + '+mods.str:'')}${classFeatures(c).some(r=>r.name==='Weapon Specialization')&&weaponRank>=2?' + '+((classFeatures(c).some(r=>r.name==='Greater Weapon Specialization')?2:1)*weaponRank):''} ${weapon.data.damage.damageType}`:'',map:weapon?.data.traits.value.includes('agile')?[0,-4,-8]:[0,-5,-10],spellAttack:mods[c.casting]+prof(ranks.spellcasting||0),spellDC:10+mods[c.casting]+prof(ranks.spellcasting||0)};for(const [key,value] of Object.entries(c.totals||{}))if(Number.isFinite(value))result[key]=value;return result;}
export function validate(c){validateProgress(c);if(!c.boosts||!c.ranks||typeof c.ranks!=='object'||Array.isArray(c.ranks)||typeof c.shield!=='boolean')throw Error('Invalid character details.');if(!c||c.setting!=='pathfinder2e'||typeof c.name!=='string'||c.name.length>120||(!Number.isInteger(c.level)||c.level<1||c.level>20)||!ancestries.some(a=>a.name===c.ancestry)||!classes.some(a=>a.name===c.className))throw Error('Invalid Pathfinder character.');for(const k of ['concept','notes','equipment','spells','background','heritage'])if(typeof c[k]!=='string'||c[k].length>10000)throw Error('Invalid notes.');for(const [k,b] of Object.entries(c.boosts)){if(!['ancestry','background','class','free'].includes(k)||!Array.isArray(b)||new Set(b).size!==b.length||b.some(a=>!attributes.includes(a))||b.length>({ancestry:2,background:2,class:1,free:4}[k]))throw Error('Invalid boosts.');}for(const [k,r] of Object.entries(c.ranks))if(!Object.hasOwn(skills,k)||![0,1].includes(r))throw Error('Invalid training.');for(const k of ['feats','inventory','spellbook'])if(!Array.isArray(c[k])||c[k].length>100||c[k].some(x=>!x||typeof x.id!=='string'||typeof x.name!=='string'))throw Error('Invalid choices.');if(c.currentHp!==null&&(!Number.isInteger(c.currentHp)||c.currentHp<0||c.currentHp>10000))throw Error('Invalid health.');if(!Number.isInteger(c.tempHp)||c.tempHp<0||c.tempHp>10000)throw Error('Invalid health.');for(const r of [...c.inventory,...(c.armor?[c.armor]:[]),...(c.weapon?[c.weapon]:[])]){const original=equipment.find(x=>x.id===r.id);if(!original||JSON.stringify(r)!==JSON.stringify(original))throw Error('Invalid equipment data.');}for(const [rows,catalogue] of [[c.feats,feats],[c.spellbook,spells]])for(const r of rows){const original=catalogue.find(x=>x.id===r.id);if(!original||JSON.stringify(r)!==JSON.stringify(original))throw Error('Invalid rule data.');}if(!attributes.includes(c.casting)||!Array.isArray(c.slots)||c.slots.length!==2||c.slots.some(n=>!Number.isInteger(n)||n<0||n>20))throw Error('Invalid casting.');}

export function budget(c){return (c.allowanceCp??1500)-c.inventory.reduce((sum,r)=>sum+(c.quantities?.[r.id]||1)*Object.entries(r.data.price?.value||{}).reduce((n,[k,v])=>n+v*({pp:1000,gp:100,sp:10,cp:1}[k]||0),0),0);}
export function issues(c){const list=[];if(!c.name.trim())list.push('Enter your name.');if(!c.background)list.push('Choose a background.');for(const [k,count] of Object.entries({ancestry:2,background:2,class:1,free:4}))if(c.boosts[k]?.length!==count)list.push('Complete '+k+' boosts.');const cl=classes.find(r=>r.name===c.className),bg=backgrounds.find(r=>r.name===c.background);if(c.boosts.class.length&&!cl.data.keyAbility.value.includes(c.boosts.class[0]))list.push('Choose your class key attribute.');if(bg&&c.boosts.background.length===2&&!c.boosts.background.some(a=>bg.data.boosts['0'].value.includes(a)))list.push('One background boost must use its allowed attributes.');for(const level of [5,10,15,20].filter(n=>n<=c.level))if(c.advancement?.[level]?.length!==4)list.push('Choose four advancement boosts at level '+level+'.');if(budget(c)<0)list.push('Equipment exceeds your recorded allowance.');return list;}
