import feats from './pathfinder-data/feats.json' with {type:'json'};
import spells from './pathfinder-data/spells.json' with {type:'json'};
import backgrounds from './pathfinder-data/backgrounds.json' with {type:'json'};
import equipment from './pathfinder-data/equipment.json' with {type:'json'};
import ancestries from './pathfinder-data/ancestries.json' with {type:'json'};
import classes from './pathfinder-data/classes.json' with {type:'json'};
export const attributes=['str','dex','con','int','wis','cha'];
export const skills={Acrobatics:'dex',Arcana:'int',Athletics:'str',Crafting:'int',Deception:'cha',Diplomacy:'cha',Intimidation:'cha',Medicine:'wis',Nature:'wis',Occultism:'int',Performance:'cha',Religion:'wis',Society:'int',Stealth:'dex',Survival:'wis',Thievery:'dex'};
export const rankNames=['Untrained','Trained','Expert','Master','Legendary'];
export const proficiency=(rank,level=1)=>rank?level+rank*2:0;
export function fresh(){return {setting:'pathfinder2e',name:'',ancestry:'Human',heritage:'',background:'',className:'Fighter',level:1,boosts:{ancestry:[],background:[],class:[],free:[]},ranks:{},feats:[],inventory:[],spellbook:[],slots:[0,0],casting:'int',spellRank:1,armor:null,weapon:null,shield:false,currentHp:null,tempHp:0,notes:'',equipment:'',spells:'',concept:''};}
export function stats(c){const a=ancestries.find(x=>x.name===c.ancestry)?.data,cl=classes.find(x=>x.name===c.className)?.data;const mods=Object.fromEntries(attributes.map(x=>[x,Object.values(c.boosts).filter(b=>b.includes(x)).length]));const prof=r=>proficiency(r,c.level),hp=(a?.hp||0)+(cl?.hp||0)+mods.con;const armor=c.armor,weapon=c.weapon;const ar=cl?.defenses[armor?.data.category||'unarmored']||0;const dex=Math.min(mods.dex,armor?.data.dexCap??mods.dex),ac=10+dex+prof(ar)+(armor?.data.acBonus||0)+(c.shield?2:0);const ability=weapon?.data.range?mods.dex:weapon?.data.traits.value.includes('finesse')?Math.max(mods.str,mods.dex):mods.str;const attack=weapon?ability+prof(cl?.attacks[weapon.data.category]||0):0;return {mods,hp,ac,speed:Math.max(5,(a?.speed||25)+(armor?Math.min(0,(armor.data.speedPenalty||0)+(mods.str>=(armor.data.strength||0)?5:0)):0)),perception:mods.wis+prof(cl?.perception||0),saves:Object.fromEntries(Object.entries(cl?.savingThrows||{}).map(([k,r])=>[k,mods[{fortitude:'con',reflex:'dex',will:'wis'}[k]]+prof(r)])),skills:Object.fromEntries(Object.entries(skills).map(([k,v])=>[k,mods[v]+prof((cl?.trainedSkills.value.includes(k.toLowerCase())||backgrounds.find(x=>x.name===c.background)?.data.trainedSkills.value.includes(k.toLowerCase()))?1:c.ranks[k]||0)])),attack,damage:weapon?`${weapon.data.damage.dice}${weapon.data.damage.die} ${weapon.data.range?'':mods.str?' + '+mods.str:''} ${weapon.data.damage.damageType}`:'',map:weapon?.data.traits.value.includes('agile')?[0,-4,-8]:[0,-5,-10],spellAttack:mods[c.casting]+prof(cl?.spellcasting||0),spellDC:10+mods[c.casting]+prof(cl?.spellcasting||0)};}
export function validate(c){if(!c||c.setting!=='pathfinder2e'||typeof c.name!=='string'||c.name.length>120||c.level!==1||!ancestries.some(a=>a.name===c.ancestry)||!classes.some(a=>a.name===c.className))throw Error('Invalid Pathfinder character.');for(const k of ['concept','notes','equipment','spells','background','heritage'])if(typeof c[k]!=='string'||c[k].length>10000)throw Error('Invalid notes.');for(const [k,b] of Object.entries(c.boosts)){if(!['ancestry','background','class','free'].includes(k)||!Array.isArray(b)||new Set(b).size!==b.length||b.some(a=>!attributes.includes(a))||b.length>({ancestry:2,background:2,class:1,free:4}[k]))throw Error('Invalid boosts.');}for(const [k,r] of Object.entries(c.ranks))if(!Object.hasOwn(skills,k)||![0,1].includes(r))throw Error('Invalid training.');for(const k of ['feats','inventory','spellbook'])if(!Array.isArray(c[k])||c[k].length>100||c[k].some(x=>!x||typeof x.id!=='string'||typeof x.name!=='string'))throw Error('Invalid choices.');if(c.currentHp!==null&&(!Number.isInteger(c.currentHp)||c.currentHp<0||c.currentHp>10000))throw Error('Invalid health.');if(!Number.isInteger(c.tempHp)||c.tempHp<0||c.tempHp>10000)throw Error('Invalid health.');for(const r of [...c.inventory,...(c.armor?[c.armor]:[]),...(c.weapon?[c.weapon]:[])]){const original=equipment.find(x=>x.id===r.id);if(!original||JSON.stringify(r)!==JSON.stringify(original))throw Error('Invalid equipment data.');}for(const [rows,catalogue] of [[c.feats,feats],[c.spellbook,spells]])for(const r of rows){const original=catalogue.find(x=>x.id===r.id);if(!original||JSON.stringify(r)!==JSON.stringify(original))throw Error('Invalid rule data.');}if(!attributes.includes(c.casting)||!Array.isArray(c.slots)||c.slots.length!==2||c.slots.some(n=>!Number.isInteger(n)||n<0||n>20))throw Error('Invalid casting.');}

export function budget(c){return 1500-c.inventory.reduce((sum,r)=>sum+Object.entries(r.data.price?.value||{}).reduce((n,[k,v])=>n+v*({pp:1000,gp:100,sp:10,cp:1}[k]||0),0),0);}
export function issues(c){const list=[];if(!c.name.trim())list.push('Enter your name.');if(!c.background)list.push('Choose a background.');for(const [k,count] of Object.entries({ancestry:2,background:2,class:1,free:4}))if(c.boosts[k]?.length!==count)list.push('Complete '+k+' boosts.');const cl=classes.find(r=>r.name===c.className),bg=backgrounds.find(r=>r.name===c.background);if(c.boosts.class.length&&!cl.data.keyAbility.value.includes(c.boosts.class[0]))list.push('Choose your class key attribute.');if(bg&&c.boosts.background.length===2&&!c.boosts.background.some(a=>bg.data.boosts['0'].value.includes(a)))list.push('One background boost must use its allowed attributes.');if(budget(c)<0)list.push('Equipment exceeds your 15 GP allowance.');return list;}
