import React, { useState, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { ConvexReactClient, useConvexAuth, useQuery, useMutation, useAction } from 'convex/react';
import { ConvexAuthProvider, useAuthActions } from '@convex-dev/auth/react';
import { makeFunctionReference as ref } from 'convex/server';
import { CharacterAccount } from './account.jsx';
import { friendlyError } from './community-ui.jsx';
import { ProfileFrameSettings } from './profile-frame-settings.jsx';
import './campaigns.css';
import './profile.css';
import './community.css';
export function SettingsPage() {
  const {isAuthenticated,isLoading}=useConvexAuth(), {signOut,signIn}=useAuthActions();
  const profile=useQuery(ref('profiles:mine'),isAuthenticated?{}:'skip'), account=useQuery(ref('accountSettings:mine'),isAuthenticated?{}:'skip'), follows=useQuery(ref('chronicles:following'),isAuthenticated?{}:'skip');
  const review=useMutation(ref('profiles:requestReview')), unpublish=useMutation(ref('profiles:unpublish')), remove=useMutation(ref('profiles:deleteProfile')), followers=useMutation(ref('chronicles:setFollowers')), password=useAction(ref('accountSettings:changePassword'));
  const canReview=useQuery(ref('profiles:canReview'),isAuthenticated?{}:'skip');
  const [appearance,setAppearance]=useState(()=>window.smAppearance?.getPreference() || 'auto');
  const [status,setStatus]=useState(''),[busy,setBusy]=useState(false),[policy,setPolicy]=useState(false),[confirmation,setConfirmation]=useState(''),[deleting,setDeleting]=useState(false),[resetting,setResetting]=useState(false);
  useEffect(()=>{const update=()=>setAppearance(window.smAppearance?.getPreference()||'auto');window.addEventListener('sm:appearance-change',update);return()=>window.removeEventListener('sm:appearance-change',update);},[]);
  async function run(fn,message){setBusy(true);setStatus('');try{await fn();setStatus(message);}catch(e){setStatus(friendlyError(e));}finally{setBusy(false);}}
  function download(){const {ownerId,...details}=profile;const blob=new Blob([JSON.stringify({profile:details},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${profile.handle}-profile.json`;a.click();URL.revokeObjectURL(url);}
  return <main className="settings-page"><a href="/profile">Back to my profile</a><header className="workspace-hero"><span className="profile-eyebrow">Make yourself at home</span><h1>Settings</h1><p>Your appearance, account, sharing, and privacy in one place.</p></header>
    <nav className="settings-nav" aria-label="Settings sections"><a href="#appearance">Appearance</a><a href="#review">Profile review</a><a href="#security">Password</a><a href="#privacy">Privacy</a><a href="#profile-data">Profile & data</a></nav>
    {canReview === true && <section><h2>Moderation workspace</h2><p>Review submitted and reported profiles in your private workspace.</p><a href="/profile-reviews">Open profile reviews</a></section>}
    <ProfileFrameSettings />
    <section id="appearance"><h2>Appearance</h2><p>Follow your device, or choose the light parchment or dark forest theme.</p><label>Color theme<select value={appearance} onChange={e=>window.smAppearance?.setPreference(e.target.value)}><option value="auto">Follow device</option><option value="light">Light</option><option value="dark">Dark</option></select></label></section>
    {isLoading?<p>Checking account…</p>:!isAuthenticated?<><p>Sign in for account settings.</p><CharacterAccount accountOnly/></>:<>
      <section id="review"><h2>Access to Around the Fire</h2>{profile===undefined?<p>Opening profile…</p>:!profile?<p><a href="/profile">Finish your profile</a> to automatically request review.</p>:<><p>Status: <strong>{profile.reviewStatus==='pending'?'Awaiting review':profile.reviewStatus==='approved'?'Approved':profile.reviewStatus==='rejected'?'Changes requested':'Private'}</strong></p>{profile.reviewNote&&<blockquote>{profile.reviewNote}</blockquote>}{profile.reviewStatus==='approved'?<p>Your public profile and posting access are ready. <a href="/chronicles">Open Around the Fire</a>.</p>:profile.reviewStatus==='pending'?<p>Your request is in the queue. Bug will keep it here while the team reviews your chosen profile details.</p>:<><p>Review grants a public profile and posting access. Update your details first, then submit them here.</p><a href="/profile?edit=1">Edit my profile</a><label className="check"><input type="checkbox" checked={policy} onChange={e=>setPolicy(e.target.checked)}/>I accept the community rules and sharing my chosen profile details publicly after approval.</label><button disabled={busy||!policy} onClick={()=>run(()=>review({}),'Your profile was submitted for review.')}>Request profile review</button></>}</>}</section>
      <section id="security"><h2>Change password</h2><p>{account?.email} · {account?.verified?'Email verified':'Verify your email before changing your password.'}</p>{!resetting?<form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);if(form.get('newPassword')!==form.get('confirmPassword')){setStatus('The new passwords must match.');return;}const currentPassword=String(form.get('currentPassword')),newPassword=String(form.get('newPassword'));e.currentTarget.reset();run(async()=>{await password({currentPassword,newPassword});await signOut();},'Password changed. Sign in again with your new password.');}}><label>Current password<input name="currentPassword" type="password" required maxLength={256} autoComplete="current-password"/></label><label>New password<input name="newPassword" type="password" required minLength={8} maxLength={256} autoComplete="new-password"/></label><label>Confirm new password<input name="confirmPassword" type="password" required minLength={8} maxLength={256} autoComplete="new-password"/></label><button disabled={busy||!account?.verified}>Change password & sign out</button><button type="button" className="secondary" disabled={busy||!account?.verified} onClick={()=>run(async()=>{await signIn('password',{flow:'reset',email:account.email});setResetting(true);},'Reset code sent to your email.')}>Send password reset code</button></form>:<form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);if(form.get('newPassword')!==form.get('confirmPassword')){setStatus('The new passwords must match.');return;}const code=String(form.get('code')).replace(/\D/g,''),newPassword=String(form.get('newPassword'));e.currentTarget.reset();run(async()=>{await signIn('password',{flow:'reset-verification',email:account.email,code,newPassword});setResetting(false);},'Your password has been reset.');}}><label>Email code<input name="code" required inputMode="numeric" autoComplete="one-time-code"/></label><label>New password<input name="newPassword" type="password" required minLength={8} maxLength={256} autoComplete="new-password"/></label><label>Confirm password<input name="confirmPassword" type="password" required minLength={8} maxLength={256} autoComplete="new-password"/></label><button disabled={busy||!account?.verified}>Reset password</button></form>}</section>
      <section id="privacy"><h2>Privacy & connections</h2><label className="check"><input type="checkbox" disabled={busy||!follows} checked={follows?.allowFollowers!==false} onChange={e=>run(()=>followers({enabled:e.target.checked}),'Follower preference saved.')}/>Allow people to follow my public profile</label>{profile&&['approved','pending'].includes(profile.reviewStatus)&&<button type="button" className="secondary" disabled={busy} onClick={()=>run(()=>unpublish({}),'Your profile is now private; posting requires review again.')}>Make my profile private</button>}<p><a href="/profile#friends">Manage friends and blocked profiles</a></p></section>
      <section id="profile-data"><h2>Your profile & data</h2><p>Your personal page holds your background, social links, follows, and public stories.</p><a href="/profile?edit=1">Edit profile, background & social links</a>{profile&&<><p><button type="button" className="secondary" onClick={download}>Download profile details</button></p><details open={deleting} onToggle={e=>setDeleting(e.currentTarget.open)}><summary>Delete profile</summary><p>This deletes your profile, removes its uploaded images, and hides your public posts, Bazaar ads, and Guilds you lead. Your sign-in account, characters, campaigns, and private journals remain.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{await remove({confirmation});setConfirmation('');setDeleting(false);},'Your profile was deleted. Your account and private game data remain.');}}><label>Type @{profile.handle} without the @ to confirm<input required value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></label><button className="danger" disabled={busy||confirmation!==profile.handle}>Delete my profile</button></form></details></>}
      <p><a href="/pricing">Billing & subscriptions</a> · <a href="/support">Support & the Bug</a></p><button type="button" className="secondary" onClick={()=>signOut()}>Sign out</button></section>
    </>}{status&&<p className="workspace-status" role="status">{status}<button type="button" aria-label="Dismiss message" onClick={()=>setStatus('')}>×</button></p>}
  </main>;
}
const url=import.meta.env.VITE_CONVEX_URL,host=typeof document!=='undefined'?document.getElementById('settingsRoot'):null;
const root=host?(import.meta.hot?.data.settingsRoot||createRoot(host)):null;
if(import.meta.hot&&root)import.meta.hot.data.settingsRoot=root;
root?.render(url?<ConvexAuthProvider client={new ConvexReactClient(url)}><SettingsPage/></ConvexAuthProvider>:<p>Settings are temporarily unavailable.</p>);
