import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {newDndCharacter,creationIssues} from '../dnd-model.mjs';
import {validateDndCharacter} from '../dnd-validation.mjs';
import {startingResources,costCopper,equipmentSection} from '../dnd-starting.mjs';
import {spellMatches,spellLevel,spellSchool,spellClasses,spellUse} from '../dnd-spells.mjs';
import {spellGuidance} from '../dnd-spell-guidance.mjs';
const spells=JSON.parse(fs.readFileSync(new URL('../dnd-rules-data/spells.json',import.meta.url))),items=JSON.parse(fs.readFileSync(new URL('../dnd-rules-data/items.json',import.meta.url)));
test('one starting path supplies either both kits, coin alternatives, or the GM budget',()=>{const c=newDndCharacter();c.name='Hero';assert.equal(startingResources(c).gold,18);assert.ok(startingResources(c).items.some(([n])=>n==='Greatsword'));c.starting={mode:'money',method:'srd',gmGold:99999};assert.equal(startingResources(c).gold,205);assert.equal(startingResources(c).items.length,0);c.starting={mode:'gm',gmGold:30,method:'srd'};assert.equal(startingResources(c).gold,30);assert.equal(startingResources(c).items.length,0);});
test('physical money rolls use entered results and never silently grant unrolled money',()=>{const c=newDndCharacter();c.name='Hero';c.starting={mode:'money',method:'custom',count:4,sides:6,multiplier:10,flat:5,rolls:[2,3,4,6]};assert.equal(startingResources(c).gold,155);validateDndCharacter(c);c.starting.rolls=[2,0,4,6];assert.ok(creationIssues(c).some(s=>s.includes('physical-dice')));assert.throws(()=>validateDndCharacter(c));c.starting.rolls=[2,8,4,6];assert.throws(()=>validateDndCharacter(c,{draft:true}));});
test('higher-level SRD money guide uses the right base and physical d10 multiplier',()=>{const c=newDndCharacter();c.starting={mode:'money',method:'higher',rolls:[7]};c.level=5;assert.equal(startingResources(c).gold,205+500+7*25);c.level=11;assert.equal(startingResources(c).gold,205+5000+7*250);c.level=17;assert.equal(startingResources(c).gold,205+20000+7*250);c.level=1;assert.ok(startingResources(c).issues.length);});
test('purchases reduce the active budget, insufficient funds block save, refunds restore it',()=>{const c=newDndCharacter();c.name='Hero';c.starting={mode:'gm',gmGold:20};c.inventory=[{name:'Longsword',page:91,quantity:1,paidCp:1500}];assert.equal(startingResources(c).balance,500);validateDndCharacter(c);c.inventory[0].quantity=2;assert.throws(()=>validateDndCharacter(c));c.inventory=[];assert.equal(startingResources(c).balance,2000);});
test('equipment categories separate mundane weapons and armor from magic items and properties',()=>{assert.equal(equipmentSection(items.find(r=>r.name==='Longsword')),'Weapons');assert.equal(equipmentSection(items.find(r=>r.name==='Shield')),'Armor & shields');assert.equal(equipmentSection(items.find(r=>r.name==='Sun Blade')),'Magic items');assert.equal(equipmentSection(items.find(r=>r.name==='Finesse')),'Properties');assert.equal(costCopper(items.find(r=>r.name==='Longsword')),1500);assert.equal(costCopper(items.find(r=>r.name==='Sun Blade')),null);});
test('spell selection respects class lists, level, school, ritual, concentration and search',()=>{const fireball=spells.find(r=>r.name==='Fireball'),detect=spells.find(r=>r.name==='Detect Magic'),bolt=spells.find(r=>r.name==='Fire Bolt');assert.equal(spellLevel(fireball),3);assert.equal(spellSchool(fireball),'Evocation');assert.ok(spellClasses(fireball).includes('Wizard'));assert.equal(spellMatches(fireball,{className:'Wizard',maxLevel:1}),false);assert.equal(spellMatches(fireball,{className:'Wizard',maxLevel:3,school:'Evocation',use:'Damage'}),true);assert.equal(spellMatches(fireball,{className:'Cleric'}),false);assert.equal(spellMatches(detect,{ritual:true,concentration:true}),true);assert.equal(spellMatches(bolt,{level:'0',search:'fire'}),true);});
test('class spell guidance preserves all levels and class-specific cantrip/preparation counts',()=>{for(const data of Object.values(spellGuidance)){assert.deepEqual(data.levels.map(r=>r.level),Array.from({length:20},(_,i)=>i+1));assert.ok(data.levels.every(r=>Number.isInteger(r.cantrips)&&r.cantrips<=6&&Number.isInteger(r.prepared)&&r.prepared<=25));}assert.equal(spellGuidance.Wizard.levels[0].prepared,4);assert.equal(spellGuidance.Wizard.levels[4].prepared,9);assert.equal(spellGuidance.Wizard.levels[19].prepared,25);assert.equal(spellGuidance.Sorcerer.levels[0].cantrips,4);assert.equal(spellGuidance.Paladin.levels[0].cantrips,0);});

test('cantrip schools and spell purposes stay accurate without matching across unrelated sentences',()=>{assert.equal(spellSchool(spells.find(r=>r.name==='Fire Bolt')),'Evocation');for(const [name,use] of [['Chromatic Orb','Damage'],['Elementalism','Utility'],['Prestidigitation','Utility'],['Conjure Animals','Summoning']])assert.equal(spellUse(spells.find(r=>r.name===name)),use,name);});
