import {test} from 'node:test';import assert from 'node:assert/strict';import {fresh,stats,validate,budget,issues} from '../pathfinder-model.mjs';import equipment from '../pathfinder-data/equipment.json' with {type:'json'};
const hero=()=>({...fresh(),name:'Test fighter',background:'Warrior',boosts:{ancestry:['str','con'],background:['str','dex'],class:['str'],free:['str','dex','con','wis']}});
test('Pathfinder initial proficiency and HP use their own rules',()=>{const c=hero(),s=stats(c);assert.equal(s.mods.str,4);assert.equal(s.hp,20);assert.equal(s.saves.fortitude,7);assert.equal(s.ac,15);assert.deepEqual(issues(c),[]);validate(c);});
test('Pathfinder mundane loadout includes trained armor, damage, MAP and budget',()=>{const c=hero();c.weapon=equipment.find(r=>r.name==='Longsword');c.armor=equipment.find(r=>r.name==='Chain Mail');c.inventory=[c.weapon,c.armor];const s=stats(c);assert.equal(s.attack,9);assert.deepEqual(s.map,[0,-5,-10]);assert.equal(s.ac,18);assert.equal(s.speed,25);assert.equal(budget(c),800);validate(c);c.weapon={...c.weapon,data:{...c.weapon.data,damage:{dice:999,die:'d20'}}};assert.throws(()=>validate(c));});
test('Pathfinder incomplete or invalid boosts cannot be treated as a finished character',()=>{const c=hero();c.boosts.class=['cha'];assert.ok(issues(c).length);c.boosts.free=['str','str'];assert.throws(()=>validate(c));});
test('Advancement applies partial boosts, repeated class HP and source proficiency grants',()=>{const c=hero();c.level=10;c.advancement={5:['str','dex','con','wis'],10:['str','dex','con','wis']};const s=stats(c);assert.equal(s.mods.str,5);assert.equal(s.mods.con,4);assert.equal(s.hp,148);assert.equal(s.saves.fortitude,20);validate(c);});
test('Skill advancement rejects early mastery and duplicate level grants',()=>{const c=hero();c.level=7;c.skillAdvances=[{level:3,skill:'Athletics'},{level:5,skill:'Athletics'},{level:7,skill:'Athletics'}];validate(c);assert.equal(stats(c).skills.Athletics,17);c.skillAdvances[1].level=3;assert.throws(()=>validate(c));c.skillAdvances=[{level:3,skill:'Intimidation'},{level:5,skill:'Intimidation'}];c.ranks.Intimidation=1;assert.throws(()=>validate(c));});
test('Spell resource state survives backups and rejects invalid focus or slots',()=>{const c=hero();c.castingState={tradition:'arcane',mode:'prepared',focusMax:2,focusUsed:1,slots:{1:{max:2,used:1}},preparations:[]};validate(JSON.parse(JSON.stringify(c)));c.castingState.focusUsed=3;assert.throws(()=>validate(c));c.castingState.focusUsed=0;c.castingState.slots[1].used=3;assert.throws(()=>validate(c));});

test('Quantity purchases and raised shields stay separate',()=>{const c=hero();const sword=equipment.find(r=>r.name==='Longsword'),shield=equipment.find(r=>r.name==='Steel Shield');c.inventory=[sword,shield];c.weapon=sword;c.quantities={[sword.id]:2};assert.equal(budget(c),1100);c.shield=true;assert.equal(stats(c).ac,17);c.inventory=[sword];assert.equal(stats(c).ac,15);assert.throws(()=>validate({...c,quantities:{bad:2}}));});
test('Explicit table totals survive backup and cannot replace arbitrary state',()=>{const c=hero();c.totals={ac:21,spellDC:25};assert.equal(stats(c).ac,21);validate(JSON.parse(JSON.stringify(c)));c.totals.mods=999;assert.throws(()=>validate(c));});

import spellProgression from '../pathfinder-data/spell-progression.json' with {type:'json'};
test('Licensed spell tables distinguish class slots through level twenty',()=>{assert.deepEqual(spellProgression.Wizard[3].slots.slice(0,3),[3,2,0]);assert.equal(spellProgression.Sorcerer[2].slots[0],4);assert.equal(spellProgression.Oracle[1].slots[0],3);assert.equal(spellProgression.Cleric[20].slots[9],1);for(const rows of Object.values(spellProgression))assert.equal(Object.keys(rows).length,20);});
