// GM capture flow preview. Production requires campaign-role authorization.
state.epicRolls=Array.isArray(state.epicRolls)?state.epicRolls:[];
const epicPanel=document.createElement('section');epicPanel.className='panel hidden';epicPanel.id='epicRollFormPanel';epicPanel.innerHTML=`<h3>Remember an Epic Roll</h3><p class="small">GM capture · Real dice, real moment · This preview saves on this device.</p><form id="epicRollForm"><label for="epicPlayer">Player character</label><select id="epicPlayer"></select><label for="epicDice">Dice rolled & results</label><input id="epicDice" required maxlength="180" placeholder="2 dice: d6 = 6 → 6 → 4; Wild d6 = 3"><label for="epicTotal">Final total (including modifiers)</label><input id="epicTotal" type="number" step="1" required><label for="epicEvent">What happened?</label><textarea id="epicEvent" required maxlength="2000" placeholder="Elian caught Mara as the bridge collapsed."></textarea><div class="assistant-actions"><button type="submit" class="primary">Save to player's journal</button><button type="button" id="epicCancel">Cancel</button></div><p class="small">Saved under The Lantern Coast · Session 04. The selected player receives the event description—leave GM secrets out.</p><p id="epicStatus" role="status" class="small"></p></form>`;document.querySelector('#table .workspace').before(epicPanel);
turnState.order.forEach(name=>{const option=document.createElement('option');option.value=name;option.textContent=name;document.getElementById('epicPlayer').append(option)});
function openEpic(){epicPanel.classList.remove('hidden');document.getElementById('epicPlayer').value=turnState.order[turnState.active];document.getElementById('epicStatus').textContent='';document.getElementById('epicDice').focus();epicPanel.scrollIntoView({block:'nearest'})}
const epicButton=document.createElement('button');epicButton.textContent='★ Epic Roll';epicButton.setAttribute('aria-controls','epicRollFormPanel');document.querySelector('.turn-controls').append(epicButton);epicButton.onclick=openEpic;
const matEpicButton=document.createElement('button');matEpicButton.textContent='★ Epic Roll';document.querySelector('#mat > .toolbar').append(matEpicButton);matEpicButton.onclick=()=>{document.querySelector('[data-view="table"]').click();openEpic()};
document.getElementById('epicCancel').onclick=()=>{epicPanel.classList.add('hidden');epicButton.focus()};
const epicJournal=document.createElement('section');epicJournal.className='panel';epicJournal.innerHTML='<h3>Epic Rolls</h3><p class="small">GM-recorded moments for Elian · Linked to your campaign and session.</p><div id="epicJournalEntries"></div>';document.getElementById('journal').append(epicJournal);
function drawEpic(){const entries=document.getElementById('epicJournalEntries');entries.replaceChildren();const rolls=state.epicRolls.filter(r=>r.character==='Elian');if(!rolls.length){const p=document.createElement('p');p.className='small';p.textContent='Your GM can bookmark a memorable roll during play.';entries.append(p)}rolls.forEach(roll=>{const card=document.createElement('article');card.className='note';const title=document.createElement('strong');title.textContent='Epic Roll · Total '+roll.total;const dice=document.createElement('p');dice.textContent=roll.dice;const event=document.createElement('p');event.textContent=roll.event;const source=document.createElement('p');source.className='small';source.textContent=roll.campaign+' · '+roll.session+' · Recorded by '+roll.gm+' · '+new Date(roll.createdAt).toLocaleDateString();card.append(title,dice,event,source);entries.append(card)})}
document.getElementById('epicRollForm').onsubmit=e=>{e.preventDefault();const character=document.getElementById('epicPlayer').value,dice=document.getElementById('epicDice').value.trim(),event=document.getElementById('epicEvent').value.trim(),total=Number(document.getElementById('epicTotal').value);if(!turnState.order.includes(character)||!dice||!event||!Number.isSafeInteger(total))return;const roll={id:crypto.randomUUID(),character,dice,total,event,campaign:'The Lantern Coast',session:'Session 04',gm:'Sample GM',createdAt:Date.now()};state.epicRolls.push(roll);save();drawEpic();e.target.reset();document.getElementById('epicStatus').textContent=`Epic Roll saved to ${character}'s demo journal. ${character==='Elian'?'Open My Journal to see it.':'The player view in this preview shows Elian only.'}`};drawEpic();
const partyMemories=document.createElement('section');partyMemories.className='panel';partyMemories.innerHTML='<h3>Party Memories</h3><p>Your journey includes the people who shared it.</p><div class="stats"><span>Elian & Vessa · 3 adventures together</span><span>Elian & Bram · 2 adventures together</span></div><article class="note"><strong>Together at the Salt Gate</strong><p>Elian kept the watch distracted while Vessa freed the watchkeeper. Bram found a path through the rising tide.</p><p class="small">Sample shared memory · The Lantern Coast / Session 03</p></article><p class="small">Planned: mutual friend invitations, shared moments you choose to keep, and your own reflections. Friendship does not expose private notes. No real invitations are sent in this preview.</p>';document.getElementById('journal').append(partyMemories);
