const resourceSection = document.createElement('section');
resourceSection.className = 'panel';
resourceSection.innerHTML = `<h3>Your resources</h3><p class="small">Keep your own websites, reference guides, and inspiration here. Demo links save on this device.</p><form id="resourceForm"><label for="resourceTitle">Resource title</label><input id="resourceTitle" maxlength="160" required placeholder="My campaign reference"><label for="resourceUrl" style="margin-top:12px">Web link</label><input id="resourceUrl" type="url" required placeholder="https://example.com"><button style="margin-top:12px" type="submit">Add resource</button><p id="resourceStatus" role="status" class="small"></p></form><div id="resourceList"></div>`;
document.getElementById('books').append(resourceSection);
state.resources = Array.isArray(state.resources) ? state.resources : [];
function resourceUrl(value){try{const url=new URL(value);if(!['https:','http:'].includes(url.protocol)||url.username||url.password)return null;return url.href}catch{return null}}
function renderResources(){const list=document.getElementById('resourceList');list.replaceChildren();if(!state.resources.length){const empty=document.createElement('p');empty.className='small';empty.textContent='No personal links yet. Add your first reference above.';list.append(empty)}state.resources.forEach((resource,index)=>{const url=resourceUrl(resource.url);if(!url)return;const row=document.createElement('div');row.className='line';const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener noreferrer';link.textContent=resource.title;const domain=document.createElement('p');domain.className='small';domain.textContent=new URL(url).hostname;const remove=document.createElement('button');remove.textContent='Remove';remove.setAttribute('aria-label',`Remove ${resource.title}`);remove.onclick=()=>{state.resources.splice(index,1);save();renderResources();document.getElementById('resourceStatus').textContent='Link removed from this demo.'};row.append(link,domain,remove);list.append(row)})}
document.getElementById('resourceForm').onsubmit=e=>{e.preventDefault();const title=document.getElementById('resourceTitle').value.trim();const url=resourceUrl(document.getElementById('resourceUrl').value.trim());const status=document.getElementById('resourceStatus');if(!title||!url){status.textContent='Add a title and a valid http or https web link without login details.';return}if(state.resources.some(r=>r.url===url)){status.textContent='That link is already in your resources.';return}state.resources.push({title,url});save();renderResources();e.target.reset();status.textContent='Resource added. Saved on this device.'};
renderResources();
