// One-device preview of GM controls and player notification, not live multiplayer.
const turnStyle=document.createElement('style');turnStyle.textContent=`.turn-banner{position:sticky;top:0;z-index:20;background:#1b6748;color:white;padding:12px 22px;display:flex;align-items:center;justify-content:space-between;gap:12px;border-bottom:3px solid #a0e6b9}.turn-banner.hidden{display:none}.turn-banner strong{font-size:19px}.turn-light{display:inline-block;width:11px;height:11px;background:#b7ffcf;border-radius:50%;margin-right:10px;box-shadow:0 0 12px #b7ffcf}.turn-arrived{animation:turnArrival .6s ease-out}@keyframes turnArrival{from{background:#329566}to{background:#1b6748}}@media(prefers-reduced-motion:reduce){.turn-arrived{animation:none}}.turn-controls{display:flex;gap:12px;align-items:end;flex-wrap:wrap}.turn-controls label{margin:0}.turn-controls button{min-height:42px}.turn-roster{display:flex;gap:8px;align-items:center;flex-wrap:wrap;padding:8px 0}`;document.head.append(turnStyle);
const turnBanner=document.createElement('div');turnBanner.className='turn-banner hidden';turnBanner.setAttribute('role','status');turnBanner.setAttribute('aria-live','polite');turnBanner.innerHTML='<span><span class="turn-light"></span><strong>Your turn</strong> <span id="turnPlayerName"></span></span><button id="playerEndTurn">End turn</button>';document.body.prepend(turnBanner);
state.turns||={enabled:false,order:['Elian','Vessa','Bram'],active:0};const turnState=state.turns;
const turnPanel=document.createElement('section');turnPanel.className='panel';turnPanel.innerHTML=`<div class="turn-controls"><label><input id="turnEnabled" type="checkbox" style="width:auto"> Turn tracker on</label><label for="activeTurn">Who's up?<select id="activeTurn"></select></label><button id="gmNextTurn" class="primary">Next turn</button></div><p id="turnStatus" role="status" class="small"></p><details><summary>Player order & preview</summary><p class="small">Use arrows to arrange the order your table uses. This preview uses sample players.</p><div id="turnRoster"></div><label for="turnPreviewPlayer">Preview this player's screen</label><select id="turnPreviewPlayer"></select><p class="small">Only the active player sees “Your turn.” This is a one-device demonstration, not connected player accounts.</p></details>`;document.querySelector('#table .workspace').before(turnPanel);
const turnMatPanel=turnPanel.cloneNode(false); // The same controls remain in Table View; mat gets an entry link.
const matTurnLink=document.createElement('button');matTurnLink.textContent='Open turn controls';matTurnLink.onclick=()=>document.querySelector('[data-view="table"]').click();document.querySelector('#mat > .toolbar').append(matTurnLink);
const activeSelect=document.getElementById('activeTurn'),previewSelect=document.getElementById('turnPreviewPlayer');let previewPlayer=turnState.order[0];
function turnOption(name,index){const option=document.createElement('option');option.value=String(index);option.textContent=name;return option}
function renderTurns(){turnState.active=Math.max(0,Math.min(turnState.order.length-1,turnState.active));document.getElementById('turnEnabled').checked=turnState.enabled;activeSelect.replaceChildren(...turnState.order.map(turnOption));activeSelect.value=String(turnState.active);previewSelect.replaceChildren(...turnState.order.map((name)=>{const o=document.createElement('option');o.value=name;o.textContent=name;return o}));previewSelect.value=previewPlayer;activeSelect.disabled=!turnState.enabled;document.getElementById('gmNextTurn').disabled=!turnState.enabled;const active=turnState.order[turnState.active];document.getElementById('turnStatus').textContent=turnState.enabled?`Now: ${active} · Next: ${turnState.order[(turnState.active+1)%turnState.order.length]}`:'Off — no player turn notifications.';const show=turnState.enabled&&active===previewPlayer;turnBanner.classList.toggle('hidden',!show);document.getElementById('turnPlayerName').textContent='— '+active;document.getElementById('playerEndTurn').disabled=!show;turnBanner.classList.remove('turn-arrived');if(show){void turnBanner.offsetWidth;turnBanner.classList.add('turn-arrived')}const roster=document.getElementById('turnRoster');roster.replaceChildren();turnState.order.forEach((name,index)=>{const row=document.createElement('div');row.className='turn-roster';const text=document.createElement('span');text.textContent=(index+1)+'. '+name;row.append(text);[-1,1].forEach(direction=>{const move=document.createElement('button');move.textContent=direction<0?'↑':'↓';move.setAttribute('aria-label',`Move ${name} ${direction<0?'earlier':'later'}`);move.disabled=index+direction<0||index+direction>=turnState.order.length;move.onclick=()=>{const current=turnState.order[turnState.active];[turnState.order[index],turnState.order[index+direction]]=[turnState.order[index+direction],turnState.order[index]];turnState.active=turnState.order.indexOf(current);save();renderTurns()};row.append(move)});roster.append(row)})}
function nextTurn(){if(!turnState.enabled)return;turnState.active=(turnState.active+1)%turnState.order.length;save();renderTurns()}
document.getElementById('turnEnabled').onchange=e=>{turnState.enabled=e.target.checked;save();renderTurns()};activeSelect.onchange=()=>{if(!turnState.enabled)return;turnState.active=Number(activeSelect.value);save();renderTurns()};document.getElementById('gmNextTurn').onclick=nextTurn;document.getElementById('playerEndTurn').onclick=()=>{if(turnState.order[turnState.active]===previewPlayer)nextTurn()};previewSelect.onchange=()=>{previewPlayer=previewSelect.value;renderTurns()};renderTurns();
